import {z} from "zod";
export const contractPartyInputSchema=z.object({companyId:z.uuid().optional(),contactId:z.uuid().optional(),role:z.string().trim().min(1).max(120)}).strict().refine(x=>Boolean(x.companyId)!==Boolean(x.contactId),"Choose one party record");
const currency=z.string().trim().length(3).transform(x=>x.toUpperCase());
export const contractCreateInputSchema=z.object({operationKey:z.uuid(),name:z.string().trim().min(1).max(200),companyId:z.uuid(),contactId:z.uuid().nullable().optional(),dealId:z.uuid().nullable().optional(),orderId:z.uuid().nullable().optional(),valueMinor:z.number().int().nonnegative().nullable().optional(),currency,effectiveAt:z.iso.datetime().nullable().optional(),expiresAt:z.iso.datetime().nullable().optional(),ownerMembershipId:z.string().min(1),parties:z.array(contractPartyInputSchema).min(1).max(50)}).strict().refine(x=>!x.effectiveAt||!x.expiresAt||Date.parse(x.expiresAt)>=Date.parse(x.effectiveAt),{message:"Expiry must not precede effective date",path:["expiresAt"]});
const commandBase={operationKey:z.uuid(),expectedRevision:z.number().int().nonnegative(),reason:z.string().trim().min(1).max(500)};
export const contractCommandInputSchema=z.discriminatedUnion("action",[
 z.object({action:z.literal("update"),...commandBase,name:z.string().trim().min(1).max(200).optional(),companyId:z.uuid().optional(),contactId:z.uuid().nullable().optional(),dealId:z.uuid().nullable().optional(),orderId:z.uuid().nullable().optional(),valueMinor:z.number().int().nonnegative().nullable().optional(),currency:currency.optional(),effectiveAt:z.iso.datetime().nullable().optional(),expiresAt:z.iso.datetime().nullable().optional(),ownerMembershipId:z.string().min(1).optional(),parties:z.array(contractPartyInputSchema).min(1).max(50).optional()}).strict(),
 z.object({action:z.literal("status"),...commandBase,status:z.enum(["draft","active","completed","terminated","expired"])}).strict(),
 z.object({action:z.literal("archive"),...commandBase}).strict(),z.object({action:z.literal("restore"),...commandBase}).strict(),
]);
export const contractListInputSchema=z.object({status:z.enum(["all","draft","active","completed","terminated","expired"]).default("all"),archived:z.coerce.boolean().default(false),limit:z.coerce.number().int().min(1).max(200).default(100)});
export const contractRowSchema=z.object({id:z.uuid(),name:z.string(),companyId:z.uuid(),contactId:z.uuid().nullable(),dealId:z.uuid().nullable(),orderId:z.uuid().nullable(),valueMinor:z.number().nullable(),currency:z.string(),effectiveAt:z.string().nullable(),expiresAt:z.string().nullable(),ownerMembershipId:z.string(),status:z.enum(["draft","active","completed","terminated","expired"]),revision:z.number(),archivedAt:z.string().nullable(),createdAt:z.string(),updatedAt:z.string()});
export const contractDetailSchema=contractRowSchema.extend({parties:z.array(z.object({partyId:z.string(),companyId:z.uuid().nullable(),contactId:z.uuid().nullable(),role:z.string()})),versions:z.array(z.object({version:z.number(),reason:z.string(),actorId:z.string(),createdAt:z.string()})),documents:z.array(z.object({id:z.uuid(),name:z.string(),size:z.number(),uploadedAt:z.string()}))});
export const contractListOutputSchema=z.object({rows:z.array(contractRowSchema)});export type ContractCreateInput=z.infer<typeof contractCreateInputSchema>;export type ContractCommandInput=z.infer<typeof contractCommandInputSchema>;
