import {and,eq,isNull,sql} from "drizzle-orm";
import type {AppDatabase} from "@/lib/db/database";
import {salesOrder,orderSequence,contact,singletonMembership} from "@/lib/db/schema";
import type {RequestContext} from "@/lib/http/request-context";
import {HttpError} from "@/lib/http/http-errors";
import {inJsonArray} from "@/lib/db/sql-filters";
import {actionGuard,requirePermission} from "../permissions/permission-policy";
import {FieldService} from "../custom-fields/field-service";
import type {PreparedRecordCreation} from "../shared/record-fields-contract";
import {orderCreateInputSchema,orderWriteOutputSchema,orderUpdateDataSchema,orderDetailOutputSchema,orderListOutputSchema,type OrderCreateInput,type OrderUpdateData,type OrderListInput} from "./order-contract";
import {preparePricing} from "./order-pricing";
import {balance,condition,conflict,fingerprint,salesError} from "./order-operations";
import {OrderRepository} from "./order-repository";
export class OrderService{
 private readonly repository:OrderRepository;constructor(private readonly db:AppDatabase){this.repository=new OrderRepository(db);}
 async preview(context:RequestContext,raw:OrderCreateInput){await requirePermission(this.db,context,["order.create"]);const input=orderCreateInputSchema.parse(raw);return (await preparePricing(this.db,input)).preview;}
 async creationReplay(context:RequestContext,id:string,raw:OrderCreateInput){await requirePermission(this.db,context);const input=orderCreateInputSchema.parse(raw),digest=await fingerprint(id,input);const row=await this.db.select().from(salesOrder).where(eq(salesOrder.id,id)).get();if(!row)return null;if(row.creatorUserId!==context.userId||row.creationFingerprint!==digest)conflict("Creation reservation is already used for another request");return orderWriteOutputSchema.parse(JSON.parse(row.creationResultJson));}
 async create(context:RequestContext,input:OrderCreateInput,creation?:PreparedRecordCreation){const p=await this.prepareCreate(context,input,creation);try{await this.db.batch(p.statements);return p.result;}catch(e){if(creation){const previous=await this.creationReplay(context,creation.recordId,input);if(previous)return previous;}p.translateError(e);}}
 async prepareCreate(context:RequestContext,raw:OrderCreateInput,creation?:PreparedRecordCreation,options?:{preparedContactId?:string}){
  const input=orderCreateInputSchema.parse(raw),permissions=["order.create" as const,...input.ownerMembershipId?["order.assign" as const]:[]];await requirePermission(this.db,context,permissions);await this.relations(input,options?.preparedContactId);
  const price=await preparePricing(this.db,input),id=creation?.recordId??crypto.randomUUID(),now=new Date();const fields=await new FieldService(this.db).prepareValues(context,{entity:"order",recordId:id,values:input.customFields??{},calendarRevision:input.calendarRevision},"create");
  const contactPredicate=options?.preparedContactId===input.contactId?sql`1=1`:sql`exists(select 1 from contact where id=${input.contactId} and archived_at is null)`;
  const auth=actionGuard(this.db,context,permissions),guard=condition(this.db,and(price.predicate,contactPredicate)!);
  const {lines,goodsMinor,originalMinor}=price.preview;const creationFingerprint=await fingerprint(id,input),creationResultJson=JSON.stringify({id,name:input.name,revision:0});
  const statements:Parameters<AppDatabase["batch"]>[0]=[auth.begin,...creation?.before??[],guard.begin,this.db.update(orderSequence).set({nextNumber:sql`${orderSequence.nextNumber}+1`}).where(eq(orderSequence.id,"orders")),this.db.insert(salesOrder).values({id,creationFingerprint,creationResultJson,number:sql`(select next_number-1 from order_sequence where id='orders')`,name:input.name,contactId:input.contactId,companyId:input.companyId??null,leadId:input.leadId??null,dealId:input.dealId??null,source:input.source??null,description:input.description??null,ownerMembershipId:input.ownerMembershipId??null,creatorUserId:context.userId,currency:input.currency,linesJson:JSON.stringify(lines),goodsMinor,discountMinor:input.discountMinor,surchargeMinor:input.surchargeMinor,taxMinor:input.taxMinor,originalMinor,goodsRemainingMinor:goodsMinor-input.discountMinor,surchargeRemainingMinor:input.surchargeMinor,taxRemainingMinor:input.taxMinor,createdAt:now,updatedAt:now}),...fields.statements,...creation?.after??[],guard.end,auth.end];
  return {statements,result:{id,name:input.name,revision:0},translateError(error:unknown):never{try{fields.translateError(error);}catch(e){salesError(e);}return salesError(error);}};
 }
 async update(context:RequestContext,id:string,raw:OrderUpdateData){const input=orderUpdateDataSchema.parse(raw),permissions=["order.update" as const,...input.ownerMembershipId!==undefined?["order.assign" as const]:[]];await requirePermission(this.db,context,permissions);const old=await this.db.select().from(salesOrder).where(eq(salesOrder.id,id)).get();if(!old)throw new HttpError(404,"not_found","Order not found");if(old.state!=="draft"||old.revision!==input.expectedRevision||old.archivedAt)conflict();
  const lines=JSON.parse(old.linesJson);const keys=["name","contactId","companyId","leadId","dealId","ownerMembershipId","source","description","currency","discountMinor","surchargeMinor","taxMinor"] as const;const merged=orderCreateInputSchema.parse({...Object.fromEntries(keys.map(k=>[k,input[k]===undefined?old[k]:input[k]])),lines:input.lines??lines.map((l:any)=>({variantId:l.variantId,expectedVariantRevision:l.expectedVariantRevision,expectedProductRevision:l.expectedProductRevision,quantity:l.quantity,unitPriceMinor:l.unitPriceMinor,discountMinor:l.discountMinor})),customFields:input.customFields,calendarRevision:input.calendarRevision});
  // Build only the public pricing shape; persisted projections are never accepted as input.
  await this.relations(merged);const price=await preparePricing(this.db,merged),fields=await new FieldService(this.db).prepareValues(context,{entity:"order",recordId:id,values:input.customFields??{},calendarRevision:input.calendarRevision});
  const auth=actionGuard(this.db,context,permissions),guard=condition(this.db,and(price.predicate,sql`exists(select 1 from sales_order where id=${id} and state='draft' and revision=${input.expectedRevision})`,sql`exists(select 1 from contact where id=${merged.contactId} and archived_at is null)`)!);
  const p=price.preview;try{await this.db.batch([auth.begin,guard.begin,this.db.update(salesOrder).set({name:merged.name,contactId:merged.contactId,companyId:merged.companyId,leadId:merged.leadId,dealId:merged.dealId,source:merged.source,description:merged.description,ownerMembershipId:merged.ownerMembershipId,currency:merged.currency,linesJson:JSON.stringify(p.lines),goodsMinor:p.goodsMinor,discountMinor:p.discountMinor,surchargeMinor:p.surchargeMinor,taxMinor:p.taxMinor,originalMinor:p.originalMinor,goodsRemainingMinor:p.goodsMinor-p.discountMinor,surchargeRemainingMinor:p.surchargeMinor,taxRemainingMinor:p.taxMinor,revision:sql`${salesOrder.revision}+1`,updatedAt:new Date()}).where(eq(salesOrder.id,id)),...fields.statements,guard.end,auth.end]);return{id,name:merged.name,revision:old.revision+1};}catch(e){try{fields.translateError(e);}catch(error){salesError(error);}}
 }
 async byId(context:RequestContext,id:string){await requirePermission(this.db,context);const row=await this.repository.byId(id);if(!row)throw new HttpError(404,"not_found","Order not found");return orderDetailOutputSchema.parse(this.serialize(row));}
 async list(context:RequestContext,input:OrderListInput){await requirePermission(this.db,context);const result=await this.repository.list(input);return orderListOutputSchema.parse({...result,rows:result.rows.map(r=>this.serialize(r))});}
 async archive(context:RequestContext,id:string,restore=false){await this.bulkArchive(context,[id],restore);const row=await this.byId(context,id);return{id,name:row.name,archivedAt:row.archivedAt};}
 async bulkArchive(context:RequestContext,ids:string[],restore=false){const auth=actionGuard(this.db,context,[restore?"order.restore":"order.archive"]),guard=condition(this.db,sql`not exists(select 1 from sales_order where ${inJsonArray(salesOrder.id,ids)} and state not in('draft','cancelled'))`);try{const [, , rows]=await this.db.batch([auth.begin,guard.begin,this.db.update(salesOrder).set({archivedAt:restore?null:new Date(),revision:sql`${salesOrder.revision}+1`,updatedAt:new Date()}).where(inJsonArray(salesOrder.id,ids)).returning({id:salesOrder.id}),guard.end,auth.end]);return{requested:ids.length,succeeded:rows.length,failed:ids.length-rows.length};}catch(e){salesError(e);}}
 private async relations(input:{contactId:string;ownerMembershipId?:string|null},preparedContactId?:string){if(input.contactId!==preparedContactId&&!await this.db.select().from(contact).where(and(eq(contact.id,input.contactId),isNull(contact.archivedAt))).get())throw new HttpError(400,"validation_failed","Choose an active contact");if(input.ownerMembershipId&&!await this.db.select().from(singletonMembership).where(and(eq(singletonMembership.userId,input.ownerMembershipId),eq(singletonMembership.status,"active"))).get())throw new HttpError(400,"validation_failed","Choose an active owner");}
 private serialize(row:NonNullable<Awaited<ReturnType<OrderRepository["byId"]>>>){const {linesJson,ownerName,ownerEmail,...rest}=row;return{...rest,lines:JSON.parse(linesJson),balanceMinor:balance(row),owner:row.ownerMembershipId?{membershipId:row.ownerMembershipId,name:ownerName,email:ownerEmail}:null,...Object.fromEntries(["confirmedAt","completedAt","cancelledAt","archivedAt","lastActivityAt","createdAt","updatedAt"].map(k=>[k,(row[k as keyof typeof row] as Date|null)?.toISOString()??null]))};}
}
