import { expect, test } from "@playwright/test";
import { getCrmDictionary } from "../../src/lib/i18n/crm-dictionary";
import type { FieldDefinition } from "../../src/lib/services/custom-fields/field-contracts";
import type { BusinessSettings } from "../../src/lib/services/settings/business-settings-contracts";

for (const locale of ["vi", "en"] as const) {
  test(`${locale}: opt-in datetime preserves milliseconds and requires explicit daylight-saving choices`, async ({ page, baseURL }) => {
    const labels = getCrmDictionary(locale), headers = { origin: baseURL! };
    expect((await page.request.post("/api/auth/sign-in/email", { headers, data: { email: process.env.E2E_OWNER_EMAIL, password: process.env.E2E_OWNER_PASSWORD } })).ok()).toBe(true);
    const settings = async () => { const response = await page.request.get("/api/crm/settings"); expect(response.ok()).toBe(true); return await response.json() as BusinessSettings; };
    const original = await settings();
    const prefix = `datetime-${locale}-${crypto.randomUUID().slice(0, 8)}`;
    async function create(path: string, data: object) { const response = await page.request.post(`/api/crm/${path}`, { headers, data }); expect(response.ok()).toBe(true); return response.json(); }
    try {
      const calendarResponse = await page.request.patch("/api/crm/settings", { headers, data: { timeZone: "America/New_York", countryCode: "US", revision: original.revision } });
      expect(calendarResponse.ok()).toBe(true);
      const calendar = await calendarResponse.json() as BusinessSettings;
      const date = await create("fields", { entity: "company", type: "date", label: `${prefix}-time`, showOnFilter: true, showOnTable: true }) as FieldDefinition;
      const legacy = await create("fields", { entity: "company", type: "date", label: `${prefix}-legacy` }) as FieldDefinition;
      const number = await create("fields", { entity: "company", type: "number", label: `${prefix}-number` }) as FieldDefinition;
      const record = await create("companies", { name: prefix });
      const originalInstant = "2030-11-03T06:30:00.123Z";
      expect((await page.request.patch("/api/crm/fields/values", { headers, data: { entity: "company", recordId: record.id, values: { [date.key]: originalInstant, [legacy.key]: originalInstant, [number.key]: 2 } } })).ok()).toBe(true);
      const stored = async () => { const response = await page.request.get(`/api/crm/fields/values?entity=company&recordId=${record.id}`); expect(response.ok()).toBe(true); return response.json(); };
      await page.goto(`/${locale}/crm/companies?q=${prefix}`);
      await page.getByRole("button", { name: labels.custom.manage, exact: true }).click();
      const sheet = page.getByRole("dialog");
      await sheet.locator("li").filter({ hasText: date.label }).getByRole("button").first().click();
      await sheet.getByLabel(labels.custom.includeTime, { exact: true }).check();
      await sheet.getByRole("button", { name: labels.save, exact: true }).click();
      await expect(sheet.getByRole("button", { name: labels.custom.add, exact: true })).toBeVisible();
      expect((await stored())[date.key]).toBe(originalInstant);
      await page.keyboard.press("Escape");
      await page.goto(`/${locale}/crm/companies?q=${prefix}&recordType=company&recordId=${record.id}&tab=fields`);
      const dialog = page.getByRole("dialog");
      const input = dialog.locator(`#custom-${date.id}`);
      await expect(input).toHaveAttribute("type", "datetime-local");
      await expect(input).toHaveValue("2030-11-03T01:30:00.123");
      await expect(dialog.locator(`#custom-${date.id}-offset`)).toHaveText("-05:00");
      await expect(dialog.locator(`#custom-${legacy.id}`)).toHaveAttribute("type", "date");
      await expect(dialog.locator(`#custom-${legacy.id}`)).toHaveValue("2030-11-03");
      await dialog.locator(`#custom-${number.id}`).fill("3");
      await dialog.getByRole("button", { name: labels.save, exact: true }).click();
      await expect(dialog.getByText(labels.custom.saved, { exact: true })).toBeVisible();
      expect((await stored())[date.key]).toBe(originalInstant);
      await input.fill("2030-03-10T02:30:00.123");
      await dialog.locator(`#custom-${number.id}`).fill("4");
      await dialog.getByRole("button", { name: labels.save, exact: true }).click();
      await expect(input).toBeFocused();
      await expect(dialog.getByRole("alert")).toHaveText(labels.custom.dateTimeGap);
      expect((await stored())[number.key]).toBe(3);
      await input.fill("2030-11-03T01:45:00.789");
      await expect(dialog.getByRole("alert")).toHaveText(labels.custom.dateTimeOverlap);
      await dialog.locator(`#custom-${date.id}-offset`).click();
      await page.getByRole("option", { name: "-05:00", exact: true }).click();
      const request = page.waitForRequest(request => request.url().endsWith("/api/crm/fields/values") && request.method() === "PATCH");
      await dialog.getByRole("button", { name: labels.save, exact: true }).click();
      expect((await request).postDataJSON().calendarRevision).toBe(calendar.revision);
      await expect(dialog.getByText(labels.custom.saved, { exact: true })).toBeVisible();
      const finalInstant = "2030-11-03T06:45:00.789Z";
      expect(await stored()).toMatchObject({ [date.key]: finalInstant, [legacy.key]: originalInstant, [number.key]: 4 });
      const concurrentInstant = "2030-11-03T05:50:00.456Z";
      expect((await page.request.patch("/api/crm/fields/values", { headers, data: { entity: "company", recordId: record.id, values: { [date.key]: concurrentInstant } } })).ok()).toBe(true);
      await dialog.locator(`#custom-${number.id}`).fill("5");
      await dialog.getByRole("button", { name: labels.save, exact: true }).click();
      await expect(input).toHaveValue("2030-11-03T01:50:00.456");
      await expect(dialog.locator(`#custom-${date.id}-offset`)).toHaveText("-04:00");
      expect((await stored())[date.key]).toBe(concurrentInstant);
      expect((await page.request.patch("/api/crm/fields/values", { headers, data: { entity: "company", recordId: record.id, values: { [date.key]: finalInstant } } })).ok()).toBe(true);
      await dialog.locator(`#custom-${number.id}`).fill("6");
      await dialog.getByRole("button", { name: labels.save, exact: true }).click();
      await expect(input).toHaveValue("2030-11-03T01:45:00.789");
      await expect(dialog.locator(`#custom-${date.id}-offset`)).toHaveText("-05:00");
      const currentCalendar = await settings();
      expect((await page.request.patch("/api/crm/settings", { headers, data: { timeZone: "UTC", countryCode: currentCalendar.countryCode, revision: currentCalendar.revision } })).ok()).toBe(true);
      await input.fill("2030-11-03T03:15:00.987");
      await dialog.locator(`#custom-${number.id}`).fill("7");
      await dialog.getByRole("button", { name: labels.save, exact: true }).click();
      await expect(dialog.getByRole("alert")).toContainText(labels.custom.calendarStale);
      expect(await stored()).toMatchObject({ [date.key]: finalInstant, [number.key]: 6 });
      await dialog.getByRole("button", { name: labels.custom.reloadFields, exact: true }).click();
      await expect(input).toHaveValue("2030-11-03T06:45:00.789");
      await expect(dialog.locator(`#custom-${number.id}`)).toHaveValue("6");
      const changedCalendar = await settings();
      expect((await page.request.patch("/api/crm/settings", { headers, data: { timeZone: "America/New_York", countryCode: changedCalendar.countryCode, revision: changedCalendar.revision } })).ok()).toBe(true);
      await page.reload();
      await expect(input).toHaveValue("2030-11-03T01:45:00.789");
      await page.setViewportSize({ width: 375, height: 812 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.screenshot({ path: test.info().outputPath(`${locale}-field-datetime-mobile.png`), animations: "disabled" });
      await page.setViewportSize({ width: 1280, height: 800 });
      await page.keyboard.press("Escape");
      await page.goto(`/${locale}/crm/companies?q=${prefix}`);
      const formatted = new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "medium", timeZone: "America/New_York" }).format(new Date(finalInstant));
      await expect(page.getByRole("cell", { name: formatted, exact: true })).toBeVisible();
      await page.getByRole("button", { name: labels.custom.conditions, exact: true }).click();
      await page.getByRole("dialog").getByRole("button", { name: labels.custom.addCondition, exact: true }).click();
      const condition = page.getByRole("dialog").getByRole("group");
      await condition.getByRole("combobox", { name: labels.custom.conditionField, exact: true }).click();
      await page.locator(`[role="option"][data-value="${date.key}"]`).click();
      await condition.locator('[id$="-mode"]').click();
      await page.getByRole("option", { name: labels.custom.exactInstant, exact: true }).click();
      await condition.locator('input[type="datetime-local"]').fill("2030-11-03T01:45:00.789");
      await condition.locator('[id$="-offset"]').click();
      await page.getByRole("option", { name: "-05:00", exact: true }).click();
      await page.getByRole("dialog").getByRole("button", { name: labels.apply, exact: true }).click();
      await expect.poll(() => JSON.parse(new URL(page.url()).searchParams.get("criteria") ?? "[]")).toEqual([{ key: date.key, operator: "eq", value: finalInstant }]);
      await expect(page.locator("tbody").getByRole("link", { name: prefix, exact: true })).toBeVisible();
    } finally {
      const latest = await settings();
      expect((await page.request.patch("/api/crm/settings", { headers, data: { timeZone: original.timeZone, countryCode: original.countryCode, revision: latest.revision } })).ok()).toBe(true);
    }
  });
}
