import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
import { getCrmDictionary } from "../../src/lib/i18n/crm-dictionary";
import type { FieldDefinition } from "../../src/lib/services/custom-fields/field-contracts";

for (const locale of ["vi", "en"] as const) {
  test(`${locale}: private files upload, save, reload, download and validate removal on mobile`, async ({ page, baseURL }) => {
    const labels = getCrmDictionary(locale);
    const headers = { origin: baseURL! };
    expect((await page.request.post("/api/auth/sign-in/email", { headers, data: { email: process.env.E2E_OWNER_EMAIL, password: process.env.E2E_OWNER_PASSWORD } })).ok()).toBe(true);
    const name = `files-${locale}-${crypto.randomUUID().slice(0, 8)}`;
    const created = await page.request.post("/api/crm/companies", { headers, data: { name } });
    expect(created.ok()).toBe(true);
    const company = await created.json();
    await page.goto(`/${locale}/crm/companies?q=${name}`);
    await page.getByRole("button", { name: labels.custom.manage, exact: true }).click();
    let dialog = page.getByRole("dialog");
    await dialog.getByRole("button", { name: labels.custom.add, exact: true }).click();
    await dialog.getByLabel(labels.custom.label, { exact: true }).fill(name);
    await dialog.locator("#custom-field-type").click();
    await expect(page.locator('[role="option"][data-value]')).toHaveCount(17);
    await page.locator('[role="option"][data-value="file"]').click();
    await dialog.getByLabel(labels.custom.showOnTable, { exact: true }).check();
    await dialog.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(dialog.getByRole("button", { name: labels.custom.add, exact: true })).toBeVisible();
    await page.keyboard.press("Escape");
    const definitions = await (await page.request.get("/api/crm/fields?entity=company")).json() as FieldDefinition[];
    const field = definitions.find(item => item.label === name)!;
    expect(field.type).toBe("file");
    const url = `/${locale}/crm/companies?q=${name}&recordType=company&recordId=${company.id}&tab=fields`;
    await page.goto(url);
    dialog = page.getByRole("dialog");
    const input = dialog.locator(`#custom-${field.id}`);
    const bytes = Buffer.from(`Private CRM file ${locale}\nReal bytes: \u0000\u0001\u00ff`);
    const fileName = `${name}-tài-liệu.txt`;
    await input.setInputFiles({ name: fileName, mimeType: "text/plain", buffer: bytes });
    await expect(dialog.getByText(fileName, { exact: true })).toBeVisible();
    const valuesUrl = `/api/crm/fields/values?entity=company&recordId=${company.id}`;
    expect((await (await page.request.get(valuesUrl)).json())[field.key] ?? []).toEqual([]);
    await dialog.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(dialog.getByRole("status")).toHaveText(labels.custom.saved);
    const saved = (await (await page.request.get(valuesUrl)).json())[field.key] as string[];
    expect(saved).toHaveLength(1);
    await page.reload();
    await expect(dialog.getByText(fileName, { exact: true })).toBeVisible();
    const downloadPromise = page.waitForEvent("download");
    await dialog.getByRole("link", { name: labels.custom.fileDownload, exact: true }).click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toBe(fileName);
    expect(await readFile((await download.path())!)).toEqual(bytes);
    await page.setViewportSize({ width: 375, height: 812 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath(`${locale}-file-field-mobile.png`), animations: "disabled" });
    // A rejected local selection preserves the already attached file and blocks Save.
    await input.setInputFiles({ name: "too-large.bin", mimeType: "application/octet-stream", buffer: Buffer.alloc(10 * 1024 * 1024 + 1) });
    await expect(dialog.getByRole("alert")).toContainText(labels.custom.fileLimit);
    await expect(dialog.getByText(fileName, { exact: true })).toBeVisible();
    expect(await input.evaluate(node => (node as HTMLInputElement).checkValidity())).toBe(false);
    await dialog.getByRole("button", { name: labels.custom.fileDismiss, exact: true }).click();
    expect((await page.request.patch(`/api/crm/fields/${field.id}`, { headers, data: { action: "update", data: { required: true } } })).ok()).toBe(true);
    await page.reload();
    await expect(dialog.getByText(fileName, { exact: true })).toBeVisible();
    await dialog.getByRole("button", { name: `${labels.custom.fileRemove}: ${fileName}`, exact: true }).click();
    await dialog.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(input).toBeFocused();
    expect(await input.evaluate(node => (node as HTMLInputElement).validationMessage)).toBe(labels.custom.fileRequired);
    expect((await (await page.request.get(valuesUrl)).json())[field.key]).toEqual(saved);
    expect((await page.request.patch(`/api/crm/fields/${field.id}`, { headers, data: { action: "update", data: { required: false } } })).ok()).toBe(true);
    await page.reload();
    await expect(dialog.getByText(fileName, { exact: true })).toBeVisible();
    await dialog.getByRole("button", { name: `${labels.custom.fileRemove}: ${fileName}`, exact: true }).click();
    await dialog.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(dialog.getByRole("status")).toHaveText(labels.custom.saved);
    expect((await (await page.request.get(valuesUrl)).json())[field.key]).toBeNull();
    await page.reload();
    await expect(input).toBeVisible();
    await expect(dialog.getByText(fileName, { exact: true })).toHaveCount(0);
  });
}
