import { expect, test } from "@playwright/test";
import { getCrmDictionary } from "../../src/lib/i18n/crm-dictionary";
import type { FieldDefinition } from "../../src/lib/services/custom-fields/field-contracts";

for (const locale of ["vi", "en"] as const) {
  test(`${locale}: numeric formulas recompute from saved inputs and reject invalid definitions`, async ({ page, baseURL }) => {
    const labels = getCrmDictionary(locale);
    expect((await page.request.post("/api/auth/sign-in/email", { headers: { origin: baseURL! }, data: { email: process.env.E2E_OWNER_EMAIL, password: process.env.E2E_OWNER_PASSWORD } })).ok()).toBe(true);
    const prefix = `formula-${locale}-${crypto.randomUUID().slice(0, 8)}`;
    const sourceLabel = `${prefix}-source`;
    const formulaLabel = `${prefix}-result`;
    const definitions = async () => { const response = await page.request.get("/api/crm/fields?entity=company"); expect(response.ok()).toBe(true); return await response.json() as FieldDefinition[]; };
    const companyResponse = await page.request.post("/api/crm/companies", { headers: { origin: baseURL! }, data: { name: prefix } });
    expect(companyResponse.ok()).toBe(true);
    const company = await companyResponse.json();
    await page.goto(`/${locale}/crm/companies?q=${prefix}`);
    await page.getByRole("button", { name: labels.custom.manage, exact: true }).click();
    const sheet = page.getByRole("dialog");
    await sheet.getByRole("button", { name: labels.custom.add, exact: true }).click();
    await sheet.getByLabel(labels.custom.label, { exact: true }).fill(sourceLabel);
    await sheet.locator("#custom-field-type").click();
    await page.locator('[role="option"][data-value="number"]').click();
    await sheet.getByLabel(labels.custom.showOnTable, { exact: true }).check();
    await sheet.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(sheet.getByRole("button", { name: labels.custom.add, exact: true })).toBeVisible();
    const source = (await definitions()).find(field => field.label === sourceLabel)!;
    expect(source).toBeTruthy();
    await sheet.getByRole("button", { name: labels.custom.add, exact: true }).click();
    await sheet.getByLabel(labels.custom.label, { exact: true }).fill(formulaLabel);
    await sheet.locator("#custom-field-type").click();
    await page.locator('[role="option"][data-value="formula"]').click();
    await expect(sheet.getByLabel(labels.required, { exact: true })).toBeDisabled();
    await expect(sheet.getByLabel(labels.required, { exact: true })).not.toBeChecked();
    await expect(sheet.getByText(`[${source.key}]`, { exact: true })).toBeVisible();
    await sheet.getByLabel(labels.custom.showOnTable, { exact: true }).check();
    await sheet.getByRole("textbox", { name: labels.custom.formulaExpression, exact: true }).fill("Math.max(1, 2)");
    await sheet.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(sheet.getByRole("alert")).toBeVisible();
    expect((await definitions()).some(field => field.label === formulaLabel)).toBe(false);
    const expression = `10 / [${source.key}]`;
    await sheet.getByRole("textbox", { name: labels.custom.formulaExpression, exact: true }).fill(expression);
    await sheet.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(sheet.getByRole("button", { name: labels.custom.add, exact: true })).toBeVisible();
    const formula = (await definitions()).find(field => field.label === formulaLabel)!;
    expect(formula.config?.expression).toBe(expression);
    await sheet.locator("li").filter({ hasText: formulaLabel }).getByRole("button").first().click();
    await sheet.getByRole("textbox", { name: labels.custom.formulaExpression, exact: true }).fill(`[${formula.key}] + 1`);
    await sheet.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(sheet.getByRole("alert")).toBeVisible();
    expect((await definitions()).find(field => field.id === formula.id)?.config?.expression).toBe(expression);
    await sheet.getByRole("button", { name: labels.cancel, exact: true }).last().click();
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    expect((await page.request.patch("/api/crm/fields/values", { headers: { origin: baseURL! }, data: { entity: "company", recordId: company.id, values: { [source.key]: 2 } } })).ok()).toBe(true);
    await page.goto(`/${locale}/crm/companies?q=${prefix}&recordType=company&recordId=${company.id}&tab=fields`);
    const dialog = page.getByRole("dialog");
    const result = dialog.locator(`output#custom-${formula.id}`);
    await expect(result).toHaveText("5");
    await expect(dialog.locator(`input#custom-${formula.id}`)).toHaveCount(0);
    await dialog.locator(`#custom-${source.id}`).fill("4");
    await dialog.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(dialog.getByText(labels.custom.saved, { exact: true })).toBeVisible();
    await expect(result).toHaveText("2.5");
    await page.reload();
    await expect(result).toHaveText("2.5");
    await page.setViewportSize({ width: 375, height: 812 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: test.info().outputPath(`${locale}-formula-mobile.png`), animations: "disabled" });
    await page.setViewportSize({ width: 1280, height: 800 });
    await page.keyboard.press("Escape");
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.goto(`/${locale}/crm/companies?q=${prefix}`);
    await expect(page.getByRole("cell", { name: new Intl.NumberFormat(locale).format(2.5), exact: true })).toBeVisible();
    await page.goto(`/${locale}/crm/companies?q=${prefix}&recordType=company&recordId=${company.id}&tab=fields`);
    await dialog.locator(`#custom-${source.id}`).fill("0");
    await dialog.getByRole("button", { name: labels.save, exact: true }).click();
    await expect(dialog.getByText(labels.custom.saved, { exact: true })).toBeVisible();
    await expect(result).toHaveText("—");
    const computedResponse = await page.request.get(`/api/crm/fields/values?entity=company&recordId=${company.id}`);
    expect(computedResponse.ok()).toBe(true);
    expect(await computedResponse.json()).toMatchObject({ [source.key]: 0, [formula.key]: null });
  });
}
