import {expect,test,type APIResponse} from "@playwright/test";
import {getSchedulingDictionary} from "../../src/lib/i18n/scheduling-dictionary";

test.setTimeout(120_000);
async function checked(response:Pick<APIResponse,"ok"|"text"|"json">){expect(response.ok(),await response.text()).toBe(true);return response.json();}
test.beforeEach(async({page,baseURL})=>{await checked(await page.request.post("/api/auth/sign-in/email",{headers:{origin:baseURL!},data:{email:process.env["E2E_OWNER_EMAIL"],password:process.env["E2E_OWNER_PASSWORD"]}}));});

test("Vietnamese personal tasks, conflict-aware calendar and ticket cycles",async({page,baseURL})=>{
 const copy=getSchedulingDictionary("vi"),headers={origin:baseURL!};await page.goto("/vi/crm/tasks");await expect(page.getByText(copy.noItems,{exact:true})).toBeVisible();const name=`schedule-${Date.now()}`,company=await checked(await page.request.post("/api/crm/companies",{headers,data:{name}})),task=await checked(await page.request.post("/api/crm/tasks",{headers,data:{subject:"Gọi lại khách hàng",companyId:company.id,dueAt:new Date(Date.now()+3600000).toISOString()}}));
 await page.reload();const taskRow=page.locator("li").filter({hasText:"Gọi lại khách hàng"});await expect(taskRow).toBeVisible();await taskRow.getByRole("button",{name:copy.complete,exact:true}).click();await expect(taskRow).toContainText(copy.completed);page.once("dialog",dialog=>dialog.accept("Khách vừa phản hồi"));await taskRow.getByRole("button",{name:copy.reopen,exact:true}).click();await expect(taskRow).toContainText(copy.open);
 await page.goto("/vi/crm/calendar");const start=new Date(Date.now()+86400000);start.setSeconds(0,0);const end=new Date(start.getTime()+3600000),local=(d:Date)=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);async function fill(subject:string){await page.getByLabel(copy.subject,{exact:true}).fill(subject);await page.getByLabel(copy.startsAt,{exact:true}).fill(local(start));await page.getByLabel(copy.endsAt,{exact:true}).fill(local(end));await page.getByRole("button",{name:copy.create,exact:true}).click();}await fill("Tư vấn lần đầu");await expect(page.getByText("Tư vấn lần đầu",{exact:true})).toBeVisible();await fill("Tư vấn trùng giờ");await expect(page.getByRole("alert")).toContainText(copy.conflict);await page.getByRole("button",{name:copy.allowConflict,exact:true}).click();await expect(page.getByText("Tư vấn trùng giờ",{exact:true})).toBeVisible();
 await page.goto("/vi/crm/tickets");await page.getByLabel(copy.subject,{exact:true}).fill("Cần hỗ trợ đơn hàng");await page.getByRole("button",{name:copy.create,exact:true}).click();const ticket=page.locator("li").filter({hasText:"Cần hỗ trợ đơn hàng"});await expect(ticket).toBeVisible();page.once("dialog",dialog=>dialog.accept("Đã liên hệ khách hàng"));await ticket.getByRole("button",{name:copy.respond,exact:true}).click();await expect(ticket).toContainText(copy.response);await ticket.getByRole("button",{name:copy.resolve,exact:true}).click();await expect(ticket).toContainText(copy.resolved);page.once("dialog",dialog=>dialog.accept("Khách cần hỗ trợ thêm"));await ticket.getByRole("button",{name:copy.reopen,exact:true}).click();await expect(ticket).toContainText(copy.open);await page.setViewportSize({width:375,height:812});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(task.id).toBeTruthy();
});

test("English empty work views and denied browser permission keep in-app reminders",async({page,baseURL})=>{
 const copy=getSchedulingDictionary("en"),headers={origin:baseURL!};await page.addInitScript(()=>{Object.defineProperty(Notification,"permission",{configurable:true,get:()=>"denied"});Notification.requestPermission=async()=>"denied";});await page.goto("/en/crm/tasks");const company=await checked(await page.request.post("/api/crm/companies",{headers,data:{name:`reminder-${Date.now()}`}}));await checked(await page.request.post("/api/crm/tasks",{headers,data:{subject:"Reminder remains in app",companyId:company.id,dueAt:new Date(Date.now()-60000).toISOString()}}));await page.reload();await page.getByRole("button",{name:copy.reminder,exact:true}).click();const reminder=page.getByRole("button",{name:/Reminder remains in app/});await expect(reminder).toBeVisible();await page.getByRole("button",{name:copy.enableBrowser,exact:true}).click();await expect(page.getByRole("alert")).toContainText(copy.permissionDenied);await expect(reminder).toBeVisible();
});
