import {env} from "cloudflare:workers";
import {z} from "zod";
import {createCompositionRoot,type CompositionRoot,type RuntimeEnv} from "@/lib/composition-root";
import {createRouteHandler} from "@/lib/http/route-handler";
import {appCreateSchema,automationCreateSchema,endpointCreateSchema,segmentCreateSchema,templateCreateSchema,templatePreviewSchema} from "@/lib/services/integrations/integration-contract";
const mutation=z.discriminatedUnion("action",[
 z.object({action:z.literal("create-app"),data:appCreateSchema}).strict(),z.object({action:z.literal("revoke-app"),id:z.string().uuid(),revision:z.number().int().min(0)}).strict(),
 z.object({action:z.literal("create-endpoint"),data:endpointCreateSchema}).strict(),z.object({action:z.literal("disable-endpoint"),id:z.string().uuid(),revision:z.number().int().min(0)}).strict(),z.object({action:z.literal("create-template"),data:templateCreateSchema}).strict(),z.object({action:z.literal("preview-template"),data:templatePreviewSchema}).strict(),
 z.object({action:z.literal("create-automation"),data:automationCreateSchema}).strict(),z.object({action:z.literal("set-automation-enabled"),id:z.string().uuid(),revision:z.number().int().min(0),enabled:z.boolean()}).strict(),z.object({action:z.literal("create-segment"),data:segmentCreateSchema}).strict(),z.object({action:z.literal("segment-members"),id:z.string().uuid()}).strict(),z.object({action:z.literal("use-ai")}).strict(),
]);
export const createIntegrationsGetHandler=(root:CompositionRoot)=>createRouteHandler(root,{ownerOnly:true,handle:({context})=>root.integrations.dashboard(context)});
export const createIntegrationsPostHandler=(root:CompositionRoot)=>createRouteHandler<z.infer<typeof mutation>,unknown>(root,{ownerOnly:true,unsafe:true,input:mutation,handle:({context,input})=>{switch(input.action){case"create-app":return root.integrations.createApp(context,input.data);case"revoke-app":return root.integrations.revokeApp(context,input.id,input.revision);case"create-endpoint":return root.integrations.createEndpoint(context,input.data);case"disable-endpoint":return root.integrations.disableEndpoint(context,input.id,input.revision);case"create-template":return root.integrations.createTemplate(context,input.data);case"preview-template":return root.integrations.previewTemplate(context,input.data.templateId,input.data.variables);case"create-automation":return root.integrations.createAutomation(context,input.data);case"set-automation-enabled":return root.integrations.setAutomationEnabled(context,input.id,input.revision,input.enabled);case"create-segment":return root.integrations.createSegment(context,input.data);case"segment-members":return root.integrations.segmentMembers(context,input.id);case"use-ai":return root.integrations.useAi(context);}}});
export function GET(request:Request){return createIntegrationsGetHandler(createCompositionRoot(env as RuntimeEnv))(request);}
export function POST(request:Request){return createIntegrationsPostHandler(createCompositionRoot(env as RuntimeEnv))(request);}
