import {and,asc,desc,eq,isNull,like,or,sql} from "drizzle-orm";
import type {AppDatabase} from "@/lib/db/database";
import {product,productVariant,variantFulfillment,inventoryMovement,salesOrder,user} from "@/lib/db/schema";
import type {RequestContext} from "@/lib/http/request-context";
import {HttpError} from "@/lib/http/http-errors";
import {actionGuard,requirePermission} from "../permissions/permission-policy";
import {commandDate,condition,conflict,fingerprint,salesError} from "../orders/order-operations";
import {inventoryConfigureInputSchema,inventoryRecordInputSchema,inventoryListInputSchema,inventoryResultOutputSchema,type InventoryConfigureInput,type InventoryRecordInput} from "./inventory-contract";
export class InventoryService{
 constructor(private readonly db:AppDatabase){}
 private rows(){return this.db.select({variantId:productVariant.id,productId:product.id,productName:product.name,label:productVariant.label,kind:product.kind,stockTracked:sql<number>`coalesce(${variantFulfillment.stockTracked},0)`,sessionUnits:sql<number>`coalesce(${variantFulfillment.sessionUnits},0)`,expiryDays:variantFulfillment.expiryDays,onHand:sql<number>`coalesce(${variantFulfillment.onHand},0)`,revision:sql<number>`coalesce(${variantFulfillment.revision},0)`}).from(productVariant).innerJoin(product,eq(product.id,productVariant.productId)).leftJoin(variantFulfillment,eq(variantFulfillment.variantId,productVariant.id));}
 async list(context:RequestContext,raw:{q?:string;pageSize?:number}={}){await requirePermission(this.db,context);const input=inventoryListInputSchema.parse(raw);const rows=await this.rows().where(and(isNull(product.archivedAt),isNull(productVariant.archivedAt),input.q?or(like(product.name,`%${input.q}%`),like(productVariant.label,`%${input.q}%`)):undefined)).orderBy(asc(product.name),asc(productVariant.id)).limit(input.pageSize);return{rows:rows.map(r=>({...r,stockTracked:Boolean(r.stockTracked)}))};}
 async byId(context:RequestContext,id:string){await requirePermission(this.db,context);const r=await this.rows().where(eq(productVariant.id,id)).get();if(!r)throw new HttpError(404,"not_found","Variant not found");return{...r,stockTracked:Boolean(r.stockTracked)};}
 async configure(context:RequestContext,id:string,raw:InventoryConfigureInput){const input=inventoryConfigureInputSchema.parse(raw);await requirePermission(this.db,context,["inventory.configure"]);const current=await this.byId(context,id);if(current.revision!==input.expectedRevision)conflict();if(input.stockTracked&&current.kind!=="product"||input.sessionUnits>0&&current.kind!=="service")throw new HttpError(400,"validation_failed","Stock applies to goods and sessions apply to services");const auth=actionGuard(this.db,context,["inventory.configure"]),guard=condition(this.db,sql`coalesce((select revision from variant_fulfillment where variant_id=${id}),0)=${input.expectedRevision}`);try{await this.db.batch([auth.begin,guard.begin,this.db.insert(variantFulfillment).values({variantId:id,stockTracked:input.stockTracked,sessionUnits:input.sessionUnits,expiryDays:input.expiryDays,revision:input.expectedRevision+1}).onConflictDoUpdate({target:variantFulfillment.variantId,set:{stockTracked:input.stockTracked,sessionUnits:input.sessionUnits,expiryDays:input.expiryDays,revision:input.expectedRevision+1}}),guard.end,auth.end]);return{variantId:id,revision:input.expectedRevision+1,onHand:current.onHand};}catch(e){salesError(e);}}
 async record(context:RequestContext,id:string,raw:InventoryRecordInput){const input=inventoryRecordInputSchema.parse(raw),digest=await fingerprint(id,input);await requirePermission(this.db,context);const prior=await this.db.select().from(inventoryMovement).where(eq(inventoryMovement.operationKey,input.operationKey)).get();if(prior){if(prior.variantId!==id||prior.fingerprint!==digest)conflict();return inventoryResultOutputSchema.parse(JSON.parse(prior.resultJson));}
  const permission=input.kind==="return"?"inventory.return" as const:"inventory.adjust" as const;await requirePermission(this.db,context,[permission]);const row=await this.byId(context,id);if(row.revision!==input.expectedRevision)conflict();if(input.kind!=="adjustment"&&input.quantity<0||!row.stockTracked&&input.kind!=="return")throw new HttpError(400,"validation_failed","Invalid stock movement");
  let returnGuard=sql`1=1`;if(input.kind==="return"){if(!input.orderId)throw new HttpError(400,"validation_failed","Return needs its sale order");returnGuard=sql`coalesce((select -sum(quantity) from inventory_movement where variant_id=${id} and order_id=${input.orderId} and kind in('sale','return')),0)>=${input.quantity}`;}else if(input.orderId)throw new HttpError(400,"validation_failed","Only returns reference sale orders");
  const onHand=row.onHand+input.quantity;if(onHand<0||onHand>1_000_000_000_000)conflict("Stock cannot become negative or exceed supported bounds");const date=await commandDate(this.db,context,input),auth=actionGuard(this.db,context,[permission,...date.permissions]),guard=condition(this.db,and(date.predicate,returnGuard,sql`exists(select 1 from variant_fulfillment where variant_id=${id} and revision=${input.expectedRevision})`)!);
  try{await this.db.batch([auth.begin,guard.begin,this.db.update(variantFulfillment).set({onHand,revision:input.expectedRevision+1}).where(eq(variantFulfillment.variantId,id)),this.db.insert(inventoryMovement).values({id:crypto.randomUUID(),variantId:id,orderId:input.orderId??null,kind:input.kind,quantity:input.quantity,operationKey:input.operationKey,fingerprint:digest,resultJson:JSON.stringify({variantId:id,operationKey:input.operationKey,revision:input.expectedRevision+1,onHand}),actorId:context.userId,reason:input.reason,businessDate:date.date,timeZone:date.timeZone,createdAt:date.now}),guard.end,auth.end]);return{variantId:id,operationKey:input.operationKey,revision:input.expectedRevision+1,onHand};}catch(e){const p=await this.db.select().from(inventoryMovement).where(eq(inventoryMovement.operationKey,input.operationKey)).get();if(p?.fingerprint===digest&&p.variantId===id){return inventoryResultOutputSchema.parse(JSON.parse(p.resultJson));}salesError(e);}
 }
 async history(context:RequestContext,id:string){await requirePermission(this.db,context);const rows=await this.db.select({movement:inventoryMovement,actorName:user.name}).from(inventoryMovement).leftJoin(user,eq(user.id,inventoryMovement.actorId)).where(eq(inventoryMovement.variantId,id)).orderBy(desc(inventoryMovement.createdAt),desc(inventoryMovement.id)).limit(100);return{rows:rows.map(({movement:{fingerprint:_f,resultJson:_r,...r},actorName})=>({...r,actorName,createdAt:r.createdAt.toISOString()}))};}
}
