import {z} from "zod";
export const appGrantSchema=z.enum(["events.write","contacts.read","leads.read","leads.create","tickets.create"]);
export const appCreateSchema=z.object({name:z.string().trim().min(1).max(120),grants:z.array(appGrantSchema).min(1).max(5)}).strict();
export const inboundEventSchema=z.object({externalId:z.string().trim().min(1).max(255),subjectId:z.string().trim().min(1).max(255),type:z.string().trim().regex(/^[a-z][a-z0-9_.-]*$/).max(120),occurredAt:z.string().datetime(),payload:z.record(z.string(),z.unknown())}).strict();
export const endpointCreateSchema=z.object({name:z.string().trim().min(1).max(120),url:z.string().url().refine(value=>new URL(value).protocol==="https:"),events:z.array(z.string().trim().min(1).max(120)).min(1).max(50)}).strict();
export const templateCreateSchema=z.object({name:z.string().trim().min(1).max(120),subject:z.string().trim().min(1).max(300),body:z.string().min(1).max(50_000),requiredVariables:z.array(z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]*$/)).max(50)}).strict();
export const templatePreviewSchema=z.object({templateId:z.string().uuid(),variables:z.record(z.string(),z.string().max(10_000))}).strict();
export const automationActionSchema=z.discriminatedUnion("type",[
 z.object({type:z.literal("set-lead-owner"),leadIdField:z.string().max(80),membershipId:z.string().min(1).max(255)}).strict(),
 z.object({type:z.literal("create-task"),leadIdField:z.string().max(80),membershipId:z.string().min(1).max(255),subject:z.string().trim().min(1).max(300),dueOffsetMinutes:z.number().int().min(0).max(525600)}).strict(),
 z.object({type:z.literal("update-lead-field"),leadIdField:z.string().max(80),field:z.enum(["title","description","status_id","source_id"]),value:z.string().max(10_000)}).strict(),
 z.object({type:z.literal("notify-internal"),subjectIdField:z.string().max(80),membershipId:z.string().min(1).max(255),title:z.string().trim().min(1).max(300),body:z.string().max(10_000).nullable().optional()}).strict(),
 z.object({type:z.literal("emit-webhook"),subjectIdField:z.string().max(80),eventType:z.string().trim().regex(/^[a-z][a-z0-9_.-]*$/).max(120)}).strict(),
 z.object({type:z.literal("send-email"),templateId:z.string().uuid(),recipientField:z.string().max(80)}).strict(),
]);
export const automationCreateSchema=z.object({name:z.string().trim().min(1).max(120),eventType:z.string().trim().min(1).max(120),condition:z.object({field:z.string().max(80),equals:z.union([z.string(),z.number(),z.boolean(),z.null()])}).strict(),action:automationActionSchema,enabled:z.boolean(),maxDepth:z.number().int().min(1).max(5).default(3)}).strict();
export const segmentCreateSchema=z.object({name:z.string().trim().min(1).max(120),entity:z.enum(["lead","contact","company","deal"]),kind:z.enum(["static","dynamic"]),filter:z.object({field:z.enum(["status","source","owner","country","stage"]),equals:z.string().max(255)}).strict().optional(),memberIds:z.array(z.string().min(1).max(255)).max(10_000).default([])}).strict();
export const appLeadCreateSchema=z.object({operationKey:z.string().trim().min(1).max(255),firstName:z.string().trim().min(1).max(200),lastName:z.string().trim().max(200).nullable().optional(),email:z.string().email().max(320).nullable().optional(),phone:z.string().trim().max(80).nullable().optional(),sourceId:z.string().trim().min(1).max(80).default("manual")}).strict();
export const appTicketCreateSchema=z.object({operationKey:z.string().trim().min(1).max(255),subject:z.string().trim().min(1).max(300),description:z.string().trim().max(10_000).nullable().optional(),source:z.string().trim().min(1).max(120).default("api")}).strict();
export type AppCreate=z.infer<typeof appCreateSchema>;export type InboundEvent=z.infer<typeof inboundEventSchema>;export type EndpointCreate=z.infer<typeof endpointCreateSchema>;export type TemplateCreate=z.infer<typeof templateCreateSchema>;export type AutomationAction=z.infer<typeof automationActionSchema>;export type AutomationCreate=z.infer<typeof automationCreateSchema>;export type SegmentCreate=z.infer<typeof segmentCreateSchema>;export type AppLeadCreate=z.infer<typeof appLeadCreateSchema>;export type AppTicketCreate=z.infer<typeof appTicketCreateSchema>;
