import {and,desc,eq,isNotNull,isNull,sql} from "drizzle-orm";
import {alias} from "drizzle-orm/sqlite-core";
import type {AppDatabase} from "@/lib/db/database";
import {activity,taskCycle,taskDeadlineHistory,taskOperation,taskRecord,user} from "@/lib/db/schema";
import type {RequestContext} from "@/lib/http/request-context";
import {HttpError} from "@/lib/http/http-errors";
import {requirePermission,actionGuard,permissionError} from "../permissions/permission-policy";
import {condition} from "../orders/order-operations";
import {ActivityService} from "../activities/activity-service";
import type {TaskCommandInput,TaskCreateInput,TaskListInput} from "./task-contract";

const iso=(value:Date|null)=>value?.toISOString()??null;
export class TaskService{
 constructor(private readonly db:AppDatabase,private readonly activities=new ActivityService(db)){}
 async create(context:RequestContext,input:TaskCreateInput){return this.activities.create(context,{...input,type:"task"});}
 async list(context:RequestContext,input:TaskListInput){await requirePermission(this.db,context);const assignee=alias(user,"task_assignee");const clauses=[];if(input.scope==="mine")clauses.push(eq(taskRecord.assigneeMembershipId,context.userId));if(input.state==="open")clauses.push(isNull(taskRecord.completedAt));if(input.state==="completed")clauses.push(isNotNull(taskRecord.completedAt));const rows=await this.db.select({task:taskRecord,item:activity,assigneeName:assignee.name}).from(taskRecord).innerJoin(activity,eq(activity.id,taskRecord.activityId)).leftJoin(assignee,eq(assignee.id,taskRecord.assigneeMembershipId)).where(clauses.length?and(...clauses):undefined).orderBy(sql`${taskRecord.completedAt} is not null`,taskRecord.dueAt,desc(taskRecord.updatedAt)).limit(input.limit);return{rows:rows.map(({task,item,assigneeName})=>this.serialize(task,item,assigneeName))};}
 async byId(context:RequestContext,id:string){await requirePermission(this.db,context);const assignee=alias(user,"task_assignee");const row=await this.db.select({task:taskRecord,item:activity,assigneeName:assignee.name}).from(taskRecord).innerJoin(activity,eq(activity.id,taskRecord.activityId)).leftJoin(assignee,eq(assignee.id,taskRecord.assigneeMembershipId)).where(eq(taskRecord.activityId,id)).get();if(!row)throw new HttpError(404,"not_found","Task was not found");const cycles=await this.db.select().from(taskCycle).where(eq(taskCycle.taskId,id)).orderBy(desc(taskCycle.cycle));const deadlines=await this.db.select().from(taskDeadlineHistory).where(eq(taskDeadlineHistory.taskId,id)).orderBy(desc(taskDeadlineHistory.createdAt));return{...this.serialize(row.task,row.item,row.assigneeName),cycles:cycles.map(c=>({...c,openedAt:c.openedAt.toISOString(),dueAt:iso(c.dueAt),completedAt:iso(c.completedAt)})),deadlines:deadlines.map(d=>({...d,previousDueAt:iso(d.previousDueAt),nextDueAt:iso(d.nextDueAt),createdAt:d.createdAt.toISOString()}))};}
 async command(context:RequestContext,id:string,input:TaskCommandInput){if(input.action==="complete"||input.action==="reopen"){await this.activities.complete(context,id,input.action==="complete",input.action==="reopen"?input.reason:undefined,input.operationKey,input.expectedRevision);return this.byId(context,id);}const current=await this.db.select().from(taskRecord).where(eq(taskRecord.activityId,id)).get();if(!current)throw new HttpError(404,"not_found","Task was not found");const fingerprint=JSON.stringify(input),previous=await this.db.select().from(taskOperation).where(eq(taskOperation.id,input.operationKey)).get();if(previous){if(previous.taskId!==id||previous.fingerprint!==fingerprint)throw new HttpError(409,"conflict","Operation key was already used");return this.byId(context,id);}if(current.revision!==input.expectedRevision)throw new HttpError(409,"conflict","Task changed before the update");if(current.completedAt)throw new HttpError(409,"conflict","Completed task history cannot be rewritten");const now=new Date(),overdue=Boolean(current.dueAt&&current.dueAt<now),result={id,revision:current.revision+1,cycle:current.currentCycle,dueAt:input.action==="deadline"?input.dueAt:iso(current.dueAt),assigneeMembershipId:input.action==="assign"?input.assigneeMembershipId:current.assigneeMembershipId,overdueBreached:current.overdueBreached||overdue};const auth=actionGuard(this.db,context,[input.action==="deadline"?"task.update":"task.assign"]),guard=condition(this.db,sql`exists(select 1 from task_record where activity_id=${id} and revision=${current.revision} and completed_at is null)`);
  try{await this.db.batch([auth.begin,guard.begin,this.db.update(taskRecord).set(input.action==="deadline"?{dueAt:input.dueAt?new Date(input.dueAt):null,overdueBreached:result.overdueBreached,revision:result.revision,updatedAt:now}:{assigneeMembershipId:input.assigneeMembershipId,revision:result.revision,updatedAt:now}).where(eq(taskRecord.activityId,id)),...(input.action==="deadline"?[this.db.update(taskCycle).set({dueAt:input.dueAt?new Date(input.dueAt):null,overdueBreached:result.overdueBreached}).where(and(eq(taskCycle.taskId,id),eq(taskCycle.cycle,current.currentCycle))),this.db.insert(taskDeadlineHistory).values({id:crypto.randomUUID(),taskId:id,cycle:current.currentCycle,previousDueAt:current.dueAt,nextDueAt:input.dueAt?new Date(input.dueAt):null,reason:input.reason,actorId:context.userId,operationKey:input.operationKey,createdAt:now})]:[]),this.db.insert(taskOperation).values({id:input.operationKey,taskId:id,action:input.action,fingerprint,resultJson:JSON.stringify(result),actorId:context.userId,createdAt:now}),guard.end,auth.end]);return this.byId(context,id);}catch(error){this.error(error);}
 }
 private serialize(task:typeof taskRecord.$inferSelect,item:typeof activity.$inferSelect,assigneeName:string|null){return{id:task.activityId,subject:item.subject??"",content:item.content,assigneeMembershipId:task.assigneeMembershipId,assigneeName,dueAt:iso(task.dueAt),completedAt:iso(task.completedAt),overdue:Boolean(!task.completedAt&&task.dueAt&&task.dueAt<new Date()),overdueBreached:task.overdueBreached,revision:task.revision,cycle:task.currentCycle,companyId:item.companyId,contactId:item.contactId,dealId:item.dealId,leadId:item.leadId,productId:item.productId,orderId:item.orderId,createdAt:task.createdAt.toISOString(),updatedAt:task.updatedAt.toISOString()};}
 private error(error:unknown):never{try{permissionError(error);}catch(original){let current:unknown=original;while(current&&typeof current==="object"){if(current instanceof Error&&/operation_condition|task_|UNIQUE|FOREIGN KEY/.test(current.message))throw new HttpError(409,"conflict","Task changed before the operation completed");current="cause" in current?current.cause:null;}throw original;}}
}
