"use client";
import { useRecordLayout, visibleLayoutFields } from "../layouts/use-record-layout";
import type { AppLocale } from "@/lib/i18n/config";
import type { CrmDictionary } from "@/lib/i18n/crm-dictionary";
import type { EntityType } from "@/lib/listing/list-state";
import { displayValue, fieldLabel, recordName, type CrmRecord } from "../record-types";
import { RecordLink } from "./record-link";
import { InlineRecordSelect } from "./inline-record-select";
import { InlineRecordField } from "./inline-record-field";

const readOnlyFields = new Set(["stage", "amount", "currency", "expectedCloseAt", "owner", "createdAt", "updatedAt", "sourceId", "statusId", "collaboratorMembershipIds", "kind", "categoryId"]);
export function RecordDetails({ entity, record, locale, labels, readOnly }: { entity: EntityType; readOnly?: boolean; record: CrmRecord; locale: AppLocale; labels: CrmDictionary }) {
  const { layout, error, reload } = useRecordLayout(entity);
  if (!layout) return <p role={error ? "alert" : "status"} className="p-5">{error ? labels.error : labels.loading}{error && <button onClick={reload}>{labels.retry}</button>}</p>;
  const visible = visibleLayoutFields(layout, "detail").filter(entry => entry.kind === "builtin");
  const shown = (key: string) => visible.some(field => field.key === key);
  const aliases: Record<string, string> = { ownerMembershipId: "owner", stageId: "stage", amountMinor: "amount" };
  return <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:gap-8">
    <div className="min-w-0 flex-1">
      {(entity === "company" || entity === "deal" || entity === "lead" || entity === "product") && !layout.configured && shown("description") && <section className="space-y-2 border-b px-5 py-3"><h3 className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{fieldLabel("description", labels)}</h3><InlineRecordField readOnly={readOnly} entity={entity} recordId={record.id} expectedRevision={typeof record.revision === "number" ? record.revision : undefined} field="description" value={typeof record.description === "string" ? record.description : ""} label={fieldLabel("description", labels)} labels={labels} /></section>}
      {record.company && !layout.configured && shown("companyId") && <section className="space-y-2 border-b px-5 py-3"><h3 className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{labels.company}</h3><RecordLink entity="company" id={record.company.id}>{record.company.name}</RecordLink>{record.company.domain && <p className="text-xs text-muted-foreground">{record.company.domain}</p>}</section>}
      {(["contacts", "deals"] as const).map(key => record[key] && <section key={key} className="border-b last:border-0"><h3 className="flex items-center gap-2 px-5 py-3 text-xs font-medium uppercase tracking-wider text-muted-foreground">{labels[key === "contacts" ? "contact" : "deal"]}<span className="tabular-nums">{record[key]?.length}</span></h3>{record[key]?.length ? <ul className="divide-y border-t">{record[key]?.map(related => <li className="flex min-w-0 items-center gap-3 px-5 py-2.5 text-xs hover:bg-muted/40" key={related.id}><div className="flex size-6 shrink-0 items-center justify-center rounded-sm border bg-muted/40 text-xs font-medium" aria-hidden="true">{recordName(related).slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><RecordLink entity={key === "contacts" ? "contact" : "deal"} id={related.id}>{recordName(related)}</RecordLink>{key === "contacts" && <p className="truncate text-muted-foreground">{[related.title, related.email].filter(Boolean).join(" · ")}</p>}</div>{key === "deals" && <div className="shrink-0 text-right"><p>{displayValue(related, "stage", locale, labels)}</p><p className="text-muted-foreground tabular-nums">{displayValue(related, "amount", locale, labels)}</p></div>}{related.archivedAt && <span className="text-muted-foreground">{labels.archived}</span>}</li>)}</ul> : <p className="px-5 pb-5 text-xs text-muted-foreground">{labels.none}</p>}</section>)}
    </div>
    <section className="min-w-0 w-full shrink-0 space-y-2 px-5 py-3 lg:w-80"><h3 className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{labels.details}</h3><dl>{visible.filter(field => layout.configured || !["description", "companyId"].includes(field.key)).map(field => aliases[field.key] ?? field.key).map(key => <div key={key} className="grid grid-cols-[6.5rem_minmax(0,1fr)] items-center gap-2"><dt className="truncate text-xs text-muted-foreground" title={fieldLabel(key, labels)}>{fieldLabel(key, labels)}</dt><dd className="min-w-0">{key === "companyId" ? record.company ? <RecordLink entity="company" id={record.company.id}>{record.company.name}</RecordLink> : <span>—</span> : key === "owner" || key === "stage" ? <InlineRecordSelect readOnly={readOnly} entity={entity} record={record} field={key} shown={displayValue(record, key, locale, labels)} labels={labels} /> : readOnlyFields.has(key) ? <div className="break-words border border-transparent px-2 py-1 text-xs leading-5">{displayValue(record, key, locale, labels)}</div> : <InlineRecordField readOnly={readOnly} entity={entity} recordId={record.id} expectedRevision={typeof record.revision === "number" ? record.revision : undefined} field={key} value={typeof record[key] === "string" ? record[key] as string : ""} label={fieldLabel(key, labels)} labels={labels} />}</dd></div>)}</dl></section>
  </div>;
}
