import {applyD1Migrations,env} from "cloudflare:test";
import {it,expect} from "vitest";
it("preserves populated catalog, conversions and private files while extending order anchors",async()=>{
 const db=env.UPGRADE_DB,index=env.TEST_MIGRATIONS.findIndex(m=>m.name==="0018_order_ledger.sql");expect(index).toBe(17);await applyD1Migrations(db,env.TEST_MIGRATIONS.slice(0,index));
 await db.batch([
 db.prepare("INSERT INTO user(id,name,email,email_verified,created_at,updated_at) VALUES('owner','Owner','order-upgrade@example.invalid',1,1,2)"),db.prepare("INSERT INTO singleton_membership(user_id,role,status,created_at,updated_at) VALUES('owner','owner','active',1,2)"),
 db.prepare("INSERT INTO company(id,name,created_at,updated_at) VALUES('company','Retained',1,2)"),db.prepare("INSERT INTO contact(id,first_name,company_id,created_at,updated_at) VALUES('contact','Retained contact','company',1,2)"),db.prepare("INSERT INTO deal(id,name,company_id,owner_membership_id,stage_id,stage_changed_at,amount_minor,currency,created_at,updated_at) VALUES('deal','Retained deal','company','owner','demo-booked',1,12500,'USD',1,2)"),
 db.prepare("INSERT INTO lead(id,first_name,creator_user_id,created_at,updated_at) VALUES('lead','Retained lead','owner',1,2)"),db.prepare("UPDATE lead SET status_id='converted',converted_contact_id='contact',converted_at=3 WHERE id='lead'"),db.prepare("INSERT INTO lead_conversion(id,lead_id,operation_key,fingerprint,actor_id,contact_id,mode,lead_revision,mapping_revision,snapshot_json,result_json,completed_at) VALUES('conversion','lead','conversion-key','hash','owner','contact','link',0,0,'{}','{}',3)"),
 db.prepare("INSERT INTO product(id,kind,name,creator_user_id,created_at,updated_at) VALUES('product','product','Retained product','owner',1,2)"),db.prepare("INSERT INTO product_variant(id,product_id,is_default,sku,label,price_minor,currency,created_at,updated_at) VALUES('variant','product',1,'OLD-SKU','Retained',123,'USD',1,2)"),db.prepare("INSERT INTO crm_file(id,entity,record_id,field_id,uploader_id,object_key,file_name,size,status,created_at) VALUES('file','product','product','7dd843dc-6df2-4c33-a8f8-8f45cc0e5762','owner','private-object','real.bin',2,'pending',1)"),db.prepare("UPDATE crm_file SET status='ready',ready_at=2 WHERE id='file'"),db.prepare("INSERT INTO custom_field_value(id,field_id,product_id,json_value,updated_at) VALUES('value','7dd843dc-6df2-4c33-a8f8-8f45cc0e5762','product','[\"file\"]',2)"),db.prepare("INSERT INTO activity(id,type,product_id,author_user_id,content,created_at,updated_at) VALUES('activity','note','product','owner','Retain history',1,2)"),db.prepare("INSERT INTO record_draft(id,entity,user_id,expires_at,created_at) VALUES('draft','product','owner',9,1)"),db.prepare("UPDATE record_layout SET revision=4,fields_json='[]' WHERE entity='product'")]);
 const tables=(await db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' AND name!='d1_migrations' ORDER BY name").all<{name:string}>()).results.map(r=>r.name);const before=new Map(await Promise.all(tables.map(async t=>[t,(await db.prepare(`SELECT * FROM ${t} ORDER BY 1,2`).all()).results] as const)));const objects=(await db.prepare("SELECT name,type FROM sqlite_schema WHERE type IN('trigger','index') AND name NOT LIKE 'sqlite_%'").all()).results;
 await applyD1Migrations(db,[env.TEST_MIGRATIONS[index]!]);for(const t of tables){let rows=(await db.prepare(`SELECT * FROM ${t} ORDER BY 1,2`).all()).results;if(['record_layout','module_setting','field_configuration_revision'].includes(t))rows=rows.filter(r=>r.entity!=='order');if(t==='access_grant')rows=rows.filter(r=>!String(r.permission).startsWith('order.'));expect(rows,t).toEqual(before.get(t)!.map(r=>['activity','custom_field_value'].includes(t)?{...r,order_id:null}:r));}
 expect((await db.prepare("SELECT name,type FROM sqlite_schema WHERE type IN('trigger','index') AND name NOT LIKE 'sqlite_%'").all()).results).toEqual(expect.arrayContaining(objects));expect((await db.prepare('PRAGMA foreign_key_check').all()).results).toEqual([]);await expect(db.prepare("UPDATE crm_file SET object_key='changed' WHERE id='file'").run()).rejects.toThrow('file_metadata_immutable');await expect(db.prepare("UPDATE lead_conversion SET fingerprint='changed'").run()).rejects.toThrow('lead_conversion_immutable');await db.prepare("UPDATE lead_mapping SET auto_order=1 WHERE id='contact'").run();
});
