import { env } from "cloudflare:workers";
import { describe, expect, it } from "vitest";
import { handleAuthRequest } from "@/lib/auth/auth";
import type { AuthEmailAdapter, AuthEmailMessage } from "@/lib/email/email-adapter";
import { createCompositionRoot, type RuntimeEnv } from "@/lib/composition-root";
class RecordingEmailAdapter implements AuthEmailAdapter {
  verificationMessages: AuthEmailMessage[] = [];
  async sendVerification(message: AuthEmailMessage) { this.verificationMessages.push(message); }
  async sendPasswordReset() { }
}
const bindings = env as RuntimeEnv;
let requestIndex = 50;
const root = () => createCompositionRoot(bindings, new RecordingEmailAdapter());
async function successful(response: Response) {
  const body = await response.json() as any;
  expect(response.status, JSON.stringify(body)).toBe(200);
  return body;
}
async function session(email: string) {
  const adapter = new RecordingEmailAdapter();
  const composition = createCompositionRoot(bindings, adapter);
  const headers = { origin: "https://auth.test", "content-type": "application/json", "cf-connecting-ip": `192.0.2.${++requestIndex}` };
  const auth = (path: string, body: unknown) => handleAuthRequest(new Request(`https://auth.test/api/auth/${path}`, { method: "POST", headers, body: JSON.stringify(body) }), composition.auth, composition.db, bindings.AUTH_BASE_URL);
  const password = "correct horse battery staple";
  await successful(await auth("sign-up/email", { name: email, email, password }));
  const token = new URL(adapter.verificationMessages.at(-1)?.url ?? "").searchParams.get("token");
  if (!token) throw new Error("Expected verification token");
  await composition.auth.api.verifyEmail({ asResponse: true, headers: new Headers({ origin: "https://auth.test" }), query: { token } });
  const signedIn = await auth("sign-in/email", { email, password });
  expect(signedIn.status).toBe(200);
  const cookie = signedIn.headers.get("set-cookie")?.split(";", 1)[0];
  const user = await composition.db.query.user.findFirst({ where: (fields, { eq }) => eq(fields.email, email) });
  if (!cookie || !user) throw new Error("Expected verified session");
  return { cookie, id: user.id };
}
import { requireRequestContext } from "@/lib/http/request-context";
import type { AppDatabase } from "@/lib/db/database";
import { ProductService } from "@/lib/services/catalog/product-service";
import { ProductCategoryService } from "@/lib/services/catalog/product-category-service";
import { productVariantUpdateInputSchema,productCreateInputSchema,productDetailOutputSchema,productListInputSchema,productListOutputSchema } from "@/lib/services/catalog/product-contract";
import { fieldCreateInputSchema } from "@/lib/services/custom-fields/field-contracts";
const input=(name:string,sku?:string,kind="product")=>productCreateInputSchema.parse({name,kind,initialVariant:{label:"Default",priceMinor:12500,sku}});
async function setupCatalog(){const actor=await session(`catalog-${crypto.randomUUID()}@example.com`);await env.DB.prepare("UPDATE singleton_membership SET role='owner' WHERE user_id=?").bind(actor.id).run();const services=root(),context=await requireRequestContext(new Headers({cookie:actor.cookie}),services);return {actor,services,context,products:new ProductService(services.db),categories:new ProductCategoryService(services.db)};}
function intercept(db:AppDatabase,before:()=>Promise<unknown>):AppDatabase{return new Proxy(db,{get(target,key){if(key==="batch")return async(statements:Parameters<AppDatabase["batch"]>[0])=>{await before();return target.batch(statements);};const value=Reflect.get(target,key);return typeof value==="function"?value.bind(target):value;}});}
import {OrderService} from "@/lib/services/orders/order-service";
import {OrderCommandService} from "@/lib/services/orders/order-command-service";
import {PaymentService} from "@/lib/services/payments/payment-service";
import {InventoryService} from "@/lib/services/inventory/inventory-service";
import {EntitlementService} from "@/lib/services/entitlements/entitlement-service";
import {orderCreateInputSchema,orderListInputSchema,orderDetailOutputSchema} from "@/lib/services/orders/order-contract";
async function setup(){const s=await setupCatalog();const contact=await s.services.contacts.create(s.context,{firstName:"Buyer"});const product=await s.products.create(s.context,input("Sold item",crypto.randomUUID()));const detail=await s.products.byId(s.context,product!.id);const calendar=await s.services.db.get<{revision:number}>(await import("drizzle-orm").then(({sql})=>sql`select calendar_revision revision from crm_setting where id='settings'`));return{...s,contact,variant:detail.variants[0],product:detail,calendarRevision:calendar!.revision,orders:new OrderService(s.services.db),commands:new OrderCommandService(s.services.db),payments:new PaymentService(s.services.db),inventory:new InventoryService(s.services.db),entitlements:new EntitlementService(s.services.db)};}
function draft(s:Awaited<ReturnType<typeof setup>>,quantity=1){return orderCreateInputSchema.parse({name:"Order",contactId:s.contact.id,lines:[{variantId:s.variant.id,expectedVariantRevision:s.variant.revision,expectedProductRevision:s.product.revision,quantity}],currency:"USD"});}
function command(s:Awaited<ReturnType<typeof setup>>,expectedRevision:number){return{operationKey:crypto.randomUUID(),expectedRevision,calendarRevision:s.calendarRevision};}
describe.sequential("order money and fulfillment",()=>{
 it("freezes confirmed snapshots and completes independently from collections",async()=>{const s=await setup();const made=await s.orders.create(s.context,draft(s));await s.orders.update(s.context,made!.id,{expectedRevision:0,name:"Edited"});await s.commands.execute(s.context,made!.id,{...command(s,1),action:"confirm"});await s.products.updateVariant(s.context,s.product.id,s.variant.id,{expectedRevision:0,priceMinor:25000});await s.commands.execute(s.context,made!.id,{...command(s,2),action:"complete"});const paid=await s.payments.record(s.context,made!.id,{...command(s,3),kind:"collection",amountMinor:4000,method:"cash"});expect(paid!.balanceMinor).toBe("8500");const row=orderDetailOutputSchema.parse(await s.orders.byId(s.context,made!.id));expect(row).toMatchObject({state:"completed",collectedMinor:4000,originalMinor:12500});expect(row.lines[0].unitPriceMinor).toBe(12500);await expect(s.orders.update(s.context,made!.id,{expectedRevision:4,name:"Rewrite"})).rejects.toMatchObject({status:409});await expect(env.DB.prepare("UPDATE sales_order SET lines_json='[]' WHERE id=?").bind(made!.id).run()).rejects.toThrow("sales_snapshot_frozen");});
 it("retains overpayment, cancellation components and refund history with exact retry results",async()=>{const s=await setup();const made=await s.orders.create(s.context,{...draft(s),surchargeMinor:200,taxMinor:300});await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});const req={...command(s,1),kind:"collection" as const,amountMinor:15000,method:"cash"};const collected=await s.payments.record(s.context,made!.id,req);expect(collected!.balanceMinor).toBe("-2000");await s.commands.execute(s.context,made!.id,{...command(s,2),action:"cancel",reason:"Cancelled by customer"});expect((await s.orders.byId(s.context,made!.id)).balanceMinor).toBe("-15000");const returned=await s.payments.record(s.context,made!.id,{...command(s,3),kind:"refund",amountMinor:15000,method:"cash"});expect(returned!.balanceMinor).toBe("0");expect(await s.payments.record(s.context,made!.id,req)).toEqual(collected);await expect(s.payments.record(s.context,made!.id,{...req,amountMinor:1})).rejects.toMatchObject({status:409});await expect(s.payments.record(s.context,made!.id,{...command(s,4),kind:"refund",amountMinor:1,method:"cash"})).rejects.toMatchObject({status:409});const history=await s.commands.history(s.context,made!.id);expect(history.rows.find(r=>r.action==="cancel")?.adjustment).toEqual({goodsMinor:12500,surchargeMinor:200,taxMinor:300});});
 it("keeps order projections equal to immutable payment and adjustment ledgers",async()=>{const s=await setup();const made=await s.orders.create(s.context,draft(s));await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});await s.payments.record(s.context,made!.id,{...command(s,1),kind:"collection",amountMinor:4000,method:"cash"});await s.commands.execute(s.context,made!.id,{...command(s,2),action:"adjust",goodsMinor:500,surchargeMinor:0,taxMinor:0,reason:"Approved reduction"});await expect(env.DB.prepare("UPDATE sales_order SET collected_minor=1 WHERE id=?").bind(made!.id).run()).rejects.toThrow("sales_projection_mismatch");await expect(env.DB.prepare("UPDATE sales_order SET goods_remaining_minor=1 WHERE id=?").bind(made!.id).run()).rejects.toThrow("sales_projection_mismatch");const totals=await env.DB.prepare("SELECT collected_minor,refunded_minor,goods_remaining_minor,(SELECT COALESCE(SUM(amount_minor),0) FROM order_payment WHERE order_id=sales_order.id AND kind='collection') ledger_collected,sales_order.goods_minor-sales_order.discount_minor-(SELECT COALESCE(SUM(a.goods_minor),0) FROM order_adjustment a WHERE a.order_id=sales_order.id) ledger_remaining FROM sales_order WHERE id=?").bind(made!.id).first();expect(totals).toMatchObject({collected_minor:4000,refunded_minor:0,goods_remaining_minor:12000,ledger_collected:4000,ledger_remaining:12000});});
 it("honors the dedicated cancellation permission without granting financial adjustment",async()=>{const s=await setup();const made=await s.orders.create(s.context,draft(s));await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});await env.DB.prepare("UPDATE singleton_membership SET role='member' WHERE user_id=?").bind(s.actor.id).run();const cancelled=await s.commands.execute(s.context,made!.id,{...command(s,1),action:"cancel",reason:"Customer cancelled"});expect(cancelled).toMatchObject({state:"cancelled",balanceMinor:"0"});});
 it("serializes concurrent collections and refunds without partial ledger entries",async()=>{const s=await setup();const made=await s.orders.create(s.context,draft(s));await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});const results=await Promise.allSettled([s.payments.record(s.context,made!.id,{...command(s,1),kind:"collection",amountMinor:7000,method:"cash"}),s.payments.record(s.context,made!.id,{...command(s,1),kind:"collection",amountMinor:7000,method:"cash"})]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((await s.payments.list(s.context,made!.id)).rows).toHaveLength(1);const refunds=await Promise.allSettled([s.payments.record(s.context,made!.id,{...command(s,2),kind:"refund",amountMinor:5000,method:"cash"}),s.payments.record(s.context,made!.id,{...command(s,2),kind:"refund",amountMinor:5000,method:"cash"})]);expect(refunds.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((await s.orders.byId(s.context,made!.id)).refundedMinor).toBe(5000);});
 it("deducts tracked stock only on completion and requires explicit bounded returns",async()=>{const s=await setup();await s.inventory.configure(s.context,s.variant.id,{expectedRevision:0,stockTracked:true,sessionUnits:0,expiryDays:null});await s.inventory.record(s.context,s.variant.id,{...command(s,1),kind:"receipt",quantity:3,reason:"Opening count"});const a=await s.orders.create(s.context,draft(s,2)),b=await s.orders.create(s.context,draft(s,2));await s.commands.execute(s.context,a!.id,{...command(s,0),action:"confirm"});await s.commands.execute(s.context,b!.id,{...command(s,0),action:"confirm"});expect((await s.inventory.byId(s.context,s.variant.id)).onHand).toBe(3);const results=await Promise.allSettled([s.commands.execute(s.context,a!.id,{...command(s,1),action:"complete"}),s.commands.execute(s.context,b!.id,{...command(s,1),action:"complete"})]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);const completed=(await s.orders.byId(s.context,a!.id)).state==="completed"?a!:b!;await s.commands.execute(s.context,completed.id,{...command(s,2),action:"cancel",reason:"Returned sale"});expect((await s.inventory.byId(s.context,s.variant.id)).onHand).toBe(1);await s.inventory.record(s.context,s.variant.id,{...command(s,3),kind:"return",quantity:2,orderId:completed.id,reason:"Goods received"});await expect(s.inventory.record(s.context,s.variant.id,{...command(s,4),kind:"return",quantity:1,orderId:completed.id,reason:"Too many"})).rejects.toMatchObject({status:409});expect((await s.inventory.byId(s.context,s.variant.id)).onHand).toBe(3);});
 it("grants configured service sessions, preserves use and revokes only unused sessions on cancellation",async()=>{const s=await setup();const service=await s.products.create(s.context,input("Service",undefined,"service"));const sv=(await s.products.byId(s.context,service!.id)).variants[0];await s.inventory.configure(s.context,sv.id,{expectedRevision:0,stockTracked:false,sessionUnits:5,expiryDays:null});const pack=await s.products.create(s.context,{...input("Package",undefined,"package"),packageComponents:[{componentVariantId:sv.id,quantity:1}]});const pd=await s.products.byId(s.context,pack!.id);const made=await s.orders.create(s.context,orderCreateInputSchema.parse({...draft(s),lines:[{variantId:pd.variants[0].id,expectedVariantRevision:0,expectedProductRevision:0,quantity:1}]}));await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});await s.commands.execute(s.context,made!.id,{...command(s,1),action:"complete"});const ent=(await s.entitlements.list(s.context,{orderId:made!.id})).rows[0];expect(ent).toMatchObject({granted:5,remaining:5,contactId:s.contact.id});const req={...command(s,0),kind:"use" as const,quantity:1,reason:"Actual visit"};const used=await s.entitlements.record(s.context,ent.id,req);await s.entitlements.record(s.context,ent.id,{...command(s,1),kind:"restore",quantity:1,reason:"Corrected visit"});expect(await s.entitlements.record(s.context,ent.id,req)).toEqual(used);await s.entitlements.record(s.context,ent.id,{...command(s,2),kind:"use",quantity:2,reason:"Two visits"});await s.commands.execute(s.context,made!.id,{...command(s,2),action:"cancel",reason:"Package cancelled"});expect(await s.entitlements.byId(s.context,ent.id)).toMatchObject({remaining:0,used:2,revoked:3});await expect(s.entitlements.record(s.context,ent.id,{...command(s,4),kind:"restore",quantity:1,reason:"Invalid restore"})).rejects.toMatchObject({status:409});});
 it("keeps required fields, private files and creation reservations atomic",async()=>{const s=await setup();const field=await s.services.fields.create(s.context,fieldCreateInputSchema.parse({entity:"order",type:"file",label:"Order proof",required:true}));try{await expect(s.orders.create(s.context,draft(s))).rejects.toMatchObject({status:400});const reservation=await s.services.drafts.create(s.context,{entity:"order"});const file=await s.services.files.upload(s.context,{entity:"order",recordId:reservation.id,draftId:reservation.id,fieldId:field.id},new Request("https://auth.test/files",{method:"POST",headers:{"content-type":"application/octet-stream","x-file-name":"proof.bin"},body:new Uint8Array([1,2,3])}));const prepared=await s.services.drafts.prepareConsumption(s.context,"order",reservation.id);const stale=new OrderService(intercept(s.services.db,()=>env.DB.prepare("UPDATE module_setting SET enabled=0 WHERE entity='order'").run()));await expect(stale.create(s.context,{...draft(s),customFields:{[field.key]:[file.id]}},prepared)).rejects.toMatchObject({status:403});expect(await env.DB.prepare("SELECT id FROM sales_order WHERE id=?").bind(reservation.id).first()).toBeNull();expect(await env.DB.prepare("SELECT consumed_at FROM record_draft WHERE id=?").bind(reservation.id).first()).toEqual({consumed_at:null});await env.DB.prepare("UPDATE module_setting SET enabled=1 WHERE entity='order'").run();await s.orders.create(s.context,{...draft(s),customFields:{[field.key]:[file.id]}},await s.services.drafts.prepareConsumption(s.context,"order",reservation.id));expect(await s.services.fields.values(s.context,{entity:"order",recordId:reservation.id})).toMatchObject({[field.key]:[file.id]});expect(await (await s.services.files.download(s.context,file.id)).arrayBuffer()).toEqual(new Uint8Array([1,2,3]).buffer);}finally{await env.DB.prepare("UPDATE module_setting SET enabled=1 WHERE entity='order'").run();await env.DB.prepare("UPDATE custom_field_definition SET required=0 WHERE id=?").bind(field.id).run();}});
 it("rechecks calendar and mutation authorization and preserves ledger dates",async()=>{const s=await setup();const made=await s.orders.create(s.context,draft(s));await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});const stale=new PaymentService(intercept(s.services.db,()=>env.DB.prepare("UPDATE crm_setting SET calendar_revision=calendar_revision+1 WHERE id='settings'").run()));await expect(stale.record(s.context,made!.id,{...command(s,1),kind:"collection",amountMinor:100,method:"cash"})).rejects.toMatchObject({status:409});expect((await s.payments.list(s.context,made!.id)).rows).toEqual([]);s.calendarRevision++;const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);await expect(s.payments.record(s.context,made!.id,{...command(s,1),kind:"collection",amountMinor:100,method:"cash",businessDate:yesterday})).rejects.toMatchObject({status:400});await s.payments.record(s.context,made!.id,{...command(s,1),kind:"collection",amountMinor:100,method:"cash",businessDate:yesterday,reason:"Late entry"});expect((await s.payments.list(s.context,made!.id)).rows[0].businessDate).toBe(yesterday);await env.DB.prepare("UPDATE singleton_membership SET role='member' WHERE user_id=?").bind(s.actor.id).run();await expect(s.payments.record(s.context,made!.id,{...command(s,2),kind:"refund",amountMinor:1,method:"cash"})).rejects.toMatchObject({status:403});});

 it("calculates exact explicit discounts and rejects unsupported amounts before persistence",async()=>{const s=await setup();const parsed=orderCreateInputSchema.parse({...draft(s,2),lines:[{variantId:s.variant.id,expectedVariantRevision:0,expectedProductRevision:0,quantity:2,unitPriceMinor:100000,discountMinor:10000}],discountMinor:20000,surchargeMinor:5000,taxMinor:17000});const preview=await s.orders.preview(s.context,parsed);expect(preview).toMatchObject({goodsMinor:190000,originalMinor:192000});const made=await s.orders.create(s.context,parsed);await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});await s.commands.execute(s.context,made!.id,{...command(s,1),action:"adjust",goodsMinor:70000,surchargeMinor:1000,taxMinor:7000,reason:"Partial agreed correction"});expect((await s.orders.byId(s.context,made!.id)).balanceMinor).toBe("114000");await expect(s.commands.execute(s.context,made!.id,{...command(s,2),action:"adjust",goodsMinor:0,surchargeMinor:5000,taxMinor:0,reason:"Exceeds surcharge"})).rejects.toMatchObject({status:409});await expect(s.orders.preview(s.context,{...parsed,lines:[{...parsed.lines[0],unitPriceMinor:99999999999999,quantity:1000000}]})).rejects.toMatchObject({status:400});expect(orderCreateInputSchema.safeParse({...parsed,lines:[{...parsed.lines[0],quantity:1.5}]}).success).toBe(false);const numbered=await Promise.all([s.orders.create(s.context,draft(s)),s.orders.create(s.context,draft(s))]);const rows=await Promise.all(numbered.map(r=>s.orders.byId(s.context,r!.id)));expect(new Set(rows.map(r=>r.number)).size).toBe(2);});

 it("expires backdated service grants at the captured business-day boundary",async()=>{const s=await setup();const service=await s.products.create(s.context,input("Expiring service",undefined,"service"));const v=(await s.products.byId(s.context,service!.id)).variants[0];await s.inventory.configure(s.context,v.id,{expectedRevision:0,stockTracked:false,sessionUnits:1,expiryDays:1});const made=await s.orders.create(s.context,orderCreateInputSchema.parse({...draft(s),lines:[{variantId:v.id,expectedVariantRevision:0,expectedProductRevision:0,quantity:1}]}));await s.commands.execute(s.context,made!.id,{...command(s,0),action:"confirm"});await s.commands.execute(s.context,made!.id,{...command(s,1),action:"complete",businessDate:"2020-03-07",reason:"Historical completion"});const entry=(await s.entitlements.list(s.context,{orderId:made!.id})).rows[0];const calendar=await env.DB.prepare("SELECT time_zone FROM crm_setting WHERE id='settings'").first<{time_zone:string}>();const {businessDayBounds}=await import("@/lib/services/settings/business-time");expect(entry.expiresAt).toBe(businessDayBounds("2020-03-08",calendar!.time_zone).end.toISOString());await expect(s.entitlements.record(s.context,entry.id,{...command(s,0),kind:"use",quantity:1,reason:"Expired visit"})).rejects.toMatchObject({status:409});});

});
