import {env} from "cloudflare:test";
import {beforeEach,describe,expect,it} from "vitest";
import {createCompositionRoot,type RuntimeEnv} from "@/lib/composition-root";
import type {RequestContext} from "@/lib/http/request-context";
import type {AuthEmailAdapter} from "@/lib/email/email-adapter";

const bindings=env as unknown as RuntimeEnv;
const encoder=new TextEncoder();
async function digest(value:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value)))].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
const emailAdapter:AuthEmailAdapter={async sendVerification(){},async sendPasswordReset(){}};
async function setup(){const id=crypto.randomUUID(),now=Date.now();await env.DB.prepare("INSERT INTO user(id,name,email,email_verified,created_at,updated_at) VALUES(?,?,?,1,?,?)").bind(id,"Webform owner",`${id}@example.com`,now,now).run();await env.DB.prepare("INSERT INTO singleton_membership(user_id,role,status,created_at,updated_at) VALUES(?,'owner','active',?,?)").bind(id,now,now).run();const context={userId:id,membershipId:id,role:"owner",user:{name:"Webform owner",email:`${id}@example.com`},requestId:crypto.randomUUID()} as RequestContext;return{root:createCompositionRoot(bindings,emailAdapter),context};}

describe("webform intake",()=>{
 beforeEach(async()=>{await env.DB.prepare("DELETE FROM webform_submission").run();await env.DB.prepare("DELETE FROM webform_rate_bucket").run();await env.DB.prepare("DELETE FROM webform_config").run();});
 it("maps public lead submissions and replays the same idempotency key",async()=>{const{root,context}=await setup(),created=await root.webforms.create(context,{name:"Website leads",slug:`leads-${crypto.randomUUID()}`,entity:"lead",mode:"public",source:"manual",mapping:{given:"firstName",mail:"email"},allowMissingRequired:false,rateLimitHour:10}),payload={given:"Lan",mail:"Lan@Example.com"},raw=JSON.stringify(payload),headers=new Headers({"idempotency-key":"submission-1","cf-connecting-ip":"203.0.113.2"});const first=await root.webforms.submit((await root.webforms.list(context)).find(row=>row.id===created.id)!.slug,payload,headers,raw),replay=await root.webforms.submit((await root.webforms.list(context)).find(row=>row.id===created.id)!.slug,payload,headers,raw);expect(first.replayed).toBe(false);expect(replay).toEqual({...first,replayed:true});expect(await env.DB.prepare("SELECT first_name,normalized_email,source_id FROM lead WHERE id=?").bind(first.recordId).first()).toEqual({first_name:"Lan",normalized_email:"lan@example.com",source_id:"manual"});});
 it("enforces rate limits and rejects changed replays",async()=>{const{root,context}=await setup(),slug=`tickets-${crypto.randomUUID()}`;await root.webforms.create(context,{name:"Support",slug,entity:"ticket",mode:"public",source:"website",mapping:{topic:"subject"},allowMissingRequired:false,rateLimitHour:1});const headers=new Headers({"idempotency-key":"one","cf-connecting-ip":"203.0.113.3"});await root.webforms.submit(slug,{topic:"Help"},headers,JSON.stringify({topic:"Help"}));await expect(root.webforms.submit(slug,{topic:"Changed"},headers,JSON.stringify({topic:"Changed"}))).rejects.toMatchObject({status:409});headers.set("idempotency-key","two");await expect(root.webforms.submit(slug,{topic:"Again"},headers,JSON.stringify({topic:"Again"}))).rejects.toMatchObject({status:429});});
 it("allows missing required data only for a signed system source",async()=>{const{root,context}=await setup(),slug=`system-${crypto.randomUUID()}`,created=await root.webforms.create(context,{name:"System",slug,entity:"lead",mode:"signed_system",source:"manual",mapping:{mail:"email"},allowMissingRequired:true,rateLimitHour:10}),raw=JSON.stringify({mail:"system@example.com"}),timestamp=String(Date.now()),headers=new Headers({authorization:`Bearer ${created.token}`,"x-webform-timestamp":timestamp,"x-webform-signature":await digest(`${created.token}.${timestamp}.${raw}`),"idempotency-key":"signed-1"});const result=await root.webforms.submit(slug,{mail:"system@example.com"},headers,raw);expect(result.missingFields).toEqual(["firstName"]);expect(await env.DB.prepare("SELECT first_name FROM lead WHERE id=?").bind(result.recordId).first()).toEqual({first_name:"[missing:firstName]"});headers.set("x-webform-signature","bad");headers.set("idempotency-key","signed-2");await expect(root.webforms.submit(slug,{mail:"system@example.com"},headers,raw)).rejects.toMatchObject({status:401});});
 it("keeps credential mode and record type immutable during updates",async()=>{const{root,context}=await setup(),created=await root.webforms.create(context,{name:"Public leads",slug:`immutable-${crypto.randomUUID()}`,entity:"lead",mode:"public",source:"manual",mapping:{name:"firstName"},allowMissingRequired:false,rateLimitHour:10});await expect(root.webforms.update(context,{id:created.id,expectedRevision:0,name:"Changed",slug:`changed-${crypto.randomUUID()}`,entity:"lead",mode:"signed_system",source:"manual",mapping:{name:"firstName"},allowMissingRequired:false,rateLimitHour:10,active:true})).rejects.toMatchObject({status:400});});
});
