import {env} from "cloudflare:test";
import {beforeEach,describe,expect,it} from "vitest";
import {createCompositionRoot,type RuntimeEnv} from "@/lib/composition-root";
import type {AuthEmailAdapter} from "@/lib/email/email-adapter";
import type {RequestContext} from "@/lib/http/request-context";
import {configurationCopySchema,workspaceMutationSchema} from "@/lib/services/settings/workspace-contract";

const adapter:AuthEmailAdapter={async sendVerification(){},async sendPasswordReset(){}};
async function setup(){const id=crypto.randomUUID(),now=Date.now();await env.DB.prepare("INSERT INTO user(id,name,email,email_verified,created_at,updated_at) VALUES(?,?,?,1,?,?)").bind(id,"Workspace owner",`${id}@example.com`,now,now).run();await env.DB.prepare("INSERT INTO singleton_membership(user_id,role,status,created_at,updated_at) VALUES(?,'owner','active',?,?)").bind(id,now,now).run();return{root:createCompositionRoot(env as unknown as RuntimeEnv,adapter),context:{userId:id,membershipId:id,role:"owner",user:{name:"Workspace owner",email:`${id}@example.com`},requestId:crypto.randomUUID()} as RequestContext};}

describe("workspace operations",()=>{
 beforeEach(async()=>{await env.DB.prepare("DELETE FROM workspace_deletion_object").run();await env.DB.prepare("DELETE FROM workspace_deletion_request").run();await env.DB.prepare("DELETE FROM configuration_copy_audit").run();await env.DB.prepare("UPDATE workspace_profile SET name='CRM Workspace',logo_object_key=NULL,logo_file_name=NULL,logo_content_type=NULL,logo_size=NULL,revision=0").run();});
 it("stores logo bytes in private R2 and only metadata in D1",async()=>{const{root,context}=await setup(),bytes=new Uint8Array([137,80,78,71,1,2,3]),uploaded=await root.workspace.uploadLogo(context,new Request("https://auth.test/api/crm/workspace/logo",{method:"PUT",headers:{"content-type":"image/png","content-length":String(bytes.length),"x-file-name":"logo.png"},body:bytes}),0),metadata=await env.DB.prepare("SELECT logo_object_key,logo_file_name,logo_size FROM workspace_profile").first<{logo_object_key:string;logo_file_name:string;logo_size:number}>();expect(uploaded).toMatchObject({name:"logo.png",size:bytes.length,revision:1});expect(metadata).toMatchObject({logo_file_name:"logo.png",logo_size:bytes.length});expect(await env.CRM_FILES.get(metadata!.logo_object_key)).not.toBeNull();expect(Object.keys(metadata!)).not.toContain("content");expect(new Uint8Array(await (await root.workspace.logo(context)).arrayBuffer())).toEqual(bytes);});
 it("previews and applies only the safe configuration allowlist",async()=>{const{root,context}=await setup(),base={workspaceName:"North office",timeZone:"Asia/Ho_Chi_Minh",countryCode:"VN",sources:[{id:"referral",label:"Referral"}],workspaceRevision:0,calendarRevision:0};const preview=await root.workspace.copyConfiguration(context,{...base,apply:false});expect(preview).toMatchObject({applied:false,excluded:["customers","permissions","secrets"]});expect(configurationCopySchema.safeParse({...base,apply:false,permissions:["owner"]}).success).toBe(false);const applied=await root.workspace.copyConfiguration(context,{...base,apply:true});expect(applied.applied).toBe(true);expect(await env.DB.prepare("SELECT name FROM workspace_profile").first()).toEqual({name:"North office"});expect(await env.DB.prepare("SELECT label FROM lead_source WHERE id='referral'").first()).toEqual({label:"Referral"});});
 it("requires exact owner confirmation and preserves a thirty-day cancellation window",async()=>{const{root,context}=await setup(),start=new Date("2026-09-06T00:00:00Z");await expect(root.workspace.scheduleDeletion(context,"wrong",start)).rejects.toMatchObject({status:400});const scheduled=await root.workspace.scheduleDeletion(context,"CRM Workspace",start);expect(Date.parse(scheduled.executeAfter)-start.getTime()).toBe(30*86_400_000);expect(await root.workspace.cancelDeletion(context)).toEqual({status:"cancelled"});expect(await env.DB.prepare("SELECT status,cancelled_at IS NOT NULL cancelled FROM workspace_deletion_request").first()).toEqual({status:"cancelled",cancelled:1});});
 it("matches normalized phone numbers across leads and contacts",async()=>{const{root,context}=await setup(),lead=await root.leads.create(context,{firstName:"Lead",phone:"090 123 4567",sourceId:"manual",statusId:"new",collaboratorMembershipIds:[]}),contact=await root.contacts.create(context,{firstName:"Contact",phone:"0901234567"}),match=await root.workspace.customerMatch(context,"090-123-4567");expect(match.leads.map(row=>row.id)).toContain(lead.id);expect(match.contacts.map(row=>row.id)).toContain(contact!.id);});
 it("retains protected settings before a deletion request becomes due",async()=>{const{root,context}=await setup(),start=new Date("2026-09-01T00:00:00Z");await expect(env.DB.prepare("DELETE FROM module_setting WHERE entity='lead'").run()).rejects.toThrow(/module settings must be retained/);await root.workspace.scheduleDeletion(context,"CRM Workspace",start);await expect(root.workspace.executeDeletion(context,"CRM Workspace",new Date("2026-09-15T00:00:00Z"))).rejects.toMatchObject({status:409});expect(await env.DB.prepare("SELECT count(*) count FROM user WHERE id=?").bind(context.userId).first()).toEqual({count:1});});
 it("keeps owner access and exposes an explicit retry while exhausted R2 cleanup is pending",async()=>{const{root,context}=await setup();await env.DB.batch([env.DB.prepare("INSERT INTO workspace_deletion_request(id,requested_by,requested_at,execute_after,status) VALUES('workspace',?,?,?,'executing')").bind(context.userId,1,2592000001),env.DB.prepare("INSERT INTO workspace_deletion_object(object_key,state,attempts,last_error,updated_at) VALUES('stuck','failed',20,'unavailable',1)")]);expect(await root.workspace.cleanupDeletionObjects()).toEqual({status:"executing",deletedFiles:0});expect(await env.DB.prepare("SELECT count(*) count FROM user WHERE id=?").bind(context.userId).first()).toEqual({count:1});expect(workspaceMutationSchema.safeParse({action:"retry-deletion"}).success).toBe(true);const before=(await env.CRM_FILES.list()).objects.length;await expect(root.workspace.uploadLogo(context,new Request("https://auth.test/logo",{method:"PUT",headers:{"content-type":"image/png"},body:new Uint8Array([1,2,3])}),0)).rejects.toMatchObject({status:409});expect((await env.CRM_FILES.list()).objects).toHaveLength(before);expect((await env.DB.prepare("SELECT name FROM sqlite_schema WHERE type='trigger' AND name LIKE 'workspace_deletion_block_%' ORDER BY name").all()).results.map(row=>(row as {name:string}).name)).toEqual(["workspace_deletion_block_document_insert","workspace_deletion_block_document_ready","workspace_deletion_block_file_insert","workspace_deletion_block_file_ready","workspace_deletion_block_logo"]);});
 it("atomically claims due deletion before removing D1 references and retry-tracked R2 objects",async()=>{const{root,context}=await setup(),bytes=new Uint8Array([1,2,3]);await root.workspace.uploadLogo(context,new Request("https://auth.test/logo",{method:"PUT",headers:{"content-type":"image/png"},body:bytes}),0);const key=(await env.DB.prepare("SELECT logo_object_key FROM workspace_profile").first<{logo_object_key:string}>())!.logo_object_key,start=new Date("2026-07-01T00:00:00Z");await root.workspace.scheduleDeletion(context,"CRM Workspace",start);expect(await root.workspace.executeDeletion(context,"CRM Workspace",new Date("2026-08-01T00:00:00Z"))).toEqual({status:"executing",deletedFiles:0});expect(await env.CRM_FILES.get(key)).not.toBeNull();expect(await env.DB.prepare("SELECT count(*) count FROM user WHERE id=?").bind(context.userId).first()).toEqual({count:1});expect(await root.workspace.cleanupDeletionObjects(new Date("2026-08-01T00:16:00Z"))).toEqual({status:"deleted",deletedFiles:1});expect(await env.CRM_FILES.get(key)).toBeNull();expect(await env.DB.prepare("SELECT count(*) count FROM user").first()).toEqual({count:0});expect(await env.DB.prepare("SELECT status FROM workspace_deletion_request").first()).toEqual({status:"deleted"});expect(await env.DB.prepare("SELECT object_key,state,attempts FROM workspace_deletion_object").first()).toEqual({object_key:key,state:"deleted",attempts:1});});
});
