import {and,asc,eq,gt,inArray,lt,ne,or,sql} from "drizzle-orm";
import type {AppDatabase} from "@/lib/db/database";
import {appointment,appointmentOperation,appointmentParticipant,crmSetting,productVariant} from "@/lib/db/schema";
import type {RequestContext} from "@/lib/http/request-context";
import {HttpError} from "@/lib/http/http-errors";
import {actionGuard,permissionError,requirePermission} from "../permissions/permission-policy";
import {condition} from "../orders/order-operations";
import type {AppointmentCommandInput,AppointmentCreateInput,AppointmentListInput} from "./appointment-contract";
const iso=(d:Date|null)=>d?.toISOString()??null;
export class AppointmentService{
 constructor(private readonly db:AppDatabase){}
 async create(context:RequestContext,input:AppointmentCreateInput){await requirePermission(this.db,context,["appointment.create"]);const fingerprint=JSON.stringify(input),previous=await this.db.select().from(appointmentOperation).where(eq(appointmentOperation.id,input.operationKey)).get();if(previous){if(previous.fingerprint!==fingerprint)throw new HttpError(409,"conflict","Operation key was already used");return this.byId(context,previous.appointmentId);}const calendar=await this.db.select().from(crmSetting).where(eq(crmSetting.id,"settings")).get();if(!calendar)throw new HttpError(409,"conflict","Business calendar is unavailable");if(calendar.calendarRevision!==input.calendarRevision)throw new HttpError(409,"conflict","Business timezone changed; reload the calendar");const variant=input.serviceVariantId?await this.db.select().from(productVariant).where(eq(productVariant.id,input.serviceVariantId)).get():null;const startsAt=new Date(input.startsAt),endsAt=input.endsAt?new Date(input.endsAt):new Date(startsAt.getTime()+(variant?.durationMinutes??0)*60000);if(!(endsAt>startsAt))throw new HttpError(400,"validation_failed","End time must be after start time");const organizer=input.organizerMembershipId??context.membershipId,participants=[...new Set([organizer,...input.participantMembershipIds])],id=crypto.randomUUID(),now=new Date();const conflicts=await this.conflicts(participants,startsAt,endsAt);if(conflicts.length&&!input.acknowledgeConflict)throw new HttpError(409,"conflict","Appointment overlaps another participant booking");const auth=actionGuard(this.db,context,["appointment.create"]),guard=condition(this.db,sql`exists(select 1 from crm_setting where id='settings' and calendar_revision=${input.calendarRevision}) and ${this.conflictPredicate(participants,startsAt,endsAt,null,input.acknowledgeConflict)}`);const result={id,revision:0};try{await this.db.batch([auth.begin,guard.begin,this.db.insert(appointment).values({id,subject:input.subject,description:input.description??null,startsAt,endsAt,timeZone:calendar.timeZone,contactId:input.contactId??null,companyId:input.companyId??null,serviceVariantId:input.serviceVariantId??null,organizerMembershipId:organizer,creatorUserId:context.userId,status:"scheduled",reminderEnabled:input.reminderEnabled,reminderOffsetMinutes:input.reminderOffsetMinutes,conflictAcknowledgedAt:conflicts.length?now:null,conflictAcknowledgedBy:conflicts.length?context.userId:null,revision:0,createdAt:now,updatedAt:now}),...participants.map(membershipId=>this.db.insert(appointmentParticipant).values({appointmentId:id,membershipId})),this.db.insert(appointmentOperation).values({id:input.operationKey,appointmentId:id,action:"create",fingerprint,resultJson:JSON.stringify(result),actorId:context.userId,createdAt:now}),guard.end,auth.end]);return this.byId(context,id);}catch(error){this.error(error);}}
 async list(context:RequestContext,input:AppointmentListInput){await requirePermission(this.db,context);const clauses=[ne(appointment.status,"cancelled")];if(input.from)clauses.push(gt(appointment.endsAt,new Date(input.from)));if(input.to)clauses.push(lt(appointment.startsAt,new Date(input.to)));if(input.scope==="mine")clauses.push(or(eq(appointment.organizerMembershipId,context.membershipId),sql`exists(select 1 from appointment_participant p where p.appointment_id=${appointment.id} and p.membership_id=${context.membershipId})`)!);const rows=await this.db.select().from(appointment).where(and(...clauses)).orderBy(asc(appointment.startsAt)).limit(input.limit);return{rows:await Promise.all(rows.map(r=>this.serialize(r)))};}
 async byId(context:RequestContext,id:string){await requirePermission(this.db,context);const row=await this.db.select().from(appointment).where(eq(appointment.id,id)).get();if(!row)throw new HttpError(404,"not_found","Appointment was not found");return this.serialize(row);}
 async command(context:RequestContext,id:string,input:AppointmentCommandInput){const current=await this.db.select().from(appointment).where(eq(appointment.id,id)).get();if(!current)throw new HttpError(404,"not_found","Appointment was not found");const fingerprint=JSON.stringify(input),previous=await this.db.select().from(appointmentOperation).where(eq(appointmentOperation.id,input.operationKey)).get();if(previous){if(previous.appointmentId!==id||previous.fingerprint!==fingerprint)throw new HttpError(409,"conflict","Operation key was already used");return this.byId(context,id);}if(current.revision!==input.expectedRevision||current.status!=="scheduled")throw new HttpError(409,"conflict","Appointment changed before the update");const now=new Date(),permission=input.action==="cancel"?"appointment.cancel":"appointment.update",participants=input.action==="reschedule"?[...new Set([current.organizerMembershipId,...input.participantMembershipIds])]:await this.participants(id),startsAt=input.action==="reschedule"?new Date(input.startsAt):current.startsAt,endsAt=input.action==="reschedule"?new Date(input.endsAt):current.endsAt,conflicts=input.action==="reschedule"?await this.conflicts(participants,startsAt,endsAt,id):[],acknowledged=input.action!=="reschedule"||input.acknowledgeConflict;if(conflicts.length&&!acknowledged)throw new HttpError(409,"conflict","Appointment overlaps another participant booking");const auth=actionGuard(this.db,context,[permission]),guard=condition(this.db,sql`exists(select 1 from appointment where id=${id} and revision=${current.revision} and status='scheduled') and ${this.conflictPredicate(participants,startsAt,endsAt,id,acknowledged)}`),status:"scheduled"|"completed"|"cancelled"=input.action==="cancel"?"cancelled":input.action==="complete"?"completed":"scheduled",result={id,revision:current.revision+1,status};try{await this.db.batch([auth.begin,guard.begin,...input.action==="reschedule"?[this.db.delete(appointmentParticipant).where(eq(appointmentParticipant.appointmentId,id)),...participants.map(membershipId=>this.db.insert(appointmentParticipant).values({appointmentId:id,membershipId}))]:[],this.db.update(appointment).set(input.action==="reschedule"?{startsAt,endsAt,conflictAcknowledgedAt:conflicts.length?now:null,conflictAcknowledgedBy:conflicts.length?context.userId:null,revision:result.revision,updatedAt:now}:{status:result.status,revision:result.revision,updatedAt:now}).where(eq(appointment.id,id)),this.db.insert(appointmentOperation).values({id:input.operationKey,appointmentId:id,action:input.action==="reschedule"?"update":input.action,fingerprint,resultJson:JSON.stringify(result),actorId:context.userId,createdAt:now}),guard.end,auth.end]);return this.byId(context,id);}catch(error){this.error(error);}}
 private async participants(id:string){return (await this.db.select().from(appointmentParticipant).where(eq(appointmentParticipant.appointmentId,id))).map(r=>r.membershipId);}
 private async conflicts(ids:string[],start:Date,end:Date,exclude?:string){if(!ids.length)return[];return this.db.select({id:appointment.id}).from(appointment).innerJoin(appointmentParticipant,eq(appointmentParticipant.appointmentId,appointment.id)).where(and(inArray(appointmentParticipant.membershipId,ids),eq(appointment.status,"scheduled"),lt(appointment.startsAt,end),gt(appointment.endsAt,start),exclude?ne(appointment.id,exclude):undefined)).limit(10);}
 private conflictPredicate(ids:string[],start:Date,end:Date,exclude:string|null,acknowledged:boolean){return acknowledged?sql`1=1`:sql`not exists(select 1 from appointment a join appointment_participant p on p.appointment_id=a.id where p.membership_id in (select value from json_each(${JSON.stringify(ids)})) and a.status='scheduled' and a.starts_at<${end.getTime()} and a.ends_at>${start.getTime()} ${exclude?sql`and a.id<>${exclude}`:sql``})`;}
 private async serialize(row:typeof appointment.$inferSelect){return{...row,participantMembershipIds:await this.participants(row.id),startsAt:row.startsAt.toISOString(),endsAt:row.endsAt.toISOString(),conflictAcknowledgedAt:iso(row.conflictAcknowledgedAt),createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()};}
 private error(error:unknown):never{try{permissionError(error);}catch(original){let e=original;while(e&&typeof e==="object"){if(e instanceof Error&&/operation_condition|appointment_|UNIQUE|FOREIGN KEY/.test(e.message))throw new HttpError(409,"conflict","Appointment changed or conflicts with another booking");e="cause" in e?e.cause:null;}throw original;}}
}
