"use client";

import { useMemo, useState } from "react";
import Search from "@carbon/icons-react/es/Search";
import Filter from "@carbon/icons-react/es/Filter";
import Column from "@carbon/icons-react/es/Column";
import ArrowsVertical from "@carbon/icons-react/es/ArrowsVertical";
import ChevronLeft from "@carbon/icons-react/es/ChevronLeft";
import ChevronRight from "@carbon/icons-react/es/ChevronRight";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuContent, DropdownMenuCheckboxItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { AppDictionary } from "@/lib/i18n/dictionary";
import { getCrmDictionary } from "@/lib/i18n/crm-dictionary";
import { getShellInterfaceDictionary } from "@/lib/i18n/shell-interface-dictionary";
import { MemberActions, type MemberView } from "./member-actions";

type ColumnKey = "email" | "role" | "status" | "createdAt";
type SortKey = "name" | "email" | "role" | "createdAt";
export function MembersTable({ currentMembershipId, dictionary, members }: { currentMembershipId: string; dictionary: AppDictionary; members: MemberView[] }) {
  const labels = getCrmDictionary(dictionary.locale); const copy = getShellInterfaceDictionary(dictionary.locale);
  const [query, setQuery] = useState(""); const [roles, setRoles] = useState<string[]>([]); const [page, setPage] = useState(1);
  const [sort, setSort] = useState<SortKey>("name"); const [direction, setDirection] = useState("asc"); const [visible, setVisible] = useState<ColumnKey[]>(["email", "role", "status", "createdAt"]);
  const columnLabels = { name: dictionary.common.name, email: dictionary.common.email, role: dictionary.members.role, status: dictionary.members.status, createdAt: copy.joined };
  const rows = useMemo(() => members.filter(member => `${member.name} ${member.email}`.toLocaleLowerCase(dictionary.locale).includes(query.toLocaleLowerCase(dictionary.locale)) && (!roles.length || roles.includes(member.role))).sort((a, b) => { const difference = sort === "createdAt" ? Date.parse(a.createdAt) - Date.parse(b.createdAt) : a[sort].localeCompare(b[sort], dictionary.locale); return direction === "asc" ? difference : -difference; }), [members, query, roles, sort, direction, dictionary.locale]);
  const pageSize = 25; const pages = Math.max(1, Math.ceil(rows.length / pageSize)); const currentPage = Math.min(page, pages); const pageRows = rows.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  function sortBy(value: string) { setSort(value as SortKey); setPage(1); }
  return <div className="flex min-h-0 flex-1 flex-col gap-3">
    <div className="flex flex-wrap items-center gap-2"><div className="relative min-w-0 flex-1 sm:max-w-sm"><Search aria-hidden="true" className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-8" aria-label={labels.search} placeholder={`${labels.search}…`} value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} /></div><div className="flex flex-wrap gap-2 sm:ml-auto">
      <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm"><Filter />{labels.filters}{roles.length > 0 && <span className="text-muted-foreground">({roles.length})</span>}</Button></DropdownMenuTrigger><DropdownMenuContent>{(["owner", "member"] as const).map(role => <DropdownMenuCheckboxItem key={role} checked={roles.includes(role)} onCheckedChange={checked => { setRoles(previous => checked ? [...previous, role] : previous.filter(item => item !== role)); setPage(1); }}>{dictionary.members[role]}<span className="ml-auto pl-4 text-muted-foreground tabular-nums">{members.filter(member => member.role === role).length}</span></DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu>
      <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm"><ArrowsVertical />{labels.sort}</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuRadioGroup value={sort} onValueChange={sortBy}>{(["name", "email", "role", "createdAt"] as const).map(key => <DropdownMenuRadioItem key={key} value={key}>{columnLabels[key]}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup><DropdownMenuSeparator /><DropdownMenuRadioGroup value={direction} onValueChange={value => { setDirection(value); setPage(1); }}><DropdownMenuRadioItem value="asc">{labels.asc}</DropdownMenuRadioItem><DropdownMenuRadioItem value="desc">{labels.desc}</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu>
      <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm"><Column />{labels.columns}</Button></DropdownMenuTrigger><DropdownMenuContent>{(["email", "role", "status", "createdAt"] as const).map(key => <DropdownMenuCheckboxItem key={key} checked={visible.includes(key)} onCheckedChange={checked => setVisible(previous => checked ? [...previous, key] : previous.filter(item => item !== key))}>{columnLabels[key]}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu>
    </div></div>
    <div className="min-h-0 overflow-auto rounded-lg border bg-card"><Table className="table-fixed"><TableHeader className="bg-muted"><TableRow><TableHead className="w-[30%]"><button type="button" className="flex items-center gap-1" onClick={() => { if (sort === "name") setDirection(direction === "asc" ? "desc" : "asc"); else sortBy("name"); }}>{dictionary.common.name}<ArrowsVertical size={12} /></button></TableHead>{visible.includes("email") && <TableHead className="hidden w-[24%] md:table-cell">{dictionary.common.email}</TableHead>}{visible.includes("role") && <TableHead className="w-[12%]">{dictionary.members.role}</TableHead>}{visible.includes("status") && <TableHead className="hidden w-[12%] lg:table-cell">{dictionary.members.status}</TableHead>}{visible.includes("createdAt") && <TableHead className="hidden w-[16%] text-right sm:table-cell">{copy.joined}</TableHead>}<TableHead className="w-12 text-right"><span className="sr-only">{dictionary.members.actions}</span></TableHead></TableRow></TableHeader><TableBody>{pageRows.map(member => <TableRow key={member.membershipId}><TableCell><div className="flex min-w-0 items-center gap-2"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-medium">{member.name.split(" ").map(part => part[0]).slice(0, 2).join("").toUpperCase() || "?"}</span><span className="truncate font-medium" title={member.name}>{member.name}</span>{member.membershipId === currentMembershipId && <span className="text-xs text-muted-foreground">{copy.you}</span>}</div></TableCell>{visible.includes("email") && <TableCell className="hidden truncate text-muted-foreground md:table-cell" title={member.email}>{member.email}</TableCell>}{visible.includes("role") && <TableCell className="text-muted-foreground">{member.role === "owner" ? dictionary.members.owner : dictionary.members.member}</TableCell>}{visible.includes("status") && <TableCell className="hidden lg:table-cell"><span className="flex items-center gap-1.5 text-xs"><span aria-hidden="true" className={`size-1.5 shrink-0 rounded-full ${member.status === "active" ? "bg-success" : "bg-muted-foreground"}`} />{member.status === "active" ? dictionary.members.active : dictionary.members.revoked}</span></TableCell>}{visible.includes("createdAt") && <TableCell className="hidden text-right text-muted-foreground sm:table-cell"><time dateTime={member.createdAt}>{new Intl.DateTimeFormat(dictionary.locale, { dateStyle: "medium" }).format(new Date(member.createdAt))}</time></TableCell>}<TableCell><div className="flex justify-end"><MemberActions currentMembershipId={currentMembershipId} dictionary={dictionary} member={member} members={members} /></div></TableCell></TableRow>)}{!rows.length && <TableRow><TableCell colSpan={visible.length + 2} className="h-32 text-center text-muted-foreground">{labels.empty}</TableCell></TableRow>}</TableBody></Table></div>
    <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground tabular-nums"><span>{rows.length ? `${copy.showing} ${(currentPage - 1) * pageSize + 1}–${Math.min(currentPage * pageSize, rows.length)} ${copy.of} ${rows.length}` : labels.empty}</span>{pages > 1 && <div className="flex items-center gap-2"><Button size="sm" variant="ghost" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)}><ChevronLeft />{labels.previous}</Button><span>{currentPage} / {pages}</span><Button size="sm" variant="contrast" disabled={currentPage >= pages} onClick={() => setPage(currentPage + 1)}>{labels.next}<ChevronRight /></Button></div>}</div>
  </div>;
}
