"use client";
import { useEffect, useState } from "react";
import type { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { AppLocale } from "@/lib/i18n/config";
import { getOrderDictionary } from "@/lib/i18n/order-dictionary";
import { getCrmDictionary } from "@/lib/i18n/crm-dictionary";
import { entitlementRecordInputSchema, type entitlementOutputSchema, type entitlementHistoryOutputSchema } from "@/lib/services/entitlements/entitlement-contract";
import { crmRequest, requestError } from "../record-types";
import { useModules } from "../module-provider";
import { OrderOperationForm } from "./order-operation-form";
type Entitlement = z.infer<typeof entitlementOutputSchema>;
type History = z.infer<typeof entitlementHistoryOutputSchema>;
function EntitlementAction({ value, kind, locale, disabled, onDone }: { value: Entitlement; kind: "use" | "restore"; locale: AppLocale; disabled: boolean; onDone: () => void }) {
  const labels = getOrderDictionary(locale); const [current, setCurrent] = useState(value); const [quantity, setQuantity] = useState("1");
  return <OrderOperationForm title={kind === "use" ? labels.consume : labels.reverseUse} help={labels.entitlementHelp} revision={value.revision} locale={locale} requireReason disabled={disabled} onCancel={onDone} onSaved={onDone} refresh={async () => { const next = await crmRequest<Entitlement>(`/api/crm/entitlements/${value.id}`); setCurrent(next); return next.revision; }} prepare={metadata => entitlementRecordInputSchema.parse({ ...metadata, kind, quantity: Number(quantity) })} submit={payload => crmRequest(`/api/crm/entitlements/${value.id}`, { method: "POST", body: JSON.stringify(payload) })}><p className="text-sm">{labels.remaining}: {current.remaining} · {labels.used}: {current.used}</p><label className="block space-y-1 text-sm">{labels.quantity}<Input type="number" min={1} max={1_000_000} step={1} required value={quantity} onChange={event => setQuantity(event.target.value)} /></label></OrderOperationForm>;
}
export function EntitlementPanel({ orderId, contactId, locale, readOnly }: { orderId?: string; contactId?: string; locale: AppLocale; readOnly?: boolean }) {
  const labels = getOrderDictionary(locale), crm = getCrmDictionary(locale), modules = useModules(); const [rows, setRows] = useState<Entitlement[]>([]); const [revision, setRevision] = useState(0); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<{ value: Entitlement; kind: "use" | "restore" }>(); const [history, setHistory] = useState<{ id: string; data: History }>();
  useEffect(() => { const controller = new AbortController(); const query = new URLSearchParams({ ...(orderId ? { orderId } : {}), ...(contactId ? { contactId } : {}) }); void crmRequest<{ rows: Entitlement[] }>(`/api/crm/entitlements?${query}`, { signal: controller.signal }).then(data => { if (!controller.signal.aborted) { setRows(data.rows); setError(""); setLoading(false); } }).catch(reason => { if (!controller.signal.aborted) { setError(requestError(reason, crm)); setLoading(false); } }); return () => controller.abort(); }, [orderId, contactId, revision]);
  const disabled = Boolean(readOnly || !modules.isEnabled("order") || error || loading);
  function done() { setSelected(undefined); setHistory(undefined); setRevision(value => value + 1); }
  return <section className="min-w-0 space-y-4 border-t p-5 [overflow-wrap:anywhere]"><h3 className="font-medium">{labels.entitlement}</h3><p className="text-sm text-muted-foreground">{labels.entitlementHelp}</p>{loading && <p role="status">{labels.loading}</p>}{error && <p role="alert">{error}<Button variant="outline" onClick={() => setRevision(value => value + 1)}>{crm.retry}</Button></p>}{!loading && !rows.length && <p className="text-sm text-muted-foreground">{labels.none}</p>}<ul className="space-y-3">{rows.map(row => <li key={row.id} data-entitlement-id={row.id} className="space-y-3 rounded-md border p-3"><h4 className="break-words font-medium">{row.label}</h4><p className="text-sm">{labels.granted}: {row.granted} · {labels.used}: {row.used} · {labels.remaining}: {row.remaining} · {labels.revoked}: {row.revoked}</p><p className="text-xs text-muted-foreground">{row.expiresAt ? `${labels.expiresAt}: ${new Date(row.expiresAt).toLocaleDateString(locale)}` : labels.noExpiry}</p><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={disabled || Boolean(selected) || row.revoked > 0 || row.remaining <= 0} onClick={() => setSelected({ value: row, kind: "use" })}>{labels.consume}</Button><Button variant="outline" size="sm" disabled={disabled || Boolean(selected) || row.revoked > 0 || row.used <= 0} onClick={() => setSelected({ value: row, kind: "restore" })}>{labels.reverseUse}</Button><Button variant="ghost" size="sm" onClick={async () => { try { setHistory({ id: row.id, data: await crmRequest<History>(`/api/crm/entitlements/${row.id}/history`) }); } catch (failure) { setError(requestError(failure, crm)); } }}>{labels.history}</Button></div>{history?.id === row.id && <ol className="space-y-2 text-sm">{history.data.rows.map(event => <li key={event.id} className="border-t pt-2"><p>{({ grant: labels.granted, use: labels.consume, restore: labels.reverseUse, revoke: labels.cancelOrder })[event.kind]} · {event.quantity} · {event.businessDate}</p><p className="break-words">{event.reason}</p>{event.actorName && <p className="text-xs text-muted-foreground">{event.actorName}</p>}<time className="text-xs text-muted-foreground" dateTime={event.createdAt}>{labels.recordedAt}: {new Date(event.createdAt).toLocaleString(locale)}</time></li>)}</ol>}</li>)}</ul>{selected && <EntitlementAction key={`${selected.value.id}-${selected.kind}`} value={selected.value} kind={selected.kind} locale={locale} disabled={disabled} onDone={done} />}</section>;
}
