"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { AppLocale } from "@/lib/i18n/config";
import { getOrderDictionary } from "@/lib/i18n/order-dictionary";
import { getCrmDictionary } from "@/lib/i18n/crm-dictionary";
import { inventoryConfigureInputSchema, inventoryRecordInputSchema, type inventoryVariantOutputSchema, type inventoryHistoryOutputSchema } from "@/lib/services/inventory/inventory-contract";
import { crmRequest, requestError, type CrmRecord } from "../record-types";
import { useModules } from "../module-provider";
import { OrderOperationForm } from "./order-operation-form";
type Variant = z.infer<typeof inventoryVariantOutputSchema>; type History = z.infer<typeof inventoryHistoryOutputSchema>;
function InventoryMovementForm({ variant, kind, locale, disabled, onDone }: { variant: Variant; kind: "receipt" | "adjustment" | "return"; locale: AppLocale; disabled: boolean; onDone: () => void }) {
  const labels = getOrderDictionary(locale); const [current, setCurrent] = useState(variant); const [quantity, setQuantity] = useState(""); const [query, setQuery] = useState(""); const [orders, setOrders] = useState<CrmRecord[]>([]); const [selected, setSelected] = useState<CrmRecord>(); const [error, setError] = useState(false); const [lookupRevision, setLookupRevision] = useState(0);
  useEffect(() => { if (kind !== "return") return; const controller = new AbortController(); const timer = setTimeout(() => { void crmRequest<{ rows: CrmRecord[] }>(`/api/crm/orders?q=${encodeURIComponent(query)}&pageSize=30`, { signal: controller.signal }).then(data => { if (!controller.signal.aborted) { setOrders(data.rows); setError(false); } }).catch(() => { if (!controller.signal.aborted) setError(true); }); }, 250); return () => { controller.abort(); clearTimeout(timer); }; }, [query, kind, lookupRevision]);
  return <OrderOperationForm title={labels[kind === "receipt" ? "stockReceipt" : kind === "adjustment" ? "stockAdjustment" : "stockReturn"]} help={labels.stockHelp} revision={variant.revision} locale={locale} disabled={disabled} requireReason onCancel={onDone} onSaved={onDone} refresh={async () => { const next = await crmRequest<Variant>(`/api/crm/inventory/variants/${variant.variantId}`); setCurrent(next); return next.revision; }} prepare={metadata => { if (kind === "return" && !selected) throw new Error("400"); return inventoryRecordInputSchema.parse({ ...metadata, kind, quantity: Number(quantity), ...(selected ? { orderId: selected.id } : {}) }); }} submit={payload => crmRequest(`/api/crm/inventory/variants/${variant.variantId}`, { method: "POST", body: JSON.stringify(payload) })}><p className="text-sm">{labels.onHand}: {current.onHand}</p><label className="block space-y-1 text-sm">{labels.quantity}<Input type="number" min={kind === "adjustment" ? -1_000_000 : 1} max={1_000_000} step={1} required value={quantity} onChange={event => setQuantity(event.target.value)} /></label>{kind === "return" && <div className="space-y-2"><label className="block text-sm">{labels.title}<Input value={query} onChange={event => setQuery(event.target.value)} /></label>{selected && <p className="text-sm">{labels.selected}: {selected.name}</p>}{error && <p role="alert">{labels.unavailable}<Button type="button" variant="outline" onClick={() => setLookupRevision(value => value + 1)}>{labels.retry}</Button></p>}<ul className="max-h-40 overflow-auto">{orders.map(order => <li key={order.id}><Button type="button" variant={selected?.id === order.id ? "secondary" : "ghost"} className="h-auto w-full justify-start whitespace-normal" onClick={() => setSelected(order)}>{order.name} · {String(order.number)}</Button></li>)}</ul></div>}</OrderOperationForm>;
}
function InventoryConfiguration({ value, locale, disabled, onDone }: { value: Variant; locale: AppLocale; disabled: boolean; onDone: () => void }) {
  const labels = getOrderDictionary(locale), crm = getCrmDictionary(locale); const [baseline, setBaseline] = useState(value); const [tracked, setTracked] = useState(value.stockTracked); const [sessions, setSessions] = useState(String(value.sessionUnits)); const [expiry, setExpiry] = useState(value.expiryDays == null ? "" : String(value.expiryDays)); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [stale, setStale] = useState(false);
  async function save() { setError(""); let data; try { data = inventoryConfigureInputSchema.parse({ expectedRevision: baseline.revision, stockTracked: tracked, sessionUnits: Number(sessions), expiryDays: expiry === "" ? null : Number(expiry) }); } catch { setError(crm.invalid); return; } setBusy(true); try { await crmRequest(`/api/crm/inventory/variants/${baseline.variantId}`, { method: "PATCH", body: JSON.stringify(data) }); onDone(); } catch (reason) { setError(requestError(reason, crm)); setStale(reason instanceof Error && reason.message === "409"); } finally { setBusy(false); } }
  return <form className="space-y-3 rounded-md border p-3" onSubmit={event => { event.preventDefault(); if (!disabled && !stale) void save(); }}><fieldset className="space-y-3" disabled={disabled || busy || stale}><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={tracked} disabled={value.kind !== "product"} onChange={event => setTracked(event.target.checked)} />{labels.inventoryTracking}</label>{value.kind === "service" && <><label className="block space-y-1 text-sm">{labels.granted}<Input type="number" required min={0} max={1_000_000} step={1} value={sessions} onChange={event => setSessions(event.target.value)} /></label><label className="block space-y-1 text-sm">{labels.expiresAfter}<Input type="number" min={1} max={36500} step={1} value={expiry} onChange={event => setExpiry(event.target.value)} /></label><p className="text-xs text-muted-foreground">{labels.noExpiry}: {labels.leaveBlank}</p></>}</fieldset>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{stale && <div className="space-y-2"><p className="text-xs">{labels.discardConfiguration}</p><Button type="button" variant="outline" disabled={busy} onClick={async () => { setBusy(true); try { const next = await crmRequest<Variant>(`/api/crm/inventory/variants/${value.variantId}`); setBaseline(next); setTracked(next.stockTracked); setSessions(String(next.sessionUnits)); setExpiry(next.expiryDays == null ? "" : String(next.expiryDays)); setStale(false); setError(""); } catch (reason) { setError(requestError(reason, crm)); } finally { setBusy(false); } }}>{labels.reload}</Button></div>}<div className="flex flex-wrap gap-2"><Button type="submit" disabled={disabled || busy || stale}>{crm.save}</Button><Button type="button" variant="outline" disabled={busy} onClick={onDone}>{crm.cancel}</Button></div></form>;
}
export function InventoryPanel({ locale, initialData }: { locale: AppLocale; initialData?: { rows: Variant[] } }) {
  const variantId = useSearchParams().get("variantId");
  const labels = getOrderDictionary(locale), crm = getCrmDictionary(locale), modules = useModules(); const [rows, setRows] = useState(initialData?.rows ?? []); const [query, setQuery] = useState(""); const [revision, setRevision] = useState(0); const [error, setError] = useState(""); const [selected, setSelected] = useState<{ value: Variant; kind: "configure" | "receipt" | "adjustment" | "return" }>(); const [history, setHistory] = useState<{ id: string; data: History }>();
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => { void (variantId && !query ? crmRequest<Variant>(`/api/crm/inventory/variants/${encodeURIComponent(variantId)}`, { signal: controller.signal }).then(row => ({ rows: [row] })) : crmRequest<{ rows: Variant[] }>(`/api/crm/inventory?q=${encodeURIComponent(query)}&pageSize=30`, { signal: controller.signal })).then(data => { if (!controller.signal.aborted) { setRows(data.rows); setError(""); } }).catch(reason => { if (!controller.signal.aborted) setError(requestError(reason, crm)); }); }, 250); return () => { controller.abort(); clearTimeout(timer); }; }, [query, revision, variantId]);
  const disabled = !modules.isEnabled("product") || Boolean(error); function done() { setSelected(undefined); setHistory(undefined); setRevision(value => value + 1); }
  return <section className="mx-auto min-w-0 max-w-4xl space-y-5 [overflow-wrap:anywhere]"><h1 className="text-2xl font-medium">{labels.inventory}</h1><p className="text-sm text-muted-foreground">{labels.stockHelp}</p><Input aria-label={labels.chooseVariant} value={query} onChange={event => setQuery(event.target.value)} />{error && <p role="alert">{error}<Button variant="outline" onClick={() => setRevision(value => value + 1)}>{crm.retry}</Button></p>}<ul className="space-y-4">{rows.map(row => <li key={row.variantId} data-inventory-variant-id={row.variantId} className="space-y-3 rounded-md border p-4"><h2 className="break-words font-medium">{row.productName} · {row.label}</h2><p>{labels.onHand}: {row.stockTracked ? row.onHand : "—"}{row.kind === "service" ? ` · ${labels.granted}: ${row.sessionUnits}` : ""}</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={disabled || Boolean(selected)} onClick={() => setSelected({ value: row, kind: "configure" })}>{crm.edit}</Button>{row.stockTracked && (["receipt", "adjustment", "return"] as const).map(kind => <Button key={kind} variant="outline" disabled={disabled || Boolean(selected)} onClick={() => setSelected({ value: row, kind })}>{labels[kind === "receipt" ? "stockReceipt" : kind === "adjustment" ? "stockAdjustment" : "stockReturn"]}</Button>)}<Button variant="ghost" onClick={async () => { try { setHistory({ id: row.variantId, data: await crmRequest<History>(`/api/crm/inventory/variants/${row.variantId}/history`) }); } catch (reason) { setError(requestError(reason, crm)); } }}>{labels.history}</Button></div>{history?.id === row.variantId && <ol className="space-y-2 text-sm">{history.data.rows.map(event => <li key={event.id} className="border-t pt-2"><p>{({ receipt: labels.stockReceipt, adjustment: labels.stockAdjustment, sale: labels.complete, return: labels.stockReturn })[event.kind]} · {event.quantity} · {event.businessDate}</p><p className="break-words">{event.reason}</p>{event.actorName && <p className="text-xs text-muted-foreground">{event.actorName}</p>}<time className="text-xs text-muted-foreground" dateTime={event.createdAt}>{labels.recordedAt}: {new Date(event.createdAt).toLocaleString(locale)}</time></li>)}</ol>}{selected?.value.variantId === row.variantId && (selected.kind === "configure" ? <InventoryConfiguration key={`${row.variantId}-configure`} value={selected.value} locale={locale} disabled={disabled} onDone={done} /> : <InventoryMovementForm key={`${row.variantId}-${selected.kind}`} variant={selected.value} kind={selected.kind} locale={locale} disabled={disabled} onDone={done} />)}</li>)}</ul></section>;
}
