"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { AppLocale } from "@/lib/i18n/config";
import { getCrmDictionary } from "@/lib/i18n/crm-dictionary";
import { getOrderDictionary } from "@/lib/i18n/order-dictionary";
import type { BusinessSettings } from "@/lib/services/settings/business-settings-contracts";
import { crmRequest, requestError } from "../record-types";
export type OrderOperationMetadata = { operationKey: string; expectedRevision: number; businessDate: string; calendarRevision: number; reason: string };
export function OrderOperationForm({ title, help, revision, locale, disabled, requireReason, children, prepare, submit, refresh, onSaved, onCancel }: { title: string; help?: string; revision: number; locale: AppLocale; disabled?: boolean; requireReason?: boolean; children?: ReactNode; prepare: (metadata: OrderOperationMetadata) => unknown; submit: (payload: unknown) => Promise<unknown>; refresh: () => Promise<number>; onSaved: () => void; onCancel: () => void }) {
  const labels = getOrderDictionary(locale), crm = getCrmDictionary(locale); const [calendar, setCalendar] = useState<BusinessSettings>(); const [date, setDate] = useState(""); const [reason, setReason] = useState(""); const [baseline, setBaseline] = useState(revision); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [loadRevision, setLoadRevision] = useState(0); const [uncertain, setUncertain] = useState(false); const [conflict, setConflict] = useState(false); const pending = useRef<unknown>(undefined);
  useEffect(() => { const controller = new AbortController(); void crmRequest<BusinessSettings>("/api/crm/settings", { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setCalendar(value); setDate(previous => previous || value.today); setError(""); } }).catch(reason => { if (!controller.signal.aborted) setError(requestError(reason, crm)); }); return () => controller.abort(); }, [loadRevision]);
  async function save() {
    if (busy || !calendar || disabled && pending.current === undefined) return; setError("");
    try { if (pending.current === undefined) pending.current = prepare({ operationKey: crypto.randomUUID(), expectedRevision: baseline, businessDate: date, calendarRevision: calendar.revision, reason }); } catch { setError(crm.invalid); return; }
    setBusy(true); try { await submit(pending.current); pending.current = undefined; setUncertain(false); onSaved(); } catch (failure) { setError(requestError(failure, crm)); const status = failure instanceof Error ? failure.message : ""; setConflict(status === "409"); if (["400", "403", "404"].includes(status)) { pending.current = undefined; setUncertain(false); } else setUncertain(true); } finally { setBusy(false); }
  }
  async function review() { setBusy(true); setError(""); try { const [next, settings] = await Promise.all([refresh(), crmRequest<BusinessSettings>("/api/crm/settings")]); setBaseline(next); setCalendar(settings); pending.current = undefined; setUncertain(false); } catch (failure) { setError(requestError(failure, crm)); } finally { setBusy(false); } }
  return <form className="space-y-4 rounded-md border p-4" onSubmit={event => { event.preventDefault(); void save(); }}><h3 className="font-medium">{title}</h3>{help && <p className="text-sm text-muted-foreground">{help}</p>}<fieldset disabled={busy || disabled || uncertain || !calendar} className="space-y-3 min-w-0">{children}<label className="block space-y-1 text-sm">{labels.businessDate}<Input type="date" required value={date} onChange={event => setDate(event.target.value)} /></label><label className="block space-y-1 text-sm">{labels.reason}<Textarea value={reason} maxLength={2000} required={requireReason || Boolean(calendar && date < calendar.today)} onChange={event => setReason(event.target.value)} /></label><p className="text-xs text-muted-foreground">{calendar?.timeZone} · {labels.backdateHelp}</p></fieldset>{!calendar && !error && <p role="status">{labels.loading}</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{!calendar && error && <Button type="button" variant="outline" disabled={busy} onClick={() => setLoadRevision(value => value + 1)}>{crm.retry}</Button>}{uncertain && <div className="space-y-2"><p className="text-sm">{conflict ? labels.conflict : labels.uncertain}</p><p className="text-xs text-muted-foreground">{labels.reloadDiscard}</p><div className="flex flex-wrap gap-2"><Button type="button" disabled={busy} onClick={() => void save()}>{labels.retry}</Button><Button type="button" variant="outline" disabled={busy} onClick={() => void review()}>{labels.refresh}</Button></div></div>}<div className="flex flex-wrap gap-2"><Button type="submit" disabled={busy || disabled || uncertain || !calendar}>{crm.save}</Button><Button type="button" variant="outline" disabled={busy} onClick={onCancel}>{crm.cancel}</Button></div></form>;
}
