import type { AppLocale } from "./config";
const en = {
  title: "Catalog", product: "Product", service: "Service", package: "Package", kind: "Catalog type", kindHelp: "The type stays the same after creation.", categories: "Catalog categories", category: "Category", categoryHelp: "Archived categories remain on existing records.", label: "Label", variants: "Variants", initialVariant: "Initial variant", defaultVariant: "Default variant", sku: "SKU", price: "Price", cost: "Cost", costHelp: "Leave blank when the cost is unknown.", currency: "Currency", duration: "Duration in minutes", durationHelp: "Descriptive duration; no appointment is booked.", attributes: "Variant attributes", attributeName: "Attribute name", attributeValue: "Attribute value", addAttribute: "Add attribute", addVariant: "Add variant", components: "Package composition", componentHelp: "Composition describes what is included; it does not consume stock or service sessions.", chooseComponent: "Search products and services", quantity: "Quantity", addComponent: "Add component", remove: "Remove", none: "None", archive: "Archive", restore: "Restore", up: "Move up", down: "Move down", reload: "Reload current data", conflict: "This record changed. Reload current data before saving.", saved: "Catalog saved", categoriesSaved: "Categories saved", minorHelp: "Enter an amount in the selected currency. Changing currency does not convert the price.", requiredPrice: "Enter the actual price for the initial variant.", images: "Private catalog images", active: "Active", archived: "Archived", name: "Name", invalidAttributes: "Attribute names must be unique and nonempty.", editVariant: "Edit variant", cancel: "Cancel", save: "Save", unavailable: "Unavailable", defaultProtected: "The default variant remains available while its product is active.", reloadHelp: "Reload discards unsaved changes in this editor.", units: "units",
};
const vi: typeof en = {
  title: "Danh mục", product: "Sản phẩm", service: "Dịch vụ", package: "Gói", kind: "Loại danh mục", kindHelp: "Loại được giữ nguyên sau khi tạo.", categories: "Nhóm danh mục", category: "Nhóm", categoryHelp: "Nhóm đã lưu trữ vẫn được giữ trên hồ sơ hiện có.", label: "Nhãn", variants: "Biến thể", initialVariant: "Biến thể đầu tiên", defaultVariant: "Biến thể mặc định", sku: "Mã SKU", price: "Giá bán", cost: "Giá vốn", costHelp: "Để trống khi chưa biết giá vốn.", currency: "Tiền tệ", duration: "Thời lượng (phút)", durationHelp: "Thời lượng mô tả; không tạo lịch hẹn.", attributes: "Thuộc tính biến thể", attributeName: "Tên thuộc tính", attributeValue: "Giá trị thuộc tính", addAttribute: "Thêm thuộc tính", addVariant: "Thêm biến thể", components: "Thành phần gói", componentHelp: "Mô tả thành phần đi kèm; không trừ tồn kho hoặc lượt dịch vụ.", chooseComponent: "Tìm sản phẩm và dịch vụ", quantity: "Số lượng", addComponent: "Thêm thành phần", remove: "Bỏ", none: "Không có", archive: "Lưu trữ", restore: "Khôi phục", up: "Di chuyển lên", down: "Di chuyển xuống", reload: "Tải dữ liệu hiện tại", conflict: "Hồ sơ đã thay đổi. Tải dữ liệu hiện tại trước khi lưu.", saved: "Đã lưu danh mục", categoriesSaved: "Đã lưu nhóm danh mục", minorHelp: "Nhập số tiền theo tiền tệ đã chọn. Đổi tiền tệ không quy đổi giá.", requiredPrice: "Nhập giá thực của biến thể đầu tiên.", images: "Ảnh danh mục riêng tư", active: "Đang dùng", archived: "Đã lưu trữ", name: "Tên", invalidAttributes: "Tên thuộc tính không được trống hoặc trùng nhau.", editVariant: "Sửa biến thể", cancel: "Hủy", save: "Lưu", unavailable: "Không khả dụng", defaultProtected: "Biến thể mặc định được giữ khi sản phẩm đang hoạt động.", reloadHelp: "Tải lại sẽ bỏ thay đổi chưa lưu trong trình sửa này.", units: "đơn vị",
};
export function getCatalogDictionary(locale: AppLocale) { return locale === "vi" ? vi : en; }
export type CatalogDictionary = typeof en;
