import type { AppLocale } from "./config";

const en = {
  currencyPending: "A currency conversion is pending. New deals and amount/currency edits are paused; other information can still be saved.",
  custom: { manage: "Manage properties", add: "Add property", label: "Property name", key: "Stable key", type: "Type", options: "Choices", addOption: "Add choice", removeOption: "Archive choice", showOnSheet: "Show in record", showOnTable: "Show in table by default", showOnFilter: "Show in filters", up: "Move up", down: "Move down", delete: "Delete property", coverage: "Records with a value", deleteHelp: "This hides the property and preserves its values for recovery during the rollback window. Save the property ID to recover it later.", password: "Current password", confirmation: "Type the stable key to confirm", recover: "Recover deleted property", recoverId: "Deleted property ID", empty: "No custom properties yet", optionsHelp: "Renaming a choice keeps existing values. Removing it archives the choice; existing values remain readable.", typeHelp: "A type change may be rejected when existing values are incompatible.", saved: "Properties saved", yes: "Yes", no: "No", types: { text: "Text", long_text: "Long text", number: "Number", date: "Date", checkbox: "Checkbox", select: "Choice", url: "URL", email: "Email", phone: "Phone", user: "Member" } },
  views: { title: "Saved views", add: "Save current view", name: "View name", shared: "Shared with workspace", private: "Private", mine: "My views", workspace: "Workspace views", update: "Replace with current settings", rename: "Rename view", delete: "Delete view", deleteConfirm: "Delete this saved view? Records are not affected.", empty: "No saved views", description: "Save search, filters, sorting, and visible columns. Only the creator can change a view.", changed: "Unsaved view changes" },
  activity: { add: "Add activity", type: "Activity type", subject: "Subject", content: "Notes", occurredAt: "Occurred at", dueAt: "Due at", completedAt: "Completed at", author: "Author", more: "Load older activity", complete: "Complete task", reopen: "Reopen task", saved: "Activity saved", empty: "No activity in this view", filter: "Activity filter", stageChange: "Stage changed", reassign: "Reassign owner", reassignDescription: "Apply this owner to the selected records only.", unavailableOwner: "Owner no longer available", types: { note: "Note", call: "Call", meeting: "Meeting", task: "Task", stage_change: "Stage change" }, filters: { all: "All", history: "History", notes: "Notes", calls: "Calls", meetings: "Meetings", upcoming: "Upcoming", done: "Done" } },
  company: "Companies", contact: "Contacts", deal: "Deals", add: "Add record", edit: "Edit", save: "Save", cancel: "Cancel", close: "Close", search: "Search", filters: "Filters", columns: "Columns", active: "Active", archived: "Archived", archive: "Archive", restore: "Restore", selected: "selected", select: "Select", selectPage: "Select this page", clear: "Clear", previous: "Previous", next: "Next", page: "Page", pageSize: "Rows per page", total: "records", empty: "No matching records", loading: "Loading…", error: "Unable to complete this action. Please try again.", conflict: "This change conflicts with an existing record or relationship.", invalid: "Check the highlighted fields and try again.", missing: "Record not found", retry: "Try again", details: "Details", activities: "Activity", fields: "Properties", related: "Related records", none: "None", apply: "Apply", sort: "Sort by", asc: "Ascending", desc: "Descending", navigation: "Main navigation", skip: "Skip to content", saved: "Saved", archiveConfirm: "Archive the selected records? They can be restored later.", restoreConfirm: "Restore the selected records?", partial: "Some records could not be changed. Refresh and review the selection.", confirm: "Confirm", required: "Required", noActivity: "No recorded activity", currencyHelp: "Amount in the currency’s smallest unit (for example, cents for USD).", invalidQuery: "This list link contains invalid parameters.", reset: "Reset list", chooseCompany: "Search for a company", chooseOwner: "Choose an owner",
  labels: { name: "Name", firstName: "First name", lastName: "Last name", domain: "Domain", website: "Website", description: "Description", industry: "Industry", city: "City", countryCode: "Country code", phone: "Phone", email: "Email", title: "Job title", company: "Company", companyId: "Company", owner: "Owner", ownerMembershipId: "Owner", stage: "Stage", stageId: "Stage", amount: "Amount", amountMinor: "Amount (smallest unit)", currency: "Currency", expectedCloseAt: "Expected close", closedReason: "Close reason", createdAt: "Created", updatedAt: "Updated", lastActivityAt: "Last activity", archivedAt: "Archived", closedAt: "Closed", stageChangedAt: "Stage changed" },
  stages: { "demo-booked": "Demo booked", "qualified-to-buy": "Qualified to buy", "unqualified-to-buy": "Unqualified to buy", "decision-maker-bought-in": "Decision maker bought in", "contract-sent": "Contract sent", "closed-won": "Closed won", "closed-lost": "Closed lost" },
};
export type CrmDictionary = typeof en;
const vi: CrmDictionary = {
  currencyPending: "Đang có tác vụ quy đổi tiền tệ. Tạm dừng tạo cơ hội và sửa giá trị/tiền tệ; vẫn có thể lưu thông tin khác.",
  custom: { manage: "Quản lý thuộc tính", add: "Thêm thuộc tính", label: "Tên thuộc tính", key: "Khóa cố định", type: "Loại", options: "Các lựa chọn", addOption: "Thêm lựa chọn", removeOption: "Lưu trữ lựa chọn", showOnSheet: "Hiện trong bản ghi", showOnTable: "Hiện mặc định trong bảng", showOnFilter: "Hiện trong bộ lọc", up: "Di chuyển lên", down: "Di chuyển xuống", delete: "Xóa thuộc tính", coverage: "Bản ghi đã có giá trị", deleteHelp: "Thuộc tính sẽ bị ẩn; giá trị được giữ để khôi phục trong thời hạn hoàn tác. Lưu mã thuộc tính để khôi phục sau này.", password: "Mật khẩu hiện tại", confirmation: "Nhập khóa cố định để xác nhận", recover: "Khôi phục thuộc tính đã xóa", recoverId: "Mã thuộc tính đã xóa", empty: "Chưa có thuộc tính tùy chỉnh", optionsHelp: "Đổi tên lựa chọn vẫn giữ giá trị hiện có. Xóa sẽ lưu trữ lựa chọn; giá trị cũ vẫn đọc được.", typeHelp: "Đổi loại có thể bị từ chối nếu giá trị hiện có không tương thích.", saved: "Đã lưu thuộc tính", yes: "Có", no: "Không", types: { text: "Văn bản", long_text: "Văn bản dài", number: "Số", date: "Ngày", checkbox: "Ô đánh dấu", select: "Lựa chọn", url: "URL", email: "Email", phone: "Điện thoại", user: "Thành viên" } },
  views: { title: "Chế độ xem đã lưu", add: "Lưu chế độ xem hiện tại", name: "Tên chế độ xem", shared: "Chia sẻ với không gian làm việc", private: "Riêng tư", mine: "Chế độ xem của tôi", workspace: "Chế độ xem dùng chung", update: "Thay bằng thiết lập hiện tại", rename: "Đổi tên chế độ xem", delete: "Xóa chế độ xem", deleteConfirm: "Xóa chế độ xem này? Các bản ghi không bị ảnh hưởng.", empty: "Chưa có chế độ xem đã lưu", description: "Lưu tìm kiếm, bộ lọc, cách sắp xếp và cột hiển thị. Chỉ người tạo được chỉnh sửa chế độ xem.", changed: "Thiết lập chế độ xem chưa được lưu" },
  activity: { add: "Thêm hoạt động", type: "Loại hoạt động", subject: "Tiêu đề", content: "Nội dung", occurredAt: "Thời điểm diễn ra", dueAt: "Hạn hoàn thành", completedAt: "Đã hoàn thành lúc", author: "Người tạo", more: "Tải hoạt động cũ hơn", complete: "Hoàn thành công việc", reopen: "Mở lại công việc", saved: "Đã lưu hoạt động", empty: "Chưa có hoạt động trong mục này", filter: "Lọc hoạt động", stageChange: "Đổi giai đoạn", reassign: "Đổi người phụ trách", reassignDescription: "Chỉ áp dụng người phụ trách cho các bản ghi đã chọn.", unavailableOwner: "Người phụ trách không còn hoạt động", types: { note: "Ghi chú", call: "Cuộc gọi", meeting: "Cuộc họp", task: "Công việc", stage_change: "Đổi giai đoạn" }, filters: { all: "Tất cả", history: "Lịch sử", notes: "Ghi chú", calls: "Cuộc gọi", meetings: "Cuộc họp", upcoming: "Sắp tới", done: "Đã xong" } },
  company: "Công ty", contact: "Liên hệ", deal: "Cơ hội", add: "Thêm bản ghi", edit: "Chỉnh sửa", save: "Lưu", cancel: "Hủy", close: "Đóng", search: "Tìm kiếm", filters: "Bộ lọc", columns: "Cột hiển thị", active: "Đang hoạt động", archived: "Đã lưu trữ", archive: "Lưu trữ", restore: "Khôi phục", selected: "đã chọn", select: "Chọn", selectPage: "Chọn trang này", clear: "Bỏ chọn", previous: "Trước", next: "Sau", page: "Trang", pageSize: "Số dòng mỗi trang", total: "bản ghi", empty: "Không có bản ghi phù hợp", loading: "Đang tải…", error: "Không thể hoàn tất thao tác. Vui lòng thử lại.", conflict: "Thay đổi xung đột với bản ghi hoặc liên kết hiện có.", invalid: "Kiểm tra các trường được đánh dấu rồi thử lại.", missing: "Không tìm thấy bản ghi", retry: "Thử lại", details: "Chi tiết", activities: "Hoạt động", fields: "Thuộc tính", related: "Bản ghi liên quan", none: "Không có", apply: "Áp dụng", sort: "Sắp xếp theo", asc: "Tăng dần", desc: "Giảm dần", navigation: "Điều hướng chính", skip: "Đến nội dung", saved: "Đã lưu", archiveConfirm: "Lưu trữ các bản ghi đã chọn? Bạn có thể khôi phục sau.", restoreConfirm: "Khôi phục các bản ghi đã chọn?", partial: "Một số bản ghi chưa được thay đổi. Hãy tải lại và kiểm tra lựa chọn.", confirm: "Xác nhận", required: "Bắt buộc", noActivity: "Chưa có hoạt động được ghi nhận", currencyHelp: "Số tiền theo đơn vị nhỏ nhất của tiền tệ (ví dụ: cent với USD).", invalidQuery: "Liên kết danh sách chứa tham số không hợp lệ.", reset: "Đặt lại danh sách", chooseCompany: "Tìm công ty", chooseOwner: "Chọn người phụ trách",
  labels: { name: "Tên", firstName: "Tên", lastName: "Họ", domain: "Tên miền", website: "Trang web", description: "Mô tả", industry: "Ngành", city: "Thành phố", countryCode: "Mã quốc gia", phone: "Điện thoại", email: "Email", title: "Chức danh", company: "Công ty", companyId: "Công ty", owner: "Người phụ trách", ownerMembershipId: "Người phụ trách", stage: "Giai đoạn", stageId: "Giai đoạn", amount: "Giá trị", amountMinor: "Giá trị (đơn vị nhỏ nhất)", currency: "Tiền tệ", expectedCloseAt: "Ngày chốt dự kiến", closedReason: "Lý do kết thúc", createdAt: "Ngày tạo", updatedAt: "Cập nhật", lastActivityAt: "Hoạt động gần nhất", archivedAt: "Ngày lưu trữ", closedAt: "Ngày chốt", stageChangedAt: "Đổi giai đoạn" },
  stages: { "demo-booked": "Đã hẹn demo", "qualified-to-buy": "Đủ điều kiện mua", "unqualified-to-buy": "Chưa đủ điều kiện mua", "decision-maker-bought-in": "Người quyết định đồng ý", "contract-sent": "Đã gửi hợp đồng", "closed-won": "Thành công", "closed-lost": "Thất bại" },
};
export function getCrmDictionary(locale: AppLocale): CrmDictionary { return locale === "vi" ? vi : en; }
