import type { AppLocale } from "./config";

const en = {
  title: "Reports", description: "Sales, customers, leads and service operations use one reconciled definition.", from: "From", to: "To", mine: "Mine", everyone: "Everyone", specificScope: "Member or branch", memberScope: "Member", branchScope: "Branch", apply: "Apply", export: "Export Excel", noExport: "Your profile can view this report but cannot export it.",
  orderValue: "Completed order value", grossProfit: "Gross profit", collections: "Net collection", receivable: "Current receivable", averageOrder: "Average order", repeat: "30-day repeat rate", conversion: "Lead cohort conversion", comparison: "Previous period", goal: "Revenue goal", noBasis: "No basis", insufficientCost: "Insufficient cost data", costCoverage: "Cost coverage", excluded: "Orders in other currencies are excluded", orders: "Order detail", source: "Source", recorder: "Recorded by", contact: "Contact", completed: "Completed", beforeTax: "Before tax", tax: "Tax", cost: "Frozen cost", empty: "No matching orders", work: "Work and support", overdueTasks: "Open overdue tasks", taskOnTime: "Tasks completed on time", overdueTickets: "Open overdue tickets", ticketOnTime: "Tickets resolved on time", responseTime: "Average first response", resolutionTime: "Average resolution", minutes: "minutes", customers: "Customers", buyingContacts: "Buying contacts", totalPurchase: "Total purchase", demographics: "Customer demographics", age: "Age", gender: "Gender", count: "Count", saveGoal: "Save goal", goalAmount: "Goal amount", saved: "Saved", error: "Unable to load or save the report.", filters: "Filters", allSources: "All sources", allRecorders: "All recorders", queryEvidence: "Local query evidence", statements: "statements", rowsRead: "rows read",
};
const vi: typeof en = {
  title: "Báo cáo", description: "Bán hàng, khách hàng, tiềm năng và vận hành dùng chung một định nghĩa đối soát.", from: "Từ ngày", to: "Đến ngày", mine: "Của tôi", everyone: "Tất cả", specificScope: "Nhân viên hoặc chi nhánh", memberScope: "Nhân viên", branchScope: "Chi nhánh", apply: "Áp dụng", export: "Xuất Excel", noExport: "Hồ sơ quyền của bạn được xem báo cáo nhưng không được xuất.",
  orderValue: "Giá trị đơn hoàn thành", grossProfit: "Lợi nhuận gộp", collections: "Thu ròng", receivable: "Công nợ hiện tại", averageOrder: "Giá trị đơn trung bình", repeat: "Tỷ lệ mua lại 30 ngày", conversion: "Chuyển đổi nhóm lead", comparison: "Kỳ liền trước", goal: "Mục tiêu doanh thu", noBasis: "Chưa có cơ sở", insufficientCost: "Chưa đủ dữ liệu giá vốn", costCoverage: "Bao phủ giá vốn", excluded: "Đơn khác tiền tệ báo cáo không được cộng vào tổng", orders: "Chi tiết đơn hàng", source: "Nguồn", recorder: "Người ghi nhận", contact: "Liên hệ", completed: "Hoàn thành", beforeTax: "Trước thuế", tax: "Thuế", cost: "Giá vốn đã chốt", empty: "Không có đơn phù hợp", work: "Công việc và hỗ trợ", overdueTasks: "Nhiệm vụ đang quá hạn", taskOnTime: "Nhiệm vụ đúng hạn", overdueTickets: "Ticket đang quá hạn", ticketOnTime: "Ticket đúng hạn", responseTime: "Phản hồi đầu trung bình", resolutionTime: "Xử lý trung bình", minutes: "phút", customers: "Khách hàng", buyingContacts: "Khách đang mua", totalPurchase: "Tổng mua", demographics: "Nhân khẩu học khách hàng", age: "Tuổi", gender: "Giới tính", count: "Số lượng", saveGoal: "Lưu mục tiêu", goalAmount: "Số tiền mục tiêu", saved: "Đã lưu", error: "Không thể tải hoặc lưu báo cáo.", filters: "Bộ lọc", allSources: "Mọi nguồn", allRecorders: "Mọi người ghi nhận", queryEvidence: "Bằng chứng truy vấn local", statements: "câu lệnh", rowsRead: "dòng đã đọc",
};
export function getReportDictionary(locale: AppLocale) { return locale === "vi" ? vi : en; }
