import type {AppLocale} from "./config";

const en={
 calendar:"Calendar",appointments:"Appointments",newAppointment:"Add appointment",
 calendarSubtitle:"Schedule and manage customer appointments.",createAppointmentDescription:"Enter the appointment time in your business time zone.",appointmentDetails:"Appointment details",
 assignment:"Assignment",calendarView:"Calendar view",day:"Day",week:"Week",month:"Month",today:"Today",previousPeriod:"Previous period",nextPeriod:"Next period",status:"Status",
 tasks:"My tasks",tickets:"Tickets",subject:"Subject",description:"Description",startsAt:"Starts",endsAt:"Ends",dueAt:"Due",assignee:"Assignee",participants:"Participants",priority:"Priority",source:"Source",create:"Create",complete:"Complete",cancel:"Cancel",resolve:"Resolve",reopen:"Reopen",respond:"Record public response",response:"Customer response",reason:"Reason",allowConflict:"Save despite conflict",conflict:"This appointment overlaps another participant booking.",reminder:"Reminder",minutesBefore:"minutes before",browserNotifications:"Browser notifications",enableBrowser:"Enable browser notifications",permissionDenied:"Browser notification permission was denied. In-app reminders remain available.",noItems:"No items in this view.",overdue:"Overdue",lateHistory:"Was overdue",open:"Open",completed:"Completed",resolved:"Resolved",scheduled:"Scheduled",cancelled:"Cancelled",all:"All",mine:"Mine",loading:"Loading…",saved:"Saved.",errors:"Unable to complete this action. Reload and try again.",priorities:{low:"Low",normal:"Normal",high:"High",urgent:"Urgent"}
};
const vi:typeof en={
 calendar:"Lịch",appointments:"Lịch hẹn",newAppointment:"Thêm lịch hẹn",
 calendarSubtitle:"Đặt lịch, quản lý thông tin lịch hẹn của khách hàng.",createAppointmentDescription:"Nhập thời gian lịch hẹn theo múi giờ của doanh nghiệp.",appointmentDetails:"Thông tin lịch hẹn",
 assignment:"Phân công",calendarView:"Chế độ xem lịch",day:"Ngày",week:"Tuần",month:"Tháng",today:"Hôm nay",previousPeriod:"Khoảng thời gian trước",nextPeriod:"Khoảng thời gian tiếp theo",status:"Trạng thái",
 tasks:"Việc của tôi",tickets:"Ticket",subject:"Tiêu đề",description:"Mô tả",startsAt:"Bắt đầu",endsAt:"Kết thúc",dueAt:"Hạn",assignee:"Người phụ trách",participants:"Người tham gia",priority:"Ưu tiên",source:"Nguồn",create:"Tạo",complete:"Hoàn thành",cancel:"Hủy",resolve:"Giải quyết",reopen:"Mở lại",respond:"Ghi nhận phản hồi công khai",response:"Phản hồi khách hàng",reason:"Lý do",allowConflict:"Vẫn lưu lịch trùng",conflict:"Lịch này trùng với lịch khác của người tham gia.",reminder:"Nhắc việc",minutesBefore:"phút trước",browserNotifications:"Thông báo trình duyệt",enableBrowser:"Bật thông báo trình duyệt",permissionDenied:"Trình duyệt đã từ chối quyền thông báo. Nhắc việc trong ứng dụng vẫn hoạt động.",noItems:"Chưa có dữ liệu trong mục này.",overdue:"Đang quá hạn",lateHistory:"Đã từng quá hạn",open:"Đang mở",completed:"Đã hoàn thành",resolved:"Đã giải quyết",scheduled:"Mới",cancelled:"Đã hủy",all:"Tất cả",mine:"Của tôi",loading:"Đang tải…",saved:"Đã lưu.",errors:"Không thể hoàn tất thao tác. Hãy tải lại và thử lại.",priorities:{low:"Thấp",normal:"Bình thường",high:"Cao",urgent:"Khẩn cấp"}
};
export const getSchedulingDictionary=(locale:AppLocale)=>locale==="vi"?vi:en;
