import {and,desc,eq,sql} from "drizzle-orm";
import type {AppDatabase} from "@/lib/db/database";
import {serviceEntitlement,entitlementMovement,user} from "@/lib/db/schema";
import type {RequestContext} from "@/lib/http/request-context";
import {HttpError} from "@/lib/http/http-errors";
import {actionGuard,requirePermission} from "../permissions/permission-policy";
import {commandDate,condition,conflict,fingerprint,salesError} from "../orders/order-operations";
import {entitlementRecordInputSchema,entitlementListInputSchema,entitlementResultOutputSchema,type EntitlementRecordInput} from "./entitlement-contract";
export class EntitlementService{
 constructor(private readonly db:AppDatabase){}
 private serialize(r:typeof serviceEntitlement.$inferSelect){return{...r,expiresAt:r.expiresAt?.toISOString()??null,createdAt:r.createdAt.toISOString()};}
 async byId(context:RequestContext,id:string){await requirePermission(this.db,context);const row=await this.db.select().from(serviceEntitlement).where(eq(serviceEntitlement.id,id)).get();if(!row)throw new HttpError(404,"not_found","Entitlement not found");return this.serialize(row);}
 async list(context:RequestContext,raw:{contactId?:string;orderId?:string;pageSize?:number}={}){await requirePermission(this.db,context);const input=entitlementListInputSchema.parse(raw);const rows=await this.db.select().from(serviceEntitlement).where(and(input.contactId?eq(serviceEntitlement.contactId,input.contactId):undefined,input.orderId?eq(serviceEntitlement.orderId,input.orderId):undefined)).orderBy(desc(serviceEntitlement.createdAt),desc(serviceEntitlement.id)).limit(input.pageSize);return{rows:rows.map(r=>this.serialize(r))};}
 async record(context:RequestContext,id:string,raw:EntitlementRecordInput){const input=entitlementRecordInputSchema.parse(raw),digest=await fingerprint(id,input);await requirePermission(this.db,context);const replay=async()=>{const p=await this.db.select().from(entitlementMovement).where(eq(entitlementMovement.operationKey,input.operationKey)).get();if(!p)return null;if(p.entitlementId!==id||p.fingerprint!==digest)conflict();return entitlementResultOutputSchema.parse(JSON.parse(p.resultJson));};const previous=await replay();if(previous)return previous;
  const permission=input.kind==="use"?"entitlement.use" as const:"entitlement.restore" as const;await requirePermission(this.db,context,[permission]);const row=await this.byId(context,id);if(row.revision!==input.expectedRevision||row.revoked>0)conflict();if(input.kind==="use"&&row.remaining<input.quantity||input.kind==="restore"&&row.used<input.quantity)conflict("Session balance is insufficient");const date=await commandDate(this.db,context,input);const expires=row.expiresAt?Date.parse(row.expiresAt):null;if(input.kind==="use"&&expires!==null&&expires<=date.now.getTime())conflict("Entitlement expired");
  const sign=input.kind==="use"?-1:1,remaining=row.remaining+sign*input.quantity,used=row.used-sign*input.quantity;const auth=actionGuard(this.db,context,[permission,...date.permissions]),guard=condition(this.db,and(date.predicate,sql`exists(select 1 from service_entitlement e join sales_order o on o.id=e.order_id where e.id=${id} and e.revision=${input.expectedRevision} and o.state='completed' and (e.expires_at is null or e.expires_at>unixepoch('subsec')*1000 or ${input.kind}='restore'))`)!);
  try{await this.db.batch([auth.begin,guard.begin,this.db.update(serviceEntitlement).set({remaining,used,revision:row.revision+1}).where(eq(serviceEntitlement.id,id)),this.db.insert(entitlementMovement).values({id:crypto.randomUUID(),entitlementId:id,kind:input.kind,quantity:input.quantity,operationKey:input.operationKey,fingerprint:digest,resultJson:JSON.stringify({id,operationKey:input.operationKey,revision:row.revision+1,remaining,used}),actorId:context.userId,reason:input.reason,businessDate:date.date,timeZone:date.timeZone,createdAt:date.now}),guard.end,auth.end]);return{id,operationKey:input.operationKey,revision:row.revision+1,remaining,used};}catch(e){const p=await replay();if(p)return p;salesError(e);}
 }
 async history(context:RequestContext,id:string){await requirePermission(this.db,context);const rows=await this.db.select({movement:entitlementMovement,actorName:user.name}).from(entitlementMovement).leftJoin(user,eq(user.id,entitlementMovement.actorId)).where(eq(entitlementMovement.entitlementId,id)).orderBy(desc(entitlementMovement.createdAt),desc(entitlementMovement.id)).limit(100);return{rows:rows.map(({movement:{fingerprint:_f,resultJson:_r,...r},actorName})=>({...r,actorName,createdAt:r.createdAt.toISOString()}))};}
}
