"use client";

import { useEffect, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { RecordLink } from "@/components/crm/record-sheet/record-link";
import { crmRequest } from "@/components/crm/record-types";
import { selectClass } from "@/components/crm/list-toolbar";
import { formatMinor } from "@/modules/currency/currency-catalog";
import type { DashboardSummaryData } from "@/modules/dashboard/dashboard-contracts";
import type { AppLocale } from "@/i18n/config";
import { getCrmDictionary } from "@/i18n/crm-dictionary";
import { getCurrencyDictionary } from "@/i18n/currency-dictionary";

const panel = "min-w-0 rounded-lg border bg-background p-4 md:p-5";
export function DashboardSummary({ initialData, locale }: { initialData: DashboardSummaryData; locale: AppLocale }) {
  const labels = getCurrencyDictionary(locale); const crm = getCrmDictionary(locale);
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams();
  const scope = search.get("scope") === "everyone" ? "everyone" : "me";
  const [data, setData] = useState(initialData); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const [refresh, setRefresh] = useState(0);
  useEffect(() => { const update = () => setRefresh(value => value + 1); window.addEventListener("crm:invalidate", update); return () => window.removeEventListener("crm:invalidate", update); }, []);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError(false);
    crmRequest<DashboardSummaryData>(`/api/crm/dashboard?scope=${scope}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) setData(value); }).catch(() => { if (!controller.signal.aborted) setError(true); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [scope, refresh]);
  const money = (value: string | number | null, currency: string = data.reportingCurrency) => value === null ? "—" : formatMinor(value, currency, locale);
  const date = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeZone: "UTC" }).format(new Date(value)) : "—";
  const empty = <p className="py-4 text-sm text-muted-foreground">{labels.empty}</p>;
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{labels.dashboard}</h1><p className="mt-1 text-sm text-muted-foreground">{labels.description}</p></div><label className="flex flex-col gap-1 text-sm">{labels.scope}<select aria-label={labels.scope} className={selectClass} value={scope} onChange={event => { const next = new URLSearchParams(search.toString()); next.set("scope", event.target.value); router.replace(`${pathname}?${next}`, { scroll: false }); }}><option value="me">{labels.me}</option><option value="everyone">{labels.everyone}</option></select></label></div>
    <p className="text-sm text-muted-foreground">{labels.current}: {data.reportingCurrency} · {labels.version} {data.activeVersion}</p>
    <div aria-live="polite">{loading && <p role="status">{labels.loading}</p>}{error && <div role="alert" className="flex items-center gap-3 text-destructive">{labels.error}<Button variant="outline" onClick={() => setRefresh(value => value + 1)}>{labels.retry}</Button></div>}</div>
    <div aria-busy={loading} className={loading || error || data.scope !== scope ? "invisible min-h-[40rem]" : "space-y-6"}>
      {data.unconverted.count > 0 && <p role="status" className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-4 text-sm">{labels.excluded}: <strong>{data.unconverted.count}</strong> ({data.unconverted.currencies.join(", ")}).</p>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[labels.pipeline, data.pipeline.totalMinor, data.pipeline.totalDeals], [labels.won, data.wonThisMonth.valueMinor, data.wonThisMonth.count], [labels.previousWon, data.wonPrevMonth.valueMinor, data.wonPrevMonth.count], [labels.closing, data.closingThisMonthTotal.valueMinor, data.closingThisMonthTotal.count]].map(([title, amount, count]) => <section className={panel} key={title}><h2 className="text-sm text-muted-foreground">{title}</h2><p className="mt-2 break-words text-xl font-semibold tabular-nums">{money(String(amount))}</p><p className="mt-1 text-sm text-muted-foreground">{count} {labels.count.toLowerCase()}</p></section>)}</div>
      <section className={panel}><h2 className="mb-4 font-semibold">{labels.pipeline}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{data.pipeline.stages.map(stage => <div key={stage.stageId} className="rounded-md bg-muted/50 p-3"><h3 className="text-sm">{crm.stages[stage.stageId as keyof typeof crm.stages]}</h3><p className="mt-2 break-words font-semibold tabular-nums">{money(stage.valueMinor)}</p><p className="text-sm text-muted-foreground">{stage.count} {labels.count.toLowerCase()}</p></div>)}</div></section>
      <section className={panel}><h2 className="mb-4 font-semibold">{labels.performance}</h2><dl className="grid gap-4 sm:grid-cols-3"><div><dt className="text-sm text-muted-foreground">{labels.winRate}</dt><dd className="text-xl font-semibold">{data.performance.winRate === null ? "—" : new Intl.NumberFormat(locale, { style: "percent", maximumFractionDigits: 1 }).format(data.performance.winRate)}</dd><dd className="text-sm text-muted-foreground">{data.performance.wins} {labels.wins} · {data.performance.losses} {labels.losses}</dd></div><div><dt className="text-sm text-muted-foreground">{labels.averageDeal}</dt><dd className="break-words text-xl font-semibold">{money(data.performance.avgDealMinor)}</dd></div><div><dt className="text-sm text-muted-foreground">{labels.cycle}</dt><dd className="text-xl font-semibold">{data.performance.avgCycleDays === null ? "—" : `${new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(data.performance.avgCycleDays)} ${labels.days}`}</dd></div></dl></section>
      <section className={panel}><h2 className="mb-4 font-semibold">{labels.trend}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">{labels.month}</th><th className="p-2 text-right">{labels.created}</th><th className="p-2 text-right">{labels.wonValue}</th></tr></thead><tbody>{data.trend.map(point => <tr key={point.month} className="border-b last:border-0"><th className="whitespace-nowrap p-2 font-normal">{new Intl.DateTimeFormat(locale, { month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${point.month}-01T00:00:00Z`))}</th><td className="whitespace-nowrap p-2 text-right tabular-nums">{money(point.createdMinor)}</td><td className="whitespace-nowrap p-2 text-right tabular-nums">{money(point.wonMinor)}</td></tr>)}</tbody></table></div></section>
      <section className={panel}><h2 className="mb-4 font-semibold">{labels.biggest}</h2>{data.biggestOpen.length === 0 ? empty : <ul className="divide-y">{data.biggestOpen.map(deal => <li key={deal.id} className="flex flex-wrap justify-between gap-3 py-3"><div><RecordLink entity="deal" id={deal.id}>{deal.name}</RecordLink><p className="text-sm"><RecordLink entity="company" id={deal.company.id}>{deal.company.name}</RecordLink> · {deal.owner.name}</p><p className="text-sm text-muted-foreground">{crm.stages[deal.stageId as keyof typeof crm.stages]} · {labels.closeDate}: {date(deal.expectedCloseAt)}</p></div><div className="text-sm"><p>{labels.reportingAmount}: <strong>{money(deal.baseAmountMinor)}</strong></p><p className="text-muted-foreground">{labels.original}: {money(deal.amountMinor, deal.currency)}</p></div></li>)}</ul>}</section>
      <div className="grid gap-4 lg:grid-cols-2"><section className={panel}><h2 className="mb-4 font-semibold">{labels.overdue}</h2>{data.overdueTasks.length === 0 ? empty : <ul className="divide-y">{data.overdueTasks.map(task => <li key={task.id} className="space-y-1 py-3"><p className="font-medium">{task.subject || crm.activity.types.task}</p><p className="text-sm text-destructive">{date(task.dueAt)}</p><div className="flex flex-wrap gap-2 text-sm">{task.deal && <RecordLink entity="deal" id={task.deal.id}>{task.deal.name}</RecordLink>}{task.company && <RecordLink entity="company" id={task.company.id}>{task.company.name}</RecordLink>}</div></li>)}</ul>}</section><section className={panel}><h2 className="mb-4 font-semibold">{labels.recent}</h2>{data.recentActivity.length === 0 ? empty : <ul className="divide-y">{data.recentActivity.map(activity => <li key={activity.id} className="space-y-1 py-3"><p className="font-medium">{activity.subject || crm.activity.types[activity.type as keyof typeof crm.activity.types]}</p>{activity.content && <p className="line-clamp-2 break-words text-sm">{activity.content}</p>}<p className="text-sm text-muted-foreground">{activity.author.name} · {date(activity.createdAt)}</p><div className="flex flex-wrap gap-2 text-sm">{activity.deal && <RecordLink entity="deal" id={activity.deal.id}>{activity.deal.name}</RecordLink>}{activity.company && <RecordLink entity="company" id={activity.company.id}>{activity.company.name}</RecordLink>}</div></li>)}</ul>}</section></div>
    </div>
  </div>;
}
