import {and,eq} from "drizzle-orm";
import type {AppDatabase} from "@/lib/db/database";
import {webformConfig} from "@/lib/db/schema";
import type {RequestContext} from "@/lib/http/request-context";
import {HttpError} from "@/lib/http/http-errors";
import {actionGuard,authorizedBatch,permissionError,requirePermission} from "../permissions/permission-policy";
import {normalizeEmail} from "../shared/service-utils";
import {normalizeLeadPhone} from "../leads/lead-normalization";
import type {WebformCreate,WebformUpdate} from "./webform-contract";

const encoder=new TextEncoder();
async function digest(value:string){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(value)))].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function safeEqual(left:string,right:string){if(left.length!==right.length)return false;let mismatch=0;for(let index=0;index<left.length;index++)mismatch|=left.charCodeAt(index)^right.charCodeAt(index);return mismatch===0;}
function stable(value:Record<string,unknown>){return JSON.stringify(Object.keys(value).sort().reduce<Record<string,unknown>>((out,key)=>(out[key]=value[key],out),{}));}
function text(value:unknown,max:number){if(value===null||value===undefined)return null;const result=String(value).trim();return result?result.slice(0,max):null;}

export class WebformService{
 constructor(private readonly db:AppDatabase){}
 async list(context:RequestContext){await requirePermission(this.db,context,["webform.manage"],true);return this.db.select().from(webformConfig).orderBy(webformConfig.name);}
 async create(context:RequestContext,input:WebformCreate){await requirePermission(this.db,context,["webform.manage"],true);this.validateMapping(input);if(input.entity==="lead"&&!await this.db.$client.prepare("SELECT id FROM lead_source WHERE id=? AND archived_at IS NULL").bind(input.source).first())throw new HttpError(400,"validation_failed","Lead source is unavailable");const id=crypto.randomUUID(),token=input.mode==="signed_system"?crypto.randomUUID()+crypto.randomUUID():null,now=new Date();await authorizedBatch(this.db,context,["webform.manage"],[this.db.insert(webformConfig).values({id,name:input.name,slug:input.slug,entity:input.entity,mode:input.mode,tokenHash:token?await digest(token):null,source:input.source,authorityMembershipId:context.membershipId,mappingJson:JSON.stringify(input.mapping),allowMissingRequired:input.mode==="signed_system"&&input.allowMissingRequired,rateLimitHour:input.rateLimitHour,active:true,revision:0,createdAt:now,updatedAt:now})]);return{id,token,revision:0};}
 async update(context:RequestContext,input:WebformUpdate){await requirePermission(this.db,context,["webform.manage"],true);this.validateMapping(input);const current=await this.db.select().from(webformConfig).where(eq(webformConfig.id,input.id)).get();if(!current||current.revision!==input.expectedRevision)throw new HttpError(409,"conflict","Webform changed before saving");if(current.mode!==input.mode||current.entity!==input.entity)throw new HttpError(400,"validation_failed","Webform mode and record type are immutable; create a new form to rotate credentials");if(input.entity==="lead"&&!await this.db.$client.prepare("SELECT id FROM lead_source WHERE id=? AND archived_at IS NULL").bind(input.source).first())throw new HttpError(400,"validation_failed","Lead source is unavailable");const guard=actionGuard(this.db,context,["webform.manage"],true);try{const[,rows]=await this.db.batch([guard.begin,this.db.update(webformConfig).set({name:input.name,slug:input.slug,source:input.source,mappingJson:JSON.stringify(input.mapping),allowMissingRequired:input.allowMissingRequired,rateLimitHour:input.rateLimitHour,active:input.active,revision:input.expectedRevision+1,updatedAt:new Date()}).where(and(eq(webformConfig.id,input.id),eq(webformConfig.revision,input.expectedRevision))).returning(),guard.end]);if(!rows.length)throw new HttpError(409,"conflict","Webform changed before saving");}catch(error){permissionError(error);}return{id:input.id,revision:input.expectedRevision+1};}
 async submit(slug:string,payload:Record<string,unknown>,headers:Headers,rawBody:string,now=new Date()){
  const form=await this.db.select().from(webformConfig).where(eq(webformConfig.slug,slug)).get();
  if(!form||!form.active)throw new HttpError(404,"not_found","Webform was not found");
  const submissionKey=headers.get("idempotency-key")?.trim();if(!submissionKey||submissionKey.length>255)throw new HttpError(400,"validation_failed","Idempotency-Key is required");
  if(form.mode==="signed_system")await this.verifySystem(form.tokenHash!,headers,rawBody,now);
  const fingerprint=await digest(stable(payload)),prior=await this.db.$client.prepare("SELECT fingerprint,record_id,missing_fields_json FROM webform_submission WHERE form_id=? AND submission_key=?").bind(form.id,submissionKey).first<{fingerprint:string;record_id:string;missing_fields_json:string}>();
  if(prior){if(prior.fingerprint!==fingerprint)throw new HttpError(409,"conflict","Submission key was already used");return{recordId:prior.record_id,replayed:true,missingFields:JSON.parse(prior.missing_fields_json) as string[],entity:form.entity,source:form.source};}
  const mapping=JSON.parse(form.mappingJson) as Record<string,string>,mapped:Record<string,unknown>={};for(const [input,target] of Object.entries(mapping))if(payload[input]!==undefined)mapped[target]=payload[input];
  const required=form.entity==="lead"?["firstName"]:["subject"],missing=required.filter(key=>!text(mapped[key],300));
  if(missing.length&&!(form.mode==="signed_system"&&form.allowMissingRequired))throw new HttpError(400,"validation_failed",`Missing required fields: ${missing.join(", ")}`);
  const recordId=crypto.randomUUID(),client=headers.get("cf-connecting-ip")??"unknown",clientHash=await digest(client),bucket=Math.floor(now.getTime()/3_600_000),guardId=crypto.randomUUID();
  const statements=[
   this.db.$client.prepare("INSERT INTO webform_rate_bucket(form_id,bucket,client_hash,count) VALUES(?,?,?,1) ON CONFLICT(form_id,bucket,client_hash) DO UPDATE SET count=count+1").bind(form.id,bucket,clientHash),
   this.db.$client.prepare("INSERT INTO operation_condition_guard(id,authorized) SELECT ?,CASE WHEN EXISTS(SELECT 1 FROM webform_config f JOIN singleton_membership m ON m.user_id=f.authority_membership_id WHERE f.id=? AND f.active=1 AND m.status='active' AND (?!='lead' OR EXISTS(SELECT 1 FROM module_setting WHERE entity='lead' AND enabled=1)) AND (m.role='owner' OR EXISTS(SELECT 1 FROM membership_access ma JOIN access_grant g ON g.profile_id=ma.profile_id WHERE ma.membership_id=m.user_id AND g.permission=?))) AND (SELECT count FROM webform_rate_bucket WHERE form_id=? AND bucket=? AND client_hash=?)<=? THEN 1 ELSE 0 END").bind(guardId,form.id,form.entity,form.entity==="lead"?"lead.create":"ticket.create",form.id,bucket,clientHash,form.rateLimitHour),
  ];
  if(form.entity==="lead")statements.push(this.db.$client.prepare("INSERT INTO lead(id,first_name,last_name,email,phone,normalized_email,normalized_phone,title,description,source_id,status_id,owner_membership_id,creator_user_id,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,\'new\',?,?,0,?,?)").bind(recordId,text(mapped.firstName,200)??"[missing:firstName]",text(mapped.lastName,200),text(mapped.email,320),text(mapped.phone,80),normalizeEmail(text(mapped.email,320)),normalizeLeadPhone(text(mapped.phone,80)),text(mapped.title,200),text(mapped.description,10000),form.source,form.authorityMembershipId,form.authorityMembershipId,now.getTime(),now.getTime()));
  else statements.push(this.db.$client.prepare("UPDATE ticket_sequence SET next_number=next_number+1 WHERE id='tickets'"),this.db.$client.prepare("INSERT INTO ticket(id,number,subject,description,priority,category,source,creator_user_id,status,current_cycle,revision,created_at,updated_at) VALUES(?,(SELECT next_number-1 FROM ticket_sequence WHERE id='tickets'),?,?,?,?,?,?,'open',1,0,?,?)").bind(recordId,text(mapped.subject,300)??"[missing:subject]",text(mapped.description,10000),["low","normal","high","urgent"].includes(String(mapped.priority))?String(mapped.priority):"normal",text(mapped.category,120),form.source,form.authorityMembershipId,now.getTime(),now.getTime()),this.db.$client.prepare("INSERT INTO ticket_cycle(ticket_id,cycle,opened_at,opened_by,overdue_breached) VALUES(?,1,?,?,0)").bind(recordId,now.getTime(),form.authorityMembershipId),this.db.$client.prepare("INSERT INTO ticket_event(id,ticket_id,cycle,action,actor_id,operation_key,fingerprint,result_json,created_at) VALUES(?,?,1,'created',?,?,?,?,?)").bind(crypto.randomUUID(),recordId,form.authorityMembershipId,`webform:${form.id}:${submissionKey}`,fingerprint,JSON.stringify({id:recordId,status:"open",revision:0}),now.getTime()));
  statements.push(this.db.$client.prepare("INSERT INTO webform_submission(id,form_id,submission_key,fingerprint,client_hash,record_id,missing_fields_json,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),form.id,submissionKey,fingerprint,clientHash,recordId,JSON.stringify(missing),now.getTime()),this.db.$client.prepare("DELETE FROM operation_condition_guard WHERE id=?").bind(guardId));
  try{await this.db.$client.batch(statements);}catch(error){if(error instanceof Error&&error.message.includes("operation_conflict"))throw new HttpError(429,"rate_limited","Webform rate limit or authority check failed");if(error instanceof Error&&error.message.includes("UNIQUE")){const raced=await this.db.$client.prepare("SELECT fingerprint,record_id,missing_fields_json FROM webform_submission WHERE form_id=? AND submission_key=?").bind(form.id,submissionKey).first<{fingerprint:string;record_id:string;missing_fields_json:string}>();if(raced?.fingerprint===fingerprint)return{recordId:raced.record_id,replayed:true,missingFields:JSON.parse(raced.missing_fields_json) as string[],entity:form.entity,source:form.source};throw new HttpError(409,"conflict","Submission key was already used");}throw error;}
  return{recordId,replayed:false,missingFields:missing,entity:form.entity,source:form.source};
 }
 private validateMapping(input:WebformCreate){const allowed=input.entity==="lead"?new Set(["firstName","lastName","email","phone","title","description"]):new Set(["subject","description","priority","category"]);if(Object.values(input.mapping).some(target=>!allowed.has(target)))throw new HttpError(400,"validation_failed","Mapping contains a field for another record type");}
 private async verifySystem(tokenHash:string,headers:Headers,rawBody:string,now:Date){const authorization=headers.get("authorization")??"",token=authorization.startsWith("Bearer ")?authorization.slice(7):"",timestamp=headers.get("x-webform-timestamp")??"",signature=headers.get("x-webform-signature")??"";if(!token||!safeEqual(await digest(token),tokenHash))throw new HttpError(401,"invalid_signature","System token is invalid");const millis=Number(timestamp);if(!Number.isFinite(millis)||Math.abs(now.getTime()-millis)>300_000)throw new HttpError(401,"invalid_signature","System timestamp is outside the allowed window");if(!safeEqual(await digest(`${token}.${timestamp}.${rawBody}`),signature))throw new HttpError(401,"invalid_signature","System signature is invalid");}
}
