"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { AppLocale } from "@/lib/i18n/config";
import { getCrmDictionary } from "@/lib/i18n/crm-dictionary";
import { getCatalogDictionary } from "@/lib/i18n/catalog-dictionary";
import type { ProductCategoryCatalog, ProductCategoryMutation } from "@/lib/services/catalog/product-category-contract";
import { invalidateCrm } from "@/lib/listing/invalidation";
import { crmRequest, requestError } from "../record-types";
type Change = ProductCategoryMutation extends infer T ? T extends { revision: number } ? Omit<T, "revision"> : never : never;
export function CatalogSettings({ initialData, locale }: { initialData: ProductCategoryCatalog; locale: AppLocale }) {
  const labels = getCatalogDictionary(locale), crm = getCrmDictionary(locale); const [catalog, setCatalog] = useState(initialData); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [stale, setStale] = useState(false); const [saved, setSaved] = useState(false);
  const disabled = busy || stale || !catalog.canManage;
  function discard(id: string) { setDrafts(current => { const next = { ...current }; delete next[id]; return next; }); }
  async function mutate(change: Change) { if (disabled) return; setBusy(true); setError(""); setSaved(false); try { setCatalog(await crmRequest<ProductCategoryCatalog>("/api/crm/product-categories", { method: "PATCH", body: JSON.stringify({ ...change, revision: catalog.revision }) })); if (change.action === "create") setName(""); if (change.action === "relabel") discard(change.id); setSaved(true); invalidateCrm("product"); } catch (reason) { setError(requestError(reason, crm)); setStale(reason instanceof Error && reason.message === "409"); } finally { setBusy(false); } }
  async function reload() { setBusy(true); try { setCatalog(await crmRequest<ProductCategoryCatalog>("/api/crm/product-categories")); setDrafts({}); setStale(false); setError(""); setSaved(false); } catch (reason) { setError(requestError(reason, crm)); } finally { setBusy(false); } }
  return <section className="mx-auto max-w-3xl space-y-5"><h1 className="text-2xl font-medium">{labels.categories}</h1><p className="text-sm text-muted-foreground">{labels.categoryHelp}</p>{error && <p role="alert" className="text-sm text-destructive">{stale ? labels.conflict : error}</p>}{saved && <p role="status">{labels.categoriesSaved}</p>}<form className="space-y-3 rounded-md border p-4" onSubmit={event => { event.preventDefault(); void mutate({ action: "create", label: name }); }}><label className="block space-y-1 text-sm">{labels.label}<Input required maxLength={100} value={name} disabled={disabled} onChange={event => setName(event.target.value)} /></label><div className="flex flex-wrap gap-2"><Button type="submit" disabled={disabled || !name.trim()}>{crm.add}</Button><Button type="button" variant="outline" disabled={busy} onClick={() => setName("")}>{crm.cancel}</Button></div></form><ol className="space-y-3">{catalog.categories.map((row, index) => <li key={row.id} className="space-y-3 rounded-md border p-4" data-category-id={row.id}><form className="space-y-3" onSubmit={event => { event.preventDefault(); void mutate({ action: "relabel", id: row.id, label: drafts[row.id] ?? row.label }); }}><Input aria-label={`${labels.label}: ${row.label}`} required maxLength={100} value={drafts[row.id] ?? row.label} disabled={disabled} onChange={event => { setDrafts(current => ({ ...current, [row.id]: event.target.value })); setSaved(false); }} />{row.archivedAt && <p className="text-xs text-muted-foreground">{labels.archived}</p>}<div className="flex flex-wrap gap-2"><Button size="sm" type="submit" disabled={disabled || drafts[row.id] === undefined}>{crm.save}</Button><Button size="sm" type="button" variant="outline" disabled={busy || drafts[row.id] === undefined} onClick={() => discard(row.id)}>{crm.cancel}</Button><Button size="sm" type="button" variant="outline" aria-label={`${labels.up}: ${row.label}`} disabled={disabled || index === 0} onClick={() => void mutate({ action: "reorder", id: row.id, beforeId: catalog.categories[index - 1]!.id })}>↑</Button><Button size="sm" type="button" variant="outline" aria-label={`${labels.down}: ${row.label}`} disabled={disabled || index === catalog.categories.length - 1} onClick={() => void mutate({ action: "reorder", id: row.id, beforeId: catalog.categories[index + 2]?.id ?? null })}>↓</Button><Button size="sm" type="button" variant="outline" disabled={disabled} onClick={() => void mutate({ action: row.archivedAt ? "restore" : "archive", id: row.id })}>{row.archivedAt ? labels.restore : labels.archive}</Button></div></form></li>)}</ol><p className="text-xs text-muted-foreground">{labels.reloadHelp}</p><Button variant="outline" disabled={busy} onClick={() => void reload()}>{labels.reload}</Button></section>;
}
