"use client";
import { useEffect, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Bookmark } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { captureSavedViewState, type SavedView } from "@/views/saved-view-contracts";
import type { EntityType } from "@/crm/list-state";
import type { CrmDictionary } from "@/i18n/crm-dictionary";
import { crmRequest, requestError } from "./record-types";

export function SavedViewsMenu({ entity, labels }: { entity: EntityType; labels: CrmDictionary }) {
  const router = useRouter(); const path = usePathname(); const search = useSearchParams();
  const [views, setViews] = useState<SavedView[]>([]); const [revision, setRevision] = useState(0); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<SavedView | "new" | null>(null); const [name, setName] = useState(""); const [shared, setShared] = useState(false); const [deleting, setDeleting] = useState<SavedView | null>(null);
  useEffect(() => { const controller = new AbortController(); setLoading(true); crmRequest<SavedView[]>(`/api/crm/saved-views?entity=${entity}`, { signal: controller.signal }).then(setViews).catch(() => { if (!controller.signal.aborted) setError(labels.error); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [entity, revision, labels]);
  const selected = views.find(view => view.id === search.get("view"));
  const changed = selected ? captureSavedViewState(entity, new URLSearchParams(search.toString())).query !== selected.state.query : false;
  async function mutate(method: string, id: string | null, body?: unknown) { setBusy(true); setError(""); try { const result = await crmRequest<SavedView>(`/api/crm/saved-views${id ? `/${id}` : ""}`, { method, ...(body ? { body: JSON.stringify(body) } : {}) }); setRevision(value => value + 1); setEditing(null); setDeleting(null); if (method === "POST") { const next = new URLSearchParams(search.toString()); next.set("view", result.id); router.push(`${path}?${next}`, { scroll: false }); } if (method === "DELETE" && search.get("view") === id) { const next = new URLSearchParams(search.toString()); next.delete("view"); router.push(`${path}?${next}`, { scroll: false }); } } catch (reason) { setError(requestError(reason, labels)); } finally { setBusy(false); } }
  function apply(view: SavedView) { const next = new URLSearchParams(view.state.query); for (const key of ["recordType", "recordId", "tab"]) { const value = search.get(key); if (value) next.set(key, value); } next.set("view", view.id); router.push(`${path}?${next}`, { scroll: false }); }
  function edit(view: SavedView | "new") { setError(""); setEditing(view); setName(view === "new" ? "" : view.name); setShared(view === "new" ? false : view.shared); }
  return <div className="space-y-2"><details className="rounded-lg border bg-background"><summary className="flex min-h-11 cursor-pointer items-center gap-2 px-3 py-3 text-sm font-medium"><Bookmark className="size-4" aria-hidden="true" />{selected?.name ?? labels.views.title}{changed && <span className="text-xs font-normal text-muted-foreground"> · {labels.views.changed}</span>}</summary><div className="space-y-4 border-t p-3"><p className="text-sm text-muted-foreground">{labels.views.description}</p><Button variant="outline" disabled={busy} onClick={() => edit("new")}>{labels.views.add}</Button>{loading && <p role="status">{labels.loading}</p>}{!loading && !views.length && <p className="text-sm text-muted-foreground">{labels.views.empty}</p>}{([true, false] as const).map(mine => <section key={String(mine)} className="space-y-2">{views.some(view => view.mine === mine) && <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{mine ? labels.views.mine : labels.views.workspace}</h3>}{views.filter(view => view.mine === mine).map(view => <div key={view.id} className="flex flex-wrap items-center gap-2 rounded-md border p-2"><Button variant={selected?.id === view.id ? "secondary" : "ghost"} className="min-w-0 max-w-full justify-start whitespace-normal text-left" onClick={() => apply(view)} aria-pressed={selected?.id === view.id}>{view.name}</Button><span className="text-xs text-muted-foreground">{view.shared ? labels.views.shared : labels.views.private}</span>{view.mine && <div className="flex flex-wrap gap-1 sm:ml-auto"><Button size="sm" variant="ghost" disabled={busy} onClick={() => edit(view)}>{labels.edit}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => void mutate("PATCH", view.id, { state: captureSavedViewState(entity, new URLSearchParams(search.toString())) })}>{labels.views.update}</Button><Button size="sm" variant="ghost" className="text-destructive" disabled={busy} onClick={() => { setError(""); setDeleting(view); }}>{labels.views.delete}</Button></div>}</div>)}</section>)}{error && !editing && !deleting && <div role="alert" className="text-sm text-destructive">{error}<Button variant="ghost" onClick={() => { setError(""); setRevision(value => value + 1); }}>{labels.retry}</Button></div>}</div></details>
    <Dialog open={Boolean(editing)} onOpenChange={value => { if (!value && !busy) setEditing(null); }}><DialogContent closeLabel={labels.close}><DialogTitle>{editing === "new" ? labels.views.add : labels.views.rename}</DialogTitle><DialogDescription>{labels.views.description}</DialogDescription><form className="space-y-4" onSubmit={event => { event.preventDefault(); if (!editing) return; void mutate(editing === "new" ? "POST" : "PATCH", editing === "new" ? null : editing.id, editing === "new" ? { entity, name: name.trim(), shared, state: captureSavedViewState(entity, new URLSearchParams(search.toString())) } : { name: name.trim(), shared }); }}><label className="block space-y-1 text-sm">{labels.views.name}<Input value={name} onChange={event => setName(event.target.value)} required maxLength={120} disabled={busy} /></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={shared} disabled={busy} onChange={event => setShared(event.target.checked)} />{labels.views.shared}</label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => setEditing(null)}>{labels.cancel}</Button><Button type="submit" disabled={busy || !name.trim()}>{busy ? labels.loading : labels.save}</Button></div></form></DialogContent></Dialog>
    <Dialog open={Boolean(deleting)} onOpenChange={value => { if (!value && !busy) setDeleting(null); }}><DialogContent closeLabel={labels.close}><DialogTitle>{labels.views.delete} · {deleting?.name}</DialogTitle><DialogDescription>{labels.views.deleteConfirm}</DialogDescription>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={() => setDeleting(null)}>{labels.cancel}</Button><Button variant="destructive" disabled={busy} onClick={() => { if (deleting?.mine) void mutate("DELETE", deleting.id); }}>{busy ? labels.loading : labels.views.delete}</Button></div></DialogContent></Dialog>
  </div>;
}
