"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUp, Add as Plus, SettingsAdjust as Settings2, OverflowMenuVertical, Edit, Archive, Undo, TrashCan, ArrowLeft } from "@carbon/icons-react";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { FIELD_TYPES, fieldCreateInputSchema, type FieldDefinition, type FieldType } from "@/lib/services/custom-fields/field-contracts";
import type { EntityType } from "@/lib/listing/list-state";
import { invalidateCrm } from "@/lib/listing/invalidation";
import type { CrmDictionary } from "@/lib/i18n/crm-dictionary";
import { crmRequest, requestError } from "../record-types";
import { FormSelect } from "../record-sheet/form-select";

type Draft = { label: string; type: FieldType; required: boolean; showOnSheet: boolean; showOnTable: boolean; showOnFilter: boolean; options: { id?: string; label: string }[] };
const emptyDraft: Draft = { label: "", type: "text", required: false, showOnSheet: true, showOnTable: false, showOnFilter: false, options: [] };
export function FieldsSheet({ entity, labels }: { entity: EntityType; labels: CrmDictionary }) {
  const manageTrigger = useRef<HTMLButtonElement>(null);
  const [open, setOpen] = useState(false); const [fields, setFields] = useState<FieldDefinition[]>([]); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [revision, setRevision] = useState(0);
  const [editing, setEditing] = useState<FieldDefinition | "new" | null>(null); const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [deleting, setDeleting] = useState<FieldDefinition | null>(null); const [coverage, setCoverage] = useState<{ filled: number; total: number } | null>(null); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [recoverId, setRecoverId] = useState("");
  useEffect(() => { if (!open) return; const controller = new AbortController(); setLoading(true); setError(""); crmRequest<FieldDefinition[]>(`/api/crm/fields?entity=${entity}&includeArchived=true`, { signal: controller.signal }).then(setFields).catch(() => { if (!controller.signal.aborted) setError(labels.error); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [open, entity, revision, labels]);
  useEffect(() => { setCoverage(null); setPassword(""); setConfirmation(""); if (!deleting) return; const controller = new AbortController(); crmRequest<{ filled: number; total: number }>(`/api/crm/fields/${encodeURIComponent(deleting.id)}?coverage=true`, { signal: controller.signal }).then(setCoverage).catch(() => { if (!controller.signal.aborted) setError(labels.error); }); return () => controller.abort(); }, [deleting, labels, revision]);
  async function mutate(url: string, method: string, body: unknown, done?: () => void) { setBusy(true); setError(""); try { await crmRequest(url, { method, body: JSON.stringify(body) }); done?.(); setRevision(value => value + 1); invalidateCrm(entity); } catch (reason) { setError(requestError(reason, labels)); } finally { setBusy(false); } }
  function edit(field: FieldDefinition | "new") { setError(""); setEditing(field); setDraft(field === "new" ? { ...emptyDraft, options: [] } : { label: field.label, type: field.type, required: field.required, showOnSheet: field.showOnSheet, showOnTable: field.showOnTable, showOnFilter: field.showOnFilter, options: field.options.filter(option => !option.archivedAt).map(({ id, label }) => ({ id, label })) }); }
  function reorder(index: number, offset: number) { const ids = fields.map(field => field.id); [ids[index], ids[index + offset]] = [ids[index + offset], ids[index]]; void mutate("/api/crm/fields", "PATCH", { entity, ids }); }
  function save() { const parsed = fieldCreateInputSchema.safeParse({ ...draft, entity, options: draft.type === "select" ? draft.options : [] }); if (!parsed.success) { setError(labels.invalid); return; } const { entity: _entity, ...data } = parsed.data; void mutate(`/api/crm/fields${editing && editing !== "new" ? `/${encodeURIComponent(editing.id)}` : ""}`, editing === "new" ? "POST" : "PATCH", editing === "new" ? parsed.data : { action: "update", data }, () => setEditing(null)); }
  const flags = ["required", "showOnSheet", "showOnTable", "showOnFilter"] as const;
  return <><Button ref={manageTrigger} variant="outline" onClick={() => setOpen(true)}><Settings2 className="mr-2 size-4" aria-hidden="true" />{labels.custom.manage}</Button>
    <Dialog open={open} onOpenChange={value => { if (!busy) { setOpen(value); if (!value) { setEditing(null); setDeleting(null); setError(""); } } }}><DialogContent variant="sheet" sheetSize="md" closeLabel={labels.close} onCloseAutoFocus={event => { event.preventDefault(); manageTrigger.current?.focus(); }}>
      <div className="flex items-start gap-2 border-b px-5 py-3 pr-14">{editing && <Button variant="ghost" size="icon-sm" disabled={busy} aria-label={labels.cancel} onClick={() => { setEditing(null); setError(""); }}><ArrowLeft size={16} /></Button>}<div className="space-y-0.5"><DialogTitle className="text-sm">{editing === "new" ? labels.custom.add : editing ? editing.label : labels.custom.manage}</DialogTitle><DialogDescription className="text-xs">{labels[entity]}</DialogDescription></div></div>
      <div className="min-h-0 flex-1 space-y-4 overflow-auto" aria-busy={loading || busy}>
        {loading && <p role="status">{labels.loading}</p>}
        {!editing && <><div className="flex items-center justify-between border-b px-5 py-3"><span className="text-xs font-medium text-muted-foreground">{labels.fields}</span><Button size="sm" variant="outline" onClick={() => edit("new")} disabled={busy}><Plus size={14} />{labels.custom.add}</Button></div><ol>{fields.map((field, index) => <li key={field.id} className="flex items-center gap-2.5 border-b px-5 py-2"><button type="button" disabled={busy} onClick={() => edit(field)} className="min-w-0 flex-1 rounded-sm text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-ring"><span className="block truncate text-xs font-medium">{field.label}</span><span className="block truncate text-xs text-muted-foreground">{labels.custom.types[field.type]}{field.required ? ` · ${labels.required}` : ""}{field.showOnTable ? ` · ${labels.custom.showOnTable}` : ""}</span></button>{field.archivedAt && <Badge variant="secondary">{labels.archived}</Badge>}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" disabled={busy} aria-label={`${labels.edit}: ${field.label}`}><OverflowMenuVertical size={16} /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => edit(field)}><Edit size={16} />{labels.edit}</DropdownMenuItem><DropdownMenuItem disabled={index === 0} onSelect={() => reorder(index, -1)}><ArrowUp size={16} />{labels.custom.up}</DropdownMenuItem><DropdownMenuItem disabled={index === fields.length - 1} onSelect={() => reorder(index, 1)}><ArrowDown size={16} />{labels.custom.down}</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onSelect={() => void mutate(`/api/crm/fields/${encodeURIComponent(field.id)}`, "PATCH", { action: field.archivedAt ? "restore" : "archive" })}>{field.archivedAt ? <Undo size={16} /> : <Archive size={16} />}{field.archivedAt ? labels.restore : labels.archive}</DropdownMenuItem><DropdownMenuItem className="text-destructive" onSelect={() => { setError(""); setDeleting(field); }}><TrashCan size={16} />{labels.custom.delete}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></li>)}</ol>{!loading && !fields.length && <p className="px-5 py-8 text-center text-xs text-muted-foreground">{labels.custom.empty}</p>}
        <details className="border-b px-5 py-3"><summary className="cursor-pointer text-sm font-medium">{labels.custom.recover}</summary><form className="mt-3 space-y-3" onSubmit={event => { event.preventDefault(); void mutate(`/api/crm/fields/${encodeURIComponent(recoverId.trim())}`, "PATCH", { action: "recover" }, () => setRecoverId("")); }}><label className="block space-y-1 text-sm">{labels.custom.recoverId}<Input value={recoverId} onChange={event => setRecoverId(event.target.value)} required maxLength={100} /></label><Button type="submit" disabled={busy || !recoverId.trim()} variant="outline">{labels.restore}</Button></form></details></>}
        {editing && <form className="space-y-5 px-5 py-3" onSubmit={event => { event.preventDefault(); save(); }}>{editing !== "new" && <p className="break-all text-xs text-muted-foreground">{labels.custom.key}: {editing.key}</p>}<label className="block space-y-1 text-sm">{labels.custom.label}<Input required maxLength={200} value={draft.label} onChange={event => setDraft(previous => ({ ...previous, label: event.target.value }))} disabled={busy} /></label><label className="block space-y-1 text-sm">{labels.custom.type}<FormSelect id="custom-field-type" disabled={busy} value={draft.type} onValueChange={type => setDraft(previous => ({ ...previous, type: type as FieldType, showOnFilter: ["select", "user"].includes(type) && previous.showOnFilter }))} options={FIELD_TYPES.map(type => ({ value: type, label: labels.custom.types[type] }))} /></label>{editing !== "new" && <p className="text-xs text-muted-foreground">{labels.custom.typeHelp}</p>}
        {draft.type === "select" && <fieldset className="space-y-3 rounded-lg border p-3"><legend className="px-1 text-sm font-medium">{labels.custom.options}</legend><p className="text-xs text-muted-foreground">{labels.custom.optionsHelp}</p>{draft.options.map((option, index) => <div key={option.id ?? `new-${index}`} className="flex items-center gap-2"><Input aria-label={`${labels.custom.options} ${index + 1}`} required value={option.label} maxLength={200} disabled={busy} onChange={event => setDraft(previous => ({ ...previous, options: previous.options.map((value, at) => at === index ? { ...value, label: event.target.value } : value) }))} /><Button type="button" variant="ghost" disabled={busy || index === 0} aria-label={`${labels.custom.up}: ${option.label}`} onClick={() => setDraft(previous => { const options = [...previous.options]; [options[index - 1], options[index]] = [options[index], options[index - 1]]; return { ...previous, options }; })}><ArrowUp className="size-4" /></Button><Button type="button" variant="ghost" disabled={busy} aria-label={`${labels.custom.removeOption}: ${option.label}`} onClick={() => setDraft(previous => ({ ...previous, options: previous.options.filter((_, at) => at !== index) }))}>×</Button></div>)}<Button type="button" variant="outline" disabled={busy || draft.options.length >= 100} onClick={() => setDraft(previous => ({ ...previous, options: [...previous.options, { label: "" }] }))}>{labels.custom.addOption}</Button>{editing !== "new" && editing.options.filter(option => option.archivedAt && !draft.options.some(active => active.id === option.id)).map(option => <div key={option.id} className="flex items-center justify-between gap-2 text-sm"><span>{option.label} · {labels.archived}</span><Button type="button" variant="ghost" disabled={busy} onClick={() => setDraft(previous => ({ ...previous, options: [...previous.options, { id: option.id, label: option.label }] }))}>{labels.restore}</Button></div>)}</fieldset>}
        <div>{flags.map(flag => <label key={flag} className="flex min-h-9 items-center gap-2 text-xs"><Checkbox checked={draft[flag]} disabled={busy || flag === "showOnFilter" && !["select", "user"].includes(draft.type)} onCheckedChange={checked => setDraft(previous => ({ ...previous, [flag]: checked === true }))} />{flag === "required" ? labels.required : labels.custom[flag]}</label>)}</div><div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => { setEditing(null); setError(""); }}>{labels.cancel}</Button><Button type="submit" disabled={busy}>{busy ? labels.loading : labels.save}</Button></div></form>}
        {error && !deleting && <div role="alert" className="text-sm text-destructive">{error}{!editing && <Button variant="ghost" onClick={() => setRevision(value => value + 1)}>{labels.retry}</Button>}</div>}
      </div>
      <Dialog open={Boolean(deleting)} onOpenChange={value => { if (!value && !busy) setDeleting(null); }}><DialogContent closeLabel={labels.close}><DialogTitle>{labels.custom.delete} · {deleting?.label}</DialogTitle><DialogDescription>{labels.custom.deleteHelp}</DialogDescription><p className="break-all text-xs">{labels.custom.recoverId}: {deleting?.id}</p><p role="status" className="text-sm">{labels.custom.coverage}: {coverage ? `${coverage.filled} / ${coverage.total}` : labels.loading}</p><form className="space-y-4" onSubmit={event => { event.preventDefault(); if (!deleting || !coverage || confirmation !== deleting.key) return; const target = deleting; void mutate(`/api/crm/fields/${encodeURIComponent(target.id)}`, "DELETE", { password, confirmation }, () => { setDeleting(null); setRecoverId(target.id); setPassword(""); }); }}><label className="block space-y-1 text-sm">{labels.custom.password}<Input type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} required maxLength={1000} disabled={busy} /></label><label className="block space-y-1 text-sm">{labels.custom.confirmation}: <code>{deleting?.key}</code><Input value={confirmation} onChange={event => setConfirmation(event.target.value)} required autoComplete="off" disabled={busy} /></label>{error && <div role="alert" className="text-sm text-destructive">{error}{!coverage && <Button type="button" variant="ghost" onClick={() => setRevision(value => value + 1)}>{labels.retry}</Button>}</div>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => setDeleting(null)}>{labels.cancel}</Button><Button type="submit" variant="destructive" disabled={busy || !coverage || !password || confirmation !== deleting?.key}>{busy ? labels.loading : labels.custom.delete}</Button></div></form></DialogContent></Dialog>
    </DialogContent></Dialog>
  </>;
}
